//===- PIRAttrs.td - PIR attributes ------------------------*- tablegen -*-===//
//
// Copyright 2025 The ASTER Authors
//
// Licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#ifndef ASTER_DIALECT_PIR_IR_PIRATTRS_TD
#define ASTER_DIALECT_PIR_IR_PIRATTRS_TD

include "aster/Dialect/PIR/IR/PIRDialect.td"

//===----------------------------------------------------------------------===//
// PIR attributes
//===----------------------------------------------------------------------===//

#endif // ASTER_DIALECT_PIR_IR_PIRATTRS_TD
