// RUN: aster-opt --split-input-file --test-liveness-analysis %s | FileCheck %s

// CHECK-LABEL:  SSA map:
// CHECK:  Operation: `%{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>`
// CHECK:    results: [0 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>`
// CHECK:    results: [1 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.alloca : !amdgcn.sgpr<?>`
// CHECK:    results: [2 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.alloca : !amdgcn.sgpr<?>`
// CHECK:    results: [3 = `%{{.*}}`]
// CHECK:  Op: module {...}
// CHECK:    LIVE BEFORE: []
// CHECK:  Symbol: no_interference_mixed
// CHECK:  Op: amdgcn.kernel @no_interference_mixed {...}
// CHECK:    LIVE BEFORE: []
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:    LIVE BEFORE: []
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:    LIVE BEFORE: []
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.sgpr<?>
// CHECK:    LIVE BEFORE: []
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.sgpr<?>
// CHECK:    LIVE BEFORE: [2 = `%{{.*}}`]
// CHECK:  Op: amdgcn.test_inst outs %{{.*}} ins %{{.*}} : (!amdgcn.vgpr<?>, !amdgcn.sgpr<?>) -> ()
// CHECK:    LIVE BEFORE: [2 = `%{{.*}}`, 3 = `%{{.*}}`]
// CHECK:  Op: amdgcn.test_inst outs %{{.*}} ins %{{.*}} : (!amdgcn.vgpr<?>, !amdgcn.sgpr<?>) -> ()
// CHECK:    LIVE BEFORE: [3 = `%{{.*}}`]
// CHECK:  Op: amdgcn.end_kernel
// CHECK:    LIVE BEFORE: []
amdgcn.module @no_interference_mixed_mod target = <gfx942> {
amdgcn.kernel @no_interference_mixed {
  %0 = alloca : !amdgcn.vgpr<?>
  %1 = alloca : !amdgcn.vgpr<?>
  %2 = alloca : !amdgcn.sgpr<?>
  %3 = alloca : !amdgcn.sgpr<?>
  test_inst outs %0 ins %2 : (!amdgcn.vgpr<?>, !amdgcn.sgpr<?>) -> ()
  test_inst outs %1 ins %3 : (!amdgcn.vgpr<?>, !amdgcn.sgpr<?>) -> ()
  end_kernel
}
}

// -----
// CHECK-LABEL:  SSA map:
// CHECK:  Operation: `%{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>`
// CHECK:    results: [0 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>`
// CHECK:    results: [1 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.alloca : !amdgcn.sgpr<?>`
// CHECK:    results: [2 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.alloca : !amdgcn.sgpr<?>`
// CHECK:    results: [3 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>`
// CHECK:    results: [4 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>`
// CHECK:    results: [5 = `%{{.*}}`]
// CHECK:  Op: module {...}
// CHECK:    LIVE BEFORE: []
// CHECK:  Symbol: interference_mixed_all_live
// CHECK:  Op: amdgcn.kernel @interference_mixed_all_live {...}
// CHECK:    LIVE BEFORE: []
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:    LIVE BEFORE: []
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:    LIVE BEFORE: [0 = `%{{.*}}`]
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.sgpr<?>
// CHECK:    LIVE BEFORE: [0 = `%{{.*}}`, 1 = `%{{.*}}`]
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.sgpr<?>
// CHECK:    LIVE BEFORE: [0 = `%{{.*}}`, 1 = `%{{.*}}`, 2 = `%{{.*}}`]
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:    LIVE BEFORE: [0 = `%{{.*}}`, 1 = `%{{.*}}`, 2 = `%{{.*}}`, 3 = `%{{.*}}`]
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:    LIVE BEFORE: [0 = `%{{.*}}`, 1 = `%{{.*}}`, 2 = `%{{.*}}`, 3 = `%{{.*}}`]
// CHECK:  Op: amdgcn.test_inst outs %{{.*}} ins %{{.*}}, %{{.*}} : (!amdgcn.vgpr<?>, !amdgcn.sgpr<?>, !amdgcn.vgpr<?>) -> ()
// CHECK:    LIVE BEFORE: [0 = `%{{.*}}`, 1 = `%{{.*}}`, 2 = `%{{.*}}`, 3 = `%{{.*}}`]
// CHECK:  Op: amdgcn.test_inst outs %{{.*}} ins %{{.*}}, %{{.*}} : (!amdgcn.vgpr<?>, !amdgcn.sgpr<?>, !amdgcn.vgpr<?>) -> ()
// CHECK:    LIVE BEFORE: [0 = `%{{.*}}`, 1 = `%{{.*}}`, 3 = `%{{.*}}`]
// CHECK:  Op: amdgcn.test_inst ins %{{.*}}, %{{.*}} : (!amdgcn.vgpr<?>, !amdgcn.vgpr<?>) -> ()
// CHECK:    LIVE BEFORE: [0 = `%{{.*}}`, 1 = `%{{.*}}`]
// CHECK:  Op: amdgcn.end_kernel
// CHECK:    LIVE BEFORE: []
amdgcn.module @interference_mixed_all_live_mod target = <gfx942> {
amdgcn.kernel @interference_mixed_all_live {
  %0 = alloca : !amdgcn.vgpr<?>
  %1 = alloca : !amdgcn.vgpr<?>
  %2 = alloca : !amdgcn.sgpr<?>
  %3 = alloca : !amdgcn.sgpr<?>
  %4 = alloca : !amdgcn.vgpr<?>
  %5 = alloca : !amdgcn.vgpr<?>
  test_inst outs %0 ins %2, %0 : (!amdgcn.vgpr<?>, !amdgcn.sgpr<?>, !amdgcn.vgpr<?>) -> ()
  test_inst outs %1 ins %3, %1 : (!amdgcn.vgpr<?>, !amdgcn.sgpr<?>, !amdgcn.vgpr<?>) -> ()
  test_inst ins %0, %1 : (!amdgcn.vgpr<?>, !amdgcn.vgpr<?>) -> ()
  end_kernel
}
}

// -----
// CHECK-LABEL:  SSA map:
// CHECK:  Operation: `%{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>`
// CHECK:    results: [0 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>`
// CHECK:    results: [1 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.alloca : !amdgcn.sgpr<?>`
// CHECK:    results: [2 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.alloca : !amdgcn.sgpr<?>`
// CHECK:    results: [3 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>`
// CHECK:    results: [4 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>`
// CHECK:    results: [5 = `%{{.*}}`]
// CHECK:  Op: module {...}
// CHECK:    LIVE BEFORE: []
// CHECK:  Symbol: interference_mixed_with_reuse
// CHECK:  Op: amdgcn.kernel @interference_mixed_with_reuse {...}
// CHECK:    LIVE BEFORE: []
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:    LIVE BEFORE: []
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:    LIVE BEFORE: [0 = `%{{.*}}`]
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.sgpr<?>
// CHECK:    LIVE BEFORE: [0 = `%{{.*}}`, 1 = `%{{.*}}`]
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.sgpr<?>
// CHECK:    LIVE BEFORE: [0 = `%{{.*}}`, 1 = `%{{.*}}`, 2 = `%{{.*}}`]
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:    LIVE BEFORE: [0 = `%{{.*}}`, 1 = `%{{.*}}`, 2 = `%{{.*}}`, 3 = `%{{.*}}`]
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:    LIVE BEFORE: [0 = `%{{.*}}`, 1 = `%{{.*}}`, 2 = `%{{.*}}`, 3 = `%{{.*}}`]
// CHECK:  Op: amdgcn.test_inst outs %{{.*}} ins %{{.*}}, %{{.*}} : (!amdgcn.vgpr<?>, !amdgcn.sgpr<?>, !amdgcn.vgpr<?>) -> ()
// CHECK:    LIVE BEFORE: [0 = `%{{.*}}`, 1 = `%{{.*}}`, 2 = `%{{.*}}`, 3 = `%{{.*}}`]
// CHECK:  Op: amdgcn.test_inst outs %{{.*}} ins %{{.*}}, %{{.*}} : (!amdgcn.vgpr<?>, !amdgcn.sgpr<?>, !amdgcn.vgpr<?>) -> ()
// CHECK:    LIVE BEFORE: [0 = `%{{.*}}`, 1 = `%{{.*}}`, 3 = `%{{.*}}`]
// CHECK:  Op: amdgcn.test_inst ins %{{.*}}, %{{.*}} : (!amdgcn.vgpr<?>, !amdgcn.vgpr<?>) -> ()
// CHECK:    LIVE BEFORE: [0 = `%{{.*}}`, 1 = `%{{.*}}`]
// CHECK:  Op: amdgcn.end_kernel
// CHECK:    LIVE BEFORE: []
amdgcn.module @interference_mixed_with_reuse_mod target = <gfx942> {
amdgcn.kernel @interference_mixed_with_reuse {
  %0 = alloca : !amdgcn.vgpr<?>
  %1 = alloca : !amdgcn.vgpr<?>
  %2 = alloca : !amdgcn.sgpr<?>
  %3 = alloca : !amdgcn.sgpr<?>
  %4 = alloca : !amdgcn.vgpr<?>
  %5 = alloca : !amdgcn.vgpr<?>
  test_inst outs %0 ins %2, %0 : (!amdgcn.vgpr<?>, !amdgcn.sgpr<?>, !amdgcn.vgpr<?>) -> ()
  test_inst outs %1 ins %3, %1 : (!amdgcn.vgpr<?>, !amdgcn.sgpr<?>, !amdgcn.vgpr<?>) -> ()
  test_inst ins %0, %1 : (!amdgcn.vgpr<?>, !amdgcn.vgpr<?>) -> ()
  end_kernel
}
}

// -----
// CHECK-LABEL:  SSA map:
// CHECK:  Operation: `%{{.*}} = func.call @rand() : () -> i1`
// CHECK:    results: [0 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>`
// CHECK:    results: [1 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>`
// CHECK:    results: [2 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.alloca : !amdgcn.sgpr<?>`
// CHECK:    results: [3 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.alloca : !amdgcn.sgpr<?>`
// CHECK:    results: [4 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>`
// CHECK:    results: [5 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>`
// CHECK:    results: [6 = `%{{.*}}`]
// CHECK:  Op: module {...}
// CHECK:    LIVE BEFORE: []
// CHECK:  Symbol: rand
// CHECK:  Op: func.func private @rand() -> i1
// CHECK:    LIVE BEFORE: []
// CHECK:  Symbol: interference_cf
// CHECK:  Op: amdgcn.kernel @interference_cf {...}
// CHECK:    LIVE BEFORE: []
// CHECK:  Op: %{{.*}} = func.call @rand() : () -> i1
// CHECK:    LIVE BEFORE: []
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:    LIVE BEFORE: []
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:    LIVE BEFORE: []
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.sgpr<?>
// CHECK:    LIVE BEFORE: []
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.sgpr<?>
// CHECK:    LIVE BEFORE: [3 = `%{{.*}}`]
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:    LIVE BEFORE: [3 = `%{{.*}}`, 4 = `%{{.*}}`]
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:    LIVE BEFORE: [3 = `%{{.*}}`, 4 = `%{{.*}}`, 5 = `%{{.*}}`]
// CHECK:  Op: amdgcn.test_inst outs %{{.*}} ins %{{.*}} : (!amdgcn.vgpr<?>, !amdgcn.sgpr<?>) -> ()
// CHECK:    LIVE BEFORE: [3 = `%{{.*}}`, 4 = `%{{.*}}`, 5 = `%{{.*}}`, 6 = `%{{.*}}`]
// CHECK:  Op: amdgcn.test_inst outs %{{.*}} ins %{{.*}} : (!amdgcn.vgpr<?>, !amdgcn.sgpr<?>) -> ()
// CHECK:    LIVE BEFORE: [1 = `%{{.*}}`, 4 = `%{{.*}}`, 5 = `%{{.*}}`, 6 = `%{{.*}}`]
// CHECK:  Op: cf.cond_br %{{.*}}, ^bb1, ^bb2
// CHECK:    LIVE BEFORE: [1 = `%{{.*}}`, 2 = `%{{.*}}`, 5 = `%{{.*}}`, 6 = `%{{.*}}`]
// CHECK:  Op: amdgcn.test_inst outs %{{.*}} ins %{{.*}} : (!amdgcn.vgpr<?>, !amdgcn.vgpr<?>) -> ()
// CHECK:    LIVE BEFORE: [1 = `%{{.*}}`, 6 = `%{{.*}}`]
// CHECK:  Op: cf.br ^bb3
// CHECK:    LIVE BEFORE: [5 = `%{{.*}}`, 6 = `%{{.*}}`]
// CHECK:  Op: amdgcn.test_inst outs %{{.*}} ins %{{.*}} : (!amdgcn.vgpr<?>, !amdgcn.vgpr<?>) -> ()
// CHECK:    LIVE BEFORE: [2 = `%{{.*}}`, 5 = `%{{.*}}`]
// CHECK:  Op: cf.br ^bb3
// CHECK:    LIVE BEFORE: [5 = `%{{.*}}`, 6 = `%{{.*}}`]
// CHECK:  Op: amdgcn.test_inst ins %{{.*}}, %{{.*}} : (!amdgcn.vgpr<?>, !amdgcn.vgpr<?>) -> ()
// CHECK:    LIVE BEFORE: [5 = `%{{.*}}`, 6 = `%{{.*}}`]
// CHECK:  Op: amdgcn.end_kernel
// CHECK:    LIVE BEFORE: []
amdgcn.module @interference_cf_mod target = <gfx942> {
func.func private @rand() -> i1
amdgcn.kernel @interference_cf {
  %0 = func.call @rand() : () -> i1
  %1 = alloca : !amdgcn.vgpr<?>
  %2 = alloca : !amdgcn.vgpr<?>
  %3 = alloca : !amdgcn.sgpr<?>
  %4 = alloca : !amdgcn.sgpr<?>
  %5 = alloca : !amdgcn.vgpr<?>
  %6 = alloca : !amdgcn.vgpr<?>
  test_inst outs %1 ins %3 : (!amdgcn.vgpr<?>, !amdgcn.sgpr<?>) -> ()
  test_inst outs %2 ins %4 : (!amdgcn.vgpr<?>, !amdgcn.sgpr<?>) -> ()
  cf.cond_br %0, ^bb1, ^bb2
^bb1:  // CHECK: pred: ^bb0
  test_inst outs %5 ins %1 : (!amdgcn.vgpr<?>, !amdgcn.vgpr<?>) -> ()
  cf.br ^bb3
^bb2:  // CHECK: pred: ^bb0
  test_inst outs %6 ins %2 : (!amdgcn.vgpr<?>, !amdgcn.vgpr<?>) -> ()
  cf.br ^bb3
^bb3:  // CHECK: 2 preds: ^bb1, ^bb2
  test_inst ins %5, %6 : (!amdgcn.vgpr<?>, !amdgcn.vgpr<?>) -> ()
  end_kernel
}
}

// -----
// CHECK-LABEL:  SSA map:
// CHECK:  Operation: `%{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>`
// CHECK:    results: [0 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>`
// CHECK:    results: [1 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>`
// CHECK:    results: [2 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>`
// CHECK:    results: [3 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.make_register_range %{{.*}}, %{{.*}} : !amdgcn.vgpr<?>, !amdgcn.vgpr<?>`
// CHECK:    results: [4 = `%{{.*}}`]
// CHECK:  Op: module {...}
// CHECK:    LIVE BEFORE: []
// CHECK:  Symbol: test_make_range_liveness
// CHECK:  Op: amdgcn.kernel @test_make_range_liveness {...}
// CHECK:    LIVE BEFORE: []
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:    LIVE BEFORE: []
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:    LIVE BEFORE: []
// CHECK:  Op: amdgcn.test_inst outs %{{.*}} : (!amdgcn.vgpr<?>) -> ()
// CHECK:    LIVE BEFORE: []
// CHECK:  Op: amdgcn.test_inst outs %{{.*}} : (!amdgcn.vgpr<?>) -> ()
// CHECK:    LIVE BEFORE: [0 = `%{{.*}}`]
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:    LIVE BEFORE: [0 = `%{{.*}}`, 1 = `%{{.*}}`]
// CHECK:  Op: amdgcn.test_inst outs %{{.*}} ins %{{.*}} : (!amdgcn.vgpr<?>, !amdgcn.vgpr<?>) -> ()
// CHECK:    LIVE BEFORE: [0 = `%{{.*}}`, 1 = `%{{.*}}`]
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:    LIVE BEFORE: [0 = `%{{.*}}`, 1 = `%{{.*}}`, 2 = `%{{.*}}`]
// CHECK:  Op: amdgcn.test_inst outs %{{.*}} ins %{{.*}} : (!amdgcn.vgpr<?>, !amdgcn.vgpr<?>) -> ()
// CHECK:    LIVE BEFORE: [0 = `%{{.*}}`, 1 = `%{{.*}}`, 2 = `%{{.*}}`]
// CHECK:  Op: %{{.*}} = amdgcn.make_register_range %{{.*}}, %{{.*}} : !amdgcn.vgpr<?>, !amdgcn.vgpr<?>
// CHECK:    LIVE BEFORE: [0 = `%{{.*}}`, 1 = `%{{.*}}`, 2 = `%{{.*}}`]
// CHECK:  Op: amdgcn.test_inst ins %{{.*}}, %{{.*}} : (!amdgcn.vgpr<[? : ? + 2]>, !amdgcn.vgpr<?>) -> ()
// CHECK:    LIVE BEFORE: [0 = `%{{.*}}`, 1 = `%{{.*}}`, 2 = `%{{.*}}`]
// CHECK:  Op: amdgcn.end_kernel
// CHECK:    LIVE BEFORE: []
amdgcn.module @test_make_range_liveness_mod target = <gfx942> {
amdgcn.kernel @test_make_range_liveness {
  %0 = alloca : !amdgcn.vgpr<?>
  %1 = alloca : !amdgcn.vgpr<?>
  test_inst outs %0 : (!amdgcn.vgpr<?>) -> ()
  test_inst outs %1 : (!amdgcn.vgpr<?>) -> ()
  %4 = alloca : !amdgcn.vgpr<?>
  test_inst outs %4 ins %1 : (!amdgcn.vgpr<?>, !amdgcn.vgpr<?>) -> ()
  %6 = alloca : !amdgcn.vgpr<?>
  test_inst outs %6 ins %4 : (!amdgcn.vgpr<?>, !amdgcn.vgpr<?>) -> ()
  %8 = make_register_range %0, %1 : !amdgcn.vgpr<?>, !amdgcn.vgpr<?>
  test_inst ins %8, %4 : (!amdgcn.vgpr<[? : ? + 2]>, !amdgcn.vgpr<?>) -> ()
  end_kernel
}
}

// -----
// CHECK-LABEL:  SSA map:
// CHECK:  Operation: `%{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>`
// CHECK:    results: [0 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>`
// CHECK:    results: [1 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>`
// CHECK:    results: [2 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>`
// CHECK:    results: [3 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.make_register_range %{{.*}}, %{{.*}} : !amdgcn.vgpr<?>, !amdgcn.vgpr<?>`
// CHECK:    results: [4 = `%{{.*}}`]
// CHECK:  Op: module {...}
// CHECK:    LIVE BEFORE: []
// CHECK:  Symbol: test_make_range_liveness_1
// CHECK:  Op: amdgcn.kernel @test_make_range_liveness_1 {...}
// CHECK:    LIVE BEFORE: []
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:    LIVE BEFORE: []
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:    LIVE BEFORE: []
// CHECK:  Op: amdgcn.test_inst outs %{{.*}} : (!amdgcn.vgpr<?>) -> ()
// CHECK:    LIVE BEFORE: []
// CHECK:  Op: amdgcn.test_inst outs %{{.*}} : (!amdgcn.vgpr<?>) -> ()
// CHECK:    LIVE BEFORE: [0 = `%{{.*}}`]
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:    LIVE BEFORE: [0 = `%{{.*}}`, 1 = `%{{.*}}`]
// CHECK:  Op: amdgcn.test_inst outs %{{.*}} ins %{{.*}} : (!amdgcn.vgpr<?>, !amdgcn.vgpr<?>) -> ()
// CHECK:    LIVE BEFORE: [0 = `%{{.*}}`, 1 = `%{{.*}}`]
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:    LIVE BEFORE: [0 = `%{{.*}}`, 1 = `%{{.*}}`, 2 = `%{{.*}}`]
// CHECK:  Op: amdgcn.test_inst outs %{{.*}} ins %{{.*}} : (!amdgcn.vgpr<?>, !amdgcn.vgpr<?>) -> ()
// CHECK:    LIVE BEFORE: [0 = `%{{.*}}`, 1 = `%{{.*}}`, 2 = `%{{.*}}`]
// CHECK:  Op: %{{.*}} = amdgcn.make_register_range %{{.*}}, %{{.*}} : !amdgcn.vgpr<?>, !amdgcn.vgpr<?>
// CHECK:    LIVE BEFORE: [0 = `%{{.*}}`, 1 = `%{{.*}}`, 2 = `%{{.*}}`]
// CHECK:  Op: amdgcn.test_inst ins %{{.*}}, %{{.*}} : (!amdgcn.vgpr<[? : ? + 2]>, !amdgcn.vgpr<?>) -> ()
// CHECK:    LIVE BEFORE: [0 = `%{{.*}}`, 1 = `%{{.*}}`, 2 = `%{{.*}}`]
// CHECK:  Op: amdgcn.end_kernel
// CHECK:    LIVE BEFORE: []
amdgcn.module @test_make_range_liveness_1_mod target = <gfx942> {
amdgcn.kernel @test_make_range_liveness_1 {
  %0 = alloca : !amdgcn.vgpr<?>
  %1 = alloca : !amdgcn.vgpr<?>
  test_inst outs %0 : (!amdgcn.vgpr<?>) -> ()
  test_inst outs %1 : (!amdgcn.vgpr<?>) -> ()
  %4 = alloca : !amdgcn.vgpr<?>
  test_inst outs %4 ins %1 : (!amdgcn.vgpr<?>, !amdgcn.vgpr<?>) -> ()
  %6 = alloca : !amdgcn.vgpr<?>
  test_inst outs %6 ins %4 : (!amdgcn.vgpr<?>, !amdgcn.vgpr<?>) -> ()
  %8 = make_register_range %0, %1 : !amdgcn.vgpr<?>, !amdgcn.vgpr<?>
  test_inst ins %8, %4 : (!amdgcn.vgpr<[? : ? + 2]>, !amdgcn.vgpr<?>) -> ()
  end_kernel
}
}

// -----
// CHECK-LABEL:  SSA map:
// CHECK:  Operation: `%{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>`
// CHECK:    results: [0 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>`
// CHECK:    results: [1 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>`
// CHECK:    results: [2 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>`
// CHECK:    results: [3 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.make_register_range %{{.*}}, %{{.*}} : !amdgcn.vgpr<?>, !amdgcn.vgpr<?>`
// CHECK:    results: [4 = `%{{.*}}`]
// CHECK:  Op: module {...}
// CHECK:    LIVE BEFORE: []
// CHECK:  Symbol: test_make_range_liveness_2
// CHECK:  Op: amdgcn.kernel @test_make_range_liveness_2 {...}
// CHECK:    LIVE BEFORE: []
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:    LIVE BEFORE: []
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:    LIVE BEFORE: []
// CHECK:  Op: amdgcn.test_inst outs %{{.*}} : (!amdgcn.vgpr<?>) -> ()
// CHECK:    LIVE BEFORE: []
// CHECK:  Op: amdgcn.test_inst outs %{{.*}} : (!amdgcn.vgpr<?>) -> ()
// CHECK:    LIVE BEFORE: [0 = `%{{.*}}`]
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:    LIVE BEFORE: [0 = `%{{.*}}`, 1 = `%{{.*}}`]
// CHECK:  Op: amdgcn.test_inst outs %{{.*}} ins %{{.*}} : (!amdgcn.vgpr<?>, !amdgcn.vgpr<?>) -> ()
// CHECK:    LIVE BEFORE: [0 = `%{{.*}}`, 1 = `%{{.*}}`]
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:    LIVE BEFORE: [0 = `%{{.*}}`, 1 = `%{{.*}}`, 2 = `%{{.*}}`]
// CHECK:  Op: amdgcn.test_inst outs %{{.*}} ins %{{.*}} : (!amdgcn.vgpr<?>, !amdgcn.vgpr<?>) -> ()
// CHECK:    LIVE BEFORE: [0 = `%{{.*}}`, 1 = `%{{.*}}`, 2 = `%{{.*}}`]
// CHECK:  Op: amdgcn.test_inst ins %{{.*}} : (!amdgcn.vgpr<?>) -> ()
// CHECK:    LIVE BEFORE: [0 = `%{{.*}}`, 1 = `%{{.*}}`, 2 = `%{{.*}}`]
// CHECK:  Op: %{{.*}} = amdgcn.make_register_range %{{.*}}, %{{.*}} : !amdgcn.vgpr<?>, !amdgcn.vgpr<?>
// CHECK:    LIVE BEFORE: [0 = `%{{.*}}`, 1 = `%{{.*}}`]
// CHECK:  Op: amdgcn.test_inst ins %{{.*}} : (!amdgcn.vgpr<[? : ? + 2]>) -> ()
// CHECK:    LIVE BEFORE: [0 = `%{{.*}}`, 1 = `%{{.*}}`]
// CHECK:  Op: amdgcn.end_kernel
// CHECK:    LIVE BEFORE: []
amdgcn.module @test_make_range_liveness_2_mod target = <gfx942> {
amdgcn.kernel @test_make_range_liveness_2 {
  %0 = alloca : !amdgcn.vgpr<?>
  %1 = alloca : !amdgcn.vgpr<?>
  test_inst outs %0 : (!amdgcn.vgpr<?>) -> ()
  test_inst outs %1 : (!amdgcn.vgpr<?>) -> ()
  %4 = alloca : !amdgcn.vgpr<?>
  test_inst outs %4 ins %1 : (!amdgcn.vgpr<?>, !amdgcn.vgpr<?>) -> ()
  %6 = alloca : !amdgcn.vgpr<?>
  test_inst outs %6 ins %4 : (!amdgcn.vgpr<?>, !amdgcn.vgpr<?>) -> ()
  test_inst ins %4 : (!amdgcn.vgpr<?>) -> ()
  %8 = make_register_range %0, %1 : !amdgcn.vgpr<?>, !amdgcn.vgpr<?>
  test_inst ins %8 : (!amdgcn.vgpr<[? : ? + 2]>) -> ()
  end_kernel
}
}

// -----
// CHECK-LABEL:  SSA map:
// CHECK:  Operation: `%{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>`
// CHECK:    results: [0 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>`
// CHECK:    results: [1 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>`
// CHECK:    results: [2 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>`
// CHECK:    results: [3 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.make_register_range %{{.*}}, %{{.*}} : !amdgcn.vgpr<?>, !amdgcn.vgpr<?>`
// CHECK:    results: [4 = `%{{.*}}`]
// CHECK:  Op: module {...}
// CHECK:    LIVE BEFORE: []
// CHECK:  Symbol: test_make_range_liveness_3
// CHECK:  Op: amdgcn.kernel @test_make_range_liveness_3 {...}
// CHECK:    LIVE BEFORE: []
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:    LIVE BEFORE: []
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:    LIVE BEFORE: []
// CHECK:  Op: amdgcn.test_inst outs %{{.*}} : (!amdgcn.vgpr<?>) -> ()
// CHECK:    LIVE BEFORE: []
// CHECK:  Op: amdgcn.test_inst outs %{{.*}} : (!amdgcn.vgpr<?>) -> ()
// CHECK:    LIVE BEFORE: [0 = `%{{.*}}`]
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:    LIVE BEFORE: [0 = `%{{.*}}`, 1 = `%{{.*}}`]
// CHECK:  Op: amdgcn.test_inst outs %{{.*}} ins %{{.*}} : (!amdgcn.vgpr<?>, !amdgcn.vgpr<?>) -> ()
// CHECK:    LIVE BEFORE: [0 = `%{{.*}}`, 1 = `%{{.*}}`]
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:    LIVE BEFORE: [0 = `%{{.*}}`, 1 = `%{{.*}}`, 2 = `%{{.*}}`]
// CHECK:  Op: amdgcn.test_inst outs %{{.*}} ins %{{.*}} : (!amdgcn.vgpr<?>, !amdgcn.vgpr<?>) -> ()
// CHECK:    LIVE BEFORE: [0 = `%{{.*}}`, 1 = `%{{.*}}`, 2 = `%{{.*}}`]
// CHECK:  Op: %{{.*}} = amdgcn.make_register_range %{{.*}}, %{{.*}} : !amdgcn.vgpr<?>, !amdgcn.vgpr<?>
// CHECK:    LIVE BEFORE: [0 = `%{{.*}}`, 1 = `%{{.*}}`, 2 = `%{{.*}}`]
// CHECK:  Op: amdgcn.test_inst ins %{{.*}} : (!amdgcn.vgpr<[? : ? + 2]>) -> ()
// CHECK:    LIVE BEFORE: [0 = `%{{.*}}`, 1 = `%{{.*}}`, 2 = `%{{.*}}`]
// CHECK:  Op: amdgcn.test_inst ins %{{.*}} : (!amdgcn.vgpr<?>) -> ()
// CHECK:    LIVE BEFORE: [2 = `%{{.*}}`]
// CHECK:  Op: amdgcn.end_kernel
// CHECK:    LIVE BEFORE: []
amdgcn.module @test_make_range_liveness_3_mod target = <gfx942> {
amdgcn.kernel @test_make_range_liveness_3 {
  %0 = alloca : !amdgcn.vgpr<?>
  %1 = alloca : !amdgcn.vgpr<?>
  test_inst outs %0 : (!amdgcn.vgpr<?>) -> ()
  test_inst outs %1 : (!amdgcn.vgpr<?>) -> ()
  %4 = alloca : !amdgcn.vgpr<?>
  test_inst outs %4 ins %1 : (!amdgcn.vgpr<?>, !amdgcn.vgpr<?>) -> ()
  %6 = alloca : !amdgcn.vgpr<?>
  test_inst outs %6 ins %4 : (!amdgcn.vgpr<?>, !amdgcn.vgpr<?>) -> ()
  %8 = make_register_range %0, %1 : !amdgcn.vgpr<?>, !amdgcn.vgpr<?>
  test_inst ins %8 : (!amdgcn.vgpr<[? : ? + 2]>) -> ()
  test_inst ins %4 : (!amdgcn.vgpr<?>) -> ()
  end_kernel
}
}

// -----
// CHECK-LABEL:  SSA map:
// CHECK:  Operation: `%{{.*}} = amdgcn.alloca : !amdgcn.sgpr<?>`
// CHECK:    results: [0 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.alloca : !amdgcn.sgpr<?>`
// CHECK:    results: [1 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.alloca : !amdgcn.sgpr<?>`
// CHECK:    results: [2 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.alloca : !amdgcn.sgpr<?>`
// CHECK:    results: [3 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.alloca : !amdgcn.sgpr<?>`
// CHECK:    results: [4 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.alloca : !amdgcn.sgpr<?>`
// CHECK:    results: [5 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.alloca : !amdgcn.sgpr<?>`
// CHECK:    results: [6 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.alloca : !amdgcn.sgpr<?>`
// CHECK:    results: [7 = `%{{.*}}`]
// CHECK:  Op: module {...}
// CHECK:    LIVE BEFORE: []
// CHECK:  Symbol: reg_interference
// CHECK:  Op: amdgcn.kernel @reg_interference {...}
// CHECK:    LIVE BEFORE: []
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.sgpr<?>
// CHECK:    LIVE BEFORE: []
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.sgpr<?>
// CHECK:    LIVE BEFORE: [0 = `%{{.*}}`]
// CHECK:  Op: amdgcn.test_inst ins %{{.*}}, %{{.*}} : (!amdgcn.sgpr<?>, !amdgcn.sgpr<?>) -> ()
// CHECK:    LIVE BEFORE: [0 = `%{{.*}}`, 1 = `%{{.*}}`]
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.sgpr<?>
// CHECK:    LIVE BEFORE: []
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.sgpr<?>
// CHECK:    LIVE BEFORE: [2 = `%{{.*}}`]
// CHECK:  Op: amdgcn.test_inst ins %{{.*}}, %{{.*}} : (!amdgcn.sgpr<?>, !amdgcn.sgpr<?>) -> ()
// CHECK:    LIVE BEFORE: [2 = `%{{.*}}`, 3 = `%{{.*}}`]
// CHECK:  Op: amdgcn.reg_interference %{{.*}}, %{{.*}}, %{{.*}} : !amdgcn.sgpr<?>, !amdgcn.sgpr<?>, !amdgcn.sgpr<?>
// CHECK:    LIVE BEFORE: []
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.sgpr<?>
// CHECK:    LIVE BEFORE: []
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.sgpr<?>
// CHECK:    LIVE BEFORE: [4 = `%{{.*}}`]
// CHECK:  Op: amdgcn.test_inst ins %{{.*}}, %{{.*}} : (!amdgcn.sgpr<?>, !amdgcn.sgpr<?>) -> ()
// CHECK:    LIVE BEFORE: [4 = `%{{.*}}`, 5 = `%{{.*}}`]
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.sgpr<?>
// CHECK:    LIVE BEFORE: []
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.sgpr<?>
// CHECK:    LIVE BEFORE: [6 = `%{{.*}}`]
// CHECK:  Op: amdgcn.test_inst ins %{{.*}}, %{{.*}} : (!amdgcn.sgpr<?>, !amdgcn.sgpr<?>) -> ()
// CHECK:    LIVE BEFORE: [6 = `%{{.*}}`, 7 = `%{{.*}}`]
// CHECK:  Op: amdgcn.reg_interference %{{.*}}, %{{.*}}, %{{.*}}, %{{.*}} : !amdgcn.sgpr<?>, !amdgcn.sgpr<?>, !amdgcn.sgpr<?>, !amdgcn.sgpr<?>
// CHECK:    LIVE BEFORE: []
// CHECK:  Op: amdgcn.end_kernel
// CHECK:    LIVE BEFORE: []
amdgcn.module @reg_interference_mod target = <gfx942> {
amdgcn.kernel @reg_interference {
  %0 = alloca : !amdgcn.sgpr<?>
  %1 = alloca : !amdgcn.sgpr<?>
  test_inst ins %0, %1 : (!amdgcn.sgpr<?>, !amdgcn.sgpr<?>) -> ()
  %2 = alloca : !amdgcn.sgpr<?>
  %3 = alloca : !amdgcn.sgpr<?>
  test_inst ins %2, %3 : (!amdgcn.sgpr<?>, !amdgcn.sgpr<?>) -> ()
  reg_interference %0, %2, %3 : !amdgcn.sgpr<?>, !amdgcn.sgpr<?>, !amdgcn.sgpr<?>
  %4 = alloca : !amdgcn.sgpr<?>
  %5 = alloca : !amdgcn.sgpr<?>
  test_inst ins %4, %5 : (!amdgcn.sgpr<?>, !amdgcn.sgpr<?>) -> ()
  %6 = alloca : !amdgcn.sgpr<?>
  %7 = alloca : !amdgcn.sgpr<?>
  test_inst ins %6, %7 : (!amdgcn.sgpr<?>, !amdgcn.sgpr<?>) -> ()
  reg_interference %4, %1, %3, %7 : !amdgcn.sgpr<?>, !amdgcn.sgpr<?>, !amdgcn.sgpr<?>, !amdgcn.sgpr<?>
  end_kernel
}
}

// -----
// CHECK-LABEL:  SSA map:
// CHECK:  Operation: `%{{.*}} = arith.constant 0 : i32`
// CHECK:    results: [0 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>`
// CHECK:    results: [1 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>`
// CHECK:    results: [2 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.alloca : !amdgcn.sgpr<?>`
// CHECK:    results: [3 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.alloca : !amdgcn.sgpr<?>`
// CHECK:    results: [4 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>`
// CHECK:    results: [5 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>`
// CHECK:    results: [6 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = lsir.alloca : !amdgcn.scc`
// CHECK:    results: [7 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = lsir.cmpi i32 eq %{{.*}}, %{{.*}}, %{{.*}} : !amdgcn.scc, !amdgcn.sgpr<?>, i32`
// CHECK:    results: [8 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>`
// CHECK:    results: [9 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>`
// CHECK:    results: [10 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>`
// CHECK:    results: [11 = `%{{.*}}`]
// CHECK:  Op: module {...}
// CHECK:    LIVE BEFORE: []
// CHECK:  Symbol: phi_coalescing_2
// CHECK:  Op: amdgcn.kernel @phi_coalescing_2 {...}
// CHECK:    LIVE BEFORE: []
// CHECK:  Op: %{{.*}} = arith.constant 0 : i32
// CHECK:    LIVE BEFORE: []
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:    LIVE BEFORE: []
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:    LIVE BEFORE: []
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.sgpr<?>
// CHECK:    LIVE BEFORE: []
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.sgpr<?>
// CHECK:    LIVE BEFORE: [3 = `%{{.*}}`]
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:    LIVE BEFORE: [3 = `%{{.*}}`, 4 = `%{{.*}}`]
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:    LIVE BEFORE: [3 = `%{{.*}}`, 4 = `%{{.*}}`]
// CHECK:  Op: amdgcn.test_inst outs %{{.*}} ins %{{.*}} : (!amdgcn.vgpr<?>, !amdgcn.sgpr<?>) -> ()
// CHECK:    LIVE BEFORE: [3 = `%{{.*}}`, 4 = `%{{.*}}`]
// CHECK:  Op: amdgcn.test_inst outs %{{.*}} ins %{{.*}} : (!amdgcn.vgpr<?>, !amdgcn.sgpr<?>) -> ()
// CHECK:    LIVE BEFORE: [1 = `%{{.*}}`, 3 = `%{{.*}}`, 4 = `%{{.*}}`]
// CHECK:  Op: %{{.*}} = lsir.alloca : !amdgcn.scc
// CHECK:    LIVE BEFORE: [1 = `%{{.*}}`, 2 = `%{{.*}}`, 3 = `%{{.*}}`]
// CHECK:  Op: %{{.*}} = lsir.cmpi i32 eq %{{.*}}, %{{.*}}, %{{.*}} : !amdgcn.scc, !amdgcn.sgpr<?>, i32
// CHECK:    LIVE BEFORE: [1 = `%{{.*}}`, 2 = `%{{.*}}`, 3 = `%{{.*}}`]
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:    LIVE BEFORE: [1 = `%{{.*}}`, 2 = `%{{.*}}`, 8 = `%{{.*}}`]
// CHECK:  Op: lsir.cond_br %{{.*}} : !amdgcn.scc, ^bb1, ^bb2
// CHECK:    LIVE BEFORE: [1 = `%{{.*}}`, 2 = `%{{.*}}`, 8 = `%{{.*}}`]
// CHECK:  Op: amdgcn.test_inst outs %{{.*}} ins %{{.*}} : (!amdgcn.vgpr<?>, !amdgcn.vgpr<?>) -> ()
// CHECK:    LIVE BEFORE: [1 = `%{{.*}}`]
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:    LIVE BEFORE: []
// CHECK:  Op: amdgcn.test_inst outs %{{.*}} : (!amdgcn.vgpr<?>) -> ()
// CHECK:    LIVE BEFORE: []
// CHECK:  Op: lsir.copy %{{.*}}, %{{.*}} : !amdgcn.vgpr<?>, !amdgcn.vgpr<?>
// CHECK:    LIVE BEFORE: [10 = `%{{.*}}`]
// CHECK:  Op: cf.br ^bb3
// CHECK:    LIVE BEFORE: [9 = `%{{.*}}`]
// CHECK:  Op: amdgcn.test_inst outs %{{.*}} ins %{{.*}} : (!amdgcn.vgpr<?>, !amdgcn.vgpr<?>) -> ()
// CHECK:    LIVE BEFORE: [2 = `%{{.*}}`]
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:    LIVE BEFORE: []
// CHECK:  Op: amdgcn.test_inst outs %{{.*}} : (!amdgcn.vgpr<?>) -> ()
// CHECK:    LIVE BEFORE: []
// CHECK:  Op: lsir.copy %{{.*}}, %{{.*}} : !amdgcn.vgpr<?>, !amdgcn.vgpr<?>
// CHECK:    LIVE BEFORE: [11 = `%{{.*}}`]
// CHECK:  Op: cf.br ^bb3
// CHECK:    LIVE BEFORE: [9 = `%{{.*}}`]
// CHECK:  Op: amdgcn.test_inst ins %{{.*}} : (!amdgcn.vgpr<?>) -> ()
// CHECK:    LIVE BEFORE: [9 = `%{{.*}}`]
// CHECK:  Op: amdgcn.end_kernel
// CHECK:    LIVE BEFORE: []
amdgcn.module @phi_coalescing_2_mod target = <gfx942> {
amdgcn.kernel @phi_coalescing_2 {
  %c0_i32 = arith.constant 0 : i32
  %0 = alloca : !amdgcn.vgpr<?>
  %1 = alloca : !amdgcn.vgpr<?>
  %2 = alloca : !amdgcn.sgpr<?>
  %3 = alloca : !amdgcn.sgpr<?>
  %4 = alloca : !amdgcn.vgpr<?>
  %5 = alloca : !amdgcn.vgpr<?>
  test_inst outs %0 ins %2 : (!amdgcn.vgpr<?>, !amdgcn.sgpr<?>) -> ()
  test_inst outs %1 ins %3 : (!amdgcn.vgpr<?>, !amdgcn.sgpr<?>) -> ()
  %scc8 = lsir.alloca : !amdgcn.scc
  %8 = lsir.cmpi i32 eq %scc8, %2, %c0_i32 : !amdgcn.scc, !amdgcn.sgpr<?>, i32
  %9 = alloca : !amdgcn.vgpr<?>
  lsir.cond_br %8 : !amdgcn.scc, ^bb1, ^bb2
^bb1:  // CHECK: pred: ^bb0
  test_inst outs %4 ins %0 : (!amdgcn.vgpr<?>, !amdgcn.vgpr<?>) -> ()
  %11 = alloca : !amdgcn.vgpr<?>
  test_inst outs %11 : (!amdgcn.vgpr<?>) -> ()
  lsir.copy %9, %11 : !amdgcn.vgpr<?>, !amdgcn.vgpr<?>
  cf.br ^bb3
^bb2:  // CHECK: pred: ^bb0
  test_inst outs %5 ins %1 : (!amdgcn.vgpr<?>, !amdgcn.vgpr<?>) -> ()
  %15 = alloca : !amdgcn.vgpr<?>
  test_inst outs %15 : (!amdgcn.vgpr<?>) -> ()
  lsir.copy %9, %15 : !amdgcn.vgpr<?>, !amdgcn.vgpr<?>
  cf.br ^bb3
^bb3:  // CHECK: 2 preds: ^bb1, ^bb2
  test_inst ins %9 : (!amdgcn.vgpr<?>) -> ()
  end_kernel
}
}

// -----
// CHECK-LABEL:  SSA map:
// CHECK:  Operation: `%{{.*}} = arith.constant 0 : i32`
// CHECK:    results: [0 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>`
// CHECK:    results: [1 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>`
// CHECK:    results: [2 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.alloca : !amdgcn.sgpr<?>`
// CHECK:    results: [3 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.alloca : !amdgcn.sgpr<?>`
// CHECK:    results: [4 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = lsir.alloca : !amdgcn.scc`
// CHECK:    results: [5 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = lsir.cmpi i32 eq %{{.*}}, %{{.*}}, %{{.*}} : !amdgcn.scc, !amdgcn.sgpr<?>, i32`
// CHECK:    results: [6 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>`
// CHECK:    results: [7 = `%{{.*}}`]
// CHECK:  Op: module {...}
// CHECK:    LIVE BEFORE: []
// CHECK:  Symbol: phi_coalescing_3
// CHECK:  Op: amdgcn.kernel @phi_coalescing_3 {...}
// CHECK:    LIVE BEFORE: []
// CHECK:  Op: %{{.*}} = arith.constant 0 : i32
// CHECK:    LIVE BEFORE: []
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:    LIVE BEFORE: []
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:    LIVE BEFORE: []
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.sgpr<?>
// CHECK:    LIVE BEFORE: []
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.sgpr<?>
// CHECK:    LIVE BEFORE: [3 = `%{{.*}}`]
// CHECK:  Op: amdgcn.test_inst outs %{{.*}} ins %{{.*}} : (!amdgcn.vgpr<?>, !amdgcn.sgpr<?>) -> ()
// CHECK:    LIVE BEFORE: [3 = `%{{.*}}`, 4 = `%{{.*}}`]
// CHECK:  Op: amdgcn.test_inst outs %{{.*}} ins %{{.*}} : (!amdgcn.vgpr<?>, !amdgcn.sgpr<?>) -> ()
// CHECK:    LIVE BEFORE: [1 = `%{{.*}}`, 3 = `%{{.*}}`, 4 = `%{{.*}}`]
// CHECK:  Op: %{{.*}} = lsir.alloca : !amdgcn.scc
// CHECK:    LIVE BEFORE: [1 = `%{{.*}}`, 2 = `%{{.*}}`, 3 = `%{{.*}}`]
// CHECK:  Op: %{{.*}} = lsir.cmpi i32 eq %{{.*}}, %{{.*}}, %{{.*}} : !amdgcn.scc, !amdgcn.sgpr<?>, i32
// CHECK:    LIVE BEFORE: [1 = `%{{.*}}`, 2 = `%{{.*}}`, 3 = `%{{.*}}`]
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:    LIVE BEFORE: [1 = `%{{.*}}`, 2 = `%{{.*}}`, 6 = `%{{.*}}`]
// CHECK:  Op: lsir.cond_br %{{.*}} : !amdgcn.scc, ^bb1, ^bb2
// CHECK:    LIVE BEFORE: [1 = `%{{.*}}`, 2 = `%{{.*}}`, 6 = `%{{.*}}`]
// CHECK:  Op: lsir.copy %{{.*}}, %{{.*}} : !amdgcn.vgpr<?>, !amdgcn.vgpr<?>
// CHECK:    LIVE BEFORE: [1 = `%{{.*}}`, 2 = `%{{.*}}`]
// CHECK:  Op: cf.br ^bb3
// CHECK:    LIVE BEFORE: [1 = `%{{.*}}`, 2 = `%{{.*}}`, 7 = `%{{.*}}`]
// CHECK:  Op: lsir.copy %{{.*}}, %{{.*}} : !amdgcn.vgpr<?>, !amdgcn.vgpr<?>
// CHECK:    LIVE BEFORE: [1 = `%{{.*}}`, 2 = `%{{.*}}`]
// CHECK:  Op: cf.br ^bb3
// CHECK:    LIVE BEFORE: [1 = `%{{.*}}`, 2 = `%{{.*}}`, 7 = `%{{.*}}`]
// CHECK:  Op: amdgcn.test_inst ins %{{.*}}, %{{.*}}, %{{.*}} : (!amdgcn.vgpr<?>, !amdgcn.vgpr<?>, !amdgcn.vgpr<?>) -> ()
// CHECK:    LIVE BEFORE: [1 = `%{{.*}}`, 2 = `%{{.*}}`, 7 = `%{{.*}}`]
// CHECK:  Op: amdgcn.end_kernel
// CHECK:    LIVE BEFORE: []
amdgcn.module @phi_coalescing_3_mod target = <gfx942> {
amdgcn.kernel @phi_coalescing_3 {
  %c0_i32 = arith.constant 0 : i32
  %0 = alloca : !amdgcn.vgpr<?>
  %1 = alloca : !amdgcn.vgpr<?>
  %2 = alloca : !amdgcn.sgpr<?>
  %3 = alloca : !amdgcn.sgpr<?>
  test_inst outs %0 ins %2 : (!amdgcn.vgpr<?>, !amdgcn.sgpr<?>) -> ()
  test_inst outs %1 ins %3 : (!amdgcn.vgpr<?>, !amdgcn.sgpr<?>) -> ()
  %scc6 = lsir.alloca : !amdgcn.scc
  %6 = lsir.cmpi i32 eq %scc6, %2, %c0_i32 : !amdgcn.scc, !amdgcn.sgpr<?>, i32
  %7 = alloca : !amdgcn.vgpr<?>
  lsir.cond_br %6 : !amdgcn.scc, ^bb1, ^bb2
^bb1:  // CHECK: pred: ^bb0
  lsir.copy %7, %0 : !amdgcn.vgpr<?>, !amdgcn.vgpr<?>
  cf.br ^bb3
^bb2:  // CHECK: pred: ^bb0
  lsir.copy %7, %1 : !amdgcn.vgpr<?>, !amdgcn.vgpr<?>
  cf.br ^bb3
^bb3:  // CHECK: 2 preds: ^bb1, ^bb2
  test_inst ins %7, %0, %1 : (!amdgcn.vgpr<?>, !amdgcn.vgpr<?>, !amdgcn.vgpr<?>) -> ()
  end_kernel
}
}

// -----

// CHECK-LABEL:  SSA map:
// CHECK-NOT: LIVE BEFORE: [{{.+}}]
// CHECK-NOT: LIVE  AFTER: [{{.+}}]
func.func @test_no_live_values(%0: !amdgcn.vgpr) {
  amdgcn.test_inst outs %0 : (!amdgcn.vgpr) -> (!amdgcn.vgpr)
  return
}

func.func @test_no_live_values_make_register_range(%0: !amdgcn.vgpr, %1: !amdgcn.vgpr) {
  %2 = amdgcn.make_register_range %0, %1 : !amdgcn.vgpr, !amdgcn.vgpr
  amdgcn.test_inst outs %2 : (!amdgcn.vgpr<[? + 2]>) -> (!amdgcn.vgpr<[? + 2]>)
  return
}

func.func @test_no_live_values_split_register_range(%0: !amdgcn.vgpr<[? + 2]>) {
  %1, %2 = amdgcn.split_register_range %0 : !amdgcn.vgpr<[? + 2]>
  amdgcn.test_inst outs %1, %2 : (!amdgcn.vgpr, !amdgcn.vgpr) -> (!amdgcn.vgpr, !amdgcn.vgpr)
  return
}

// -----
// CHECK-LABEL: Symbol: test_live_values_split_register_range
// CHECK:  Op: %{{.*}} = amdgcn.split_register_range %{{.*}} : !amdgcn.vgpr<[? + 2]>
// CHECK:    LIVE BEFORE: [0 = `%{{.*}}`]
// CHECK:    LIVE  AFTER: [1 = `%{{.*}}`, 2 = `%{{.*}}`]
// CHECK:  Op: amdgcn.test_inst ins %{{.*}}, %{{.*}} : (!amdgcn.vgpr, !amdgcn.vgpr) -> ()
// CHECK:    LIVE BEFORE: [1 = `%{{.*}}`, 2 = `%{{.*}}`]
// CHECK:    LIVE  AFTER: []
// CHECK:  Op: func.return
// CHECK:    LIVE BEFORE: []
// CHECK:    LIVE  AFTER: []
func.func @test_live_values_split_register_range(%0: !amdgcn.vgpr<[? + 2]>) {
  %1, %2 = amdgcn.split_register_range %0 : !amdgcn.vgpr<[? + 2]>
  amdgcn.test_inst ins %1, %2 : (!amdgcn.vgpr, !amdgcn.vgpr) -> ()
  return
}

// CHECK-LABEL: Symbol: test_live_values_make_register_range
// CHECK:  Op: %{{.*}} = amdgcn.make_register_range %{{.*}}, %{{.*}} : !amdgcn.vgpr, !amdgcn.vgpr
// CHECK:    LIVE BEFORE: [3 = `%{{.*}}`, 4 = `%{{.*}}`]
// CHECK:    LIVE  AFTER: [5 = `%{{.*}}`]
// CHECK:  Op: amdgcn.test_inst ins %{{.*}} : (!amdgcn.vgpr<[? + 2]>) -> ()
// CHECK:    LIVE BEFORE: [5 = `%{{.*}}`]
// CHECK:    LIVE  AFTER: []
// CHECK:  Op: func.return
// CHECK:    LIVE BEFORE: []
// CHECK:    LIVE  AFTER: []
func.func @test_live_values_make_register_range(%0: !amdgcn.vgpr, %1: !amdgcn.vgpr) {
  %2 = amdgcn.make_register_range %0, %1 : !amdgcn.vgpr, !amdgcn.vgpr
  amdgcn.test_inst ins %2 : (!amdgcn.vgpr<[? + 2]>) -> ()
  return
}

// CHECK-LABEL: Symbol: test_mixed
// CHECK:  Op: %{{.*}} = amdgcn.make_register_range %{{.*}}, %{{.*}} : !amdgcn.vgpr, !amdgcn.vgpr
// CHECK:    LIVE BEFORE: [6 = `%{{.*}}`, 7 = `%{{.*}}`]
// CHECK:    LIVE  AFTER: [8 = `%{{.*}}`]
// CHECK:  Op: %{{.*}} = amdgcn.test_inst outs %{{.*}} ins %{{.*}} : (!amdgcn.vgpr<[? + 2]>, !amdgcn.vgpr<[? + 2]>) -> !amdgcn.vgpr<[? + 2]>
// CHECK:    LIVE BEFORE: [8 = `%{{.*}}`]
// CHECK:    LIVE  AFTER: []
// CHECK:  Op: func.return
// CHECK:    LIVE BEFORE: []
// CHECK:    LIVE  AFTER: []
func.func @test_mixed(%0: !amdgcn.vgpr, %1: !amdgcn.vgpr) {
  %2 = amdgcn.make_register_range %0, %1 : !amdgcn.vgpr, !amdgcn.vgpr
  amdgcn.test_inst outs %2 ins %2 : (!amdgcn.vgpr<[? + 2]>, !amdgcn.vgpr<[? + 2]>) -> (!amdgcn.vgpr<[? + 2]>)
  return
}

// -----
// Test: Empty kernel - no register operations, only end_kernel.
// CHECK-LABEL:  SSA map:
// CHECK:  Op: module {...}
// CHECK:    LIVE BEFORE: []
// CHECK:  Symbol: test_empty_kernel
// CHECK:  Op: amdgcn.kernel @test_empty_kernel {...}
// CHECK:    LIVE BEFORE: []
// CHECK:  Op: amdgcn.end_kernel
// CHECK:    LIVE BEFORE: []
amdgcn.module @test_empty_kernel_mod target = <gfx942> {
amdgcn.kernel @test_empty_kernel {
  end_kernel
}
}

// -----
// Test: Non-register values (i32, i1) are filtered from liveness - only
// RegisterType values appear in the live set.
// CHECK-LABEL:  SSA map:
// CHECK:  Op: module {...}
// CHECK:    LIVE BEFORE: []
// CHECK:  Symbol: test_non_register_filtered
// CHECK:  Op: amdgcn.kernel @test_non_register_filtered {...}
// CHECK:    LIVE BEFORE: []
// CHECK:  Op: %{{.*}} = arith.constant 0 : i32
// CHECK:    LIVE BEFORE: []
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.sgpr<?>
// CHECK:    LIVE BEFORE: []
// CHECK:  Op: %{{.*}} = lsir.alloca : !amdgcn.scc
// CHECK:    LIVE BEFORE: [1 = `%{{.*}}`]
// CHECK:  Op: %{{.*}} = lsir.cmpi i32 eq %{{.*}}, %{{.*}}, %{{.*}} : !amdgcn.scc, !amdgcn.sgpr<?>, i32
// CHECK:    LIVE BEFORE: [1 = `%{{.*}}`]
// CHECK:  Op: lsir.cond_br %{{.*}} : !amdgcn.scc, ^bb1, ^bb2
// CHECK:    LIVE BEFORE: [3 = `%{{.*}}`]
amdgcn.module @test_non_register_filtered_mod target = <gfx942> {
amdgcn.kernel @test_non_register_filtered {
  %c0 = arith.constant 0 : i32
  %0 = alloca : !amdgcn.sgpr<?>
  %scc_dst = lsir.alloca : !amdgcn.scc
  %cond = lsir.cmpi i32 eq %scc_dst, %0, %c0 : !amdgcn.scc, !amdgcn.sgpr<?>, i32
  lsir.cond_br %cond : !amdgcn.scc, ^bb1, ^bb2
^bb1:
  end_kernel
^bb2:
  end_kernel
}
}

// -----
// Test: Long def-use chain - verify backward liveness propagates correctly
// through many operations.
// CHECK-LABEL:  SSA map:
// CHECK:  Op: module {...}
// CHECK:    LIVE BEFORE: []
// CHECK:  Symbol: test_long_chain
// CHECK:  Op: amdgcn.kernel @test_long_chain {...}
// CHECK:    LIVE BEFORE: []
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:    LIVE BEFORE: []
// CHECK:  Op: amdgcn.test_inst outs %{{.*}} ins %{{.*}} : (!amdgcn.vgpr<?>, !amdgcn.vgpr<?>) -> ()
// CHECK:    LIVE BEFORE: [0 = `%{{.*}}`]
// CHECK:  Op: amdgcn.test_inst outs %{{.*}} ins %{{.*}} : (!amdgcn.vgpr<?>, !amdgcn.vgpr<?>) -> ()
// CHECK:    LIVE BEFORE: [0 = `%{{.*}}`, 1 = `%{{.*}}`]
// CHECK:  Op: amdgcn.test_inst outs %{{.*}} ins %{{.*}} : (!amdgcn.vgpr<?>, !amdgcn.vgpr<?>) -> ()
// CHECK:    LIVE BEFORE: [0 = `%{{.*}}`, 1 = `%{{.*}}`, 2 = `%{{.*}}`]
// CHECK:  Op: amdgcn.test_inst ins %{{.*}}, %{{.*}}, %{{.*}}, %{{.*}} :
// CHECK:    LIVE BEFORE: [0 = `%{{.*}}`, 1 = `%{{.*}}`, 2 = `%{{.*}}`, 3 = `%{{.*}}`]
amdgcn.module @test_long_chain_mod target = <gfx942> {
amdgcn.kernel @test_long_chain {
  %0 = alloca : !amdgcn.vgpr<?>
  %1 = alloca : !amdgcn.vgpr<?>
  %2 = alloca : !amdgcn.vgpr<?>
  %3 = alloca : !amdgcn.vgpr<?>
  test_inst outs %1 ins %0 : (!amdgcn.vgpr<?>, !amdgcn.vgpr<?>) -> ()
  test_inst outs %2 ins %1 : (!amdgcn.vgpr<?>, !amdgcn.vgpr<?>) -> ()
  test_inst outs %3 ins %2 : (!amdgcn.vgpr<?>, !amdgcn.vgpr<?>) -> ()
  test_inst ins %0, %1, %2, %3 : (!amdgcn.vgpr<?>, !amdgcn.vgpr<?>, !amdgcn.vgpr<?>, !amdgcn.vgpr<?>) -> ()
  end_kernel
}
}

// -----
// Test: Triple branch merge - three predecessors merging into one block.
// Verifies that liveness correctly unions live values from all predecessors.
// CHECK-LABEL:  SSA map:
// CHECK:  Op: module {...}
// CHECK:    LIVE BEFORE: []
// CHECK:  Symbol: rand
// CHECK:  Op: func.func private @rand() -> i1
// CHECK:    LIVE BEFORE: []
// CHECK:  Symbol: test_triple_merge
// CHECK:  Op: amdgcn.kernel @test_triple_merge {...}
// CHECK:    LIVE BEFORE: []
// CHECK:  Op: amdgcn.test_inst ins %{{.*}}, %{{.*}}, %{{.*}} : (!amdgcn.vgpr<?>, !amdgcn.vgpr<?>, !amdgcn.vgpr<?>) -> ()
// CHECK:    LIVE BEFORE: [0 = `%{{.*}}`, 1 = `%{{.*}}`, 2 = `%{{.*}}`]
amdgcn.module @test_triple_merge_mod target = <gfx942> {
func.func private @rand() -> i1
amdgcn.kernel @test_triple_merge {
  %0 = alloca : !amdgcn.vgpr<?>
  %1 = alloca : !amdgcn.vgpr<?>
  %2 = alloca : !amdgcn.vgpr<?>
  %cond = func.call @rand() : () -> i1
  cf.cond_br %cond, ^bb1, ^bb2
^bb1:
  test_inst outs %0 ins %0 : (!amdgcn.vgpr<?>, !amdgcn.vgpr<?>) -> ()
  cf.br ^bb3
^bb2:
  %cond2 = func.call @rand() : () -> i1
  cf.cond_br %cond2, ^bb3_alt, ^bb3_other
^bb3_alt:
  test_inst outs %1 ins %1 : (!amdgcn.vgpr<?>, !amdgcn.vgpr<?>) -> ()
  cf.br ^bb3
^bb3_other:
  test_inst outs %2 ins %2 : (!amdgcn.vgpr<?>, !amdgcn.vgpr<?>) -> ()
  cf.br ^bb3
^bb3:
  test_inst ins %0, %1, %2 : (!amdgcn.vgpr<?>, !amdgcn.vgpr<?>, !amdgcn.vgpr<?>) -> ()
  end_kernel
}
}

// -----

// CHECK-LABEL:  SSA map:
// CHECK:  Operation: `%{{.*}} = arith.constant 0 : index`
// CHECK:    results: [0 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = arith.constant 1 : index`
// CHECK:    results: [1 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = arith.constant 10 : index`
// CHECK:    results: [2 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.alloca : !amdgcn.vgpr`
// CHECK:    results: [3 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.alloca : !amdgcn.vgpr`
// CHECK:    results: [4 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}}:2 = scf.for %{{.*}} = %{{.*}} to %{{.*}} step %{{.*}} iter_args(%{{.*}} = %{{.*}}, %{{.*}} = %{{.*}}) -> (!amdgcn.vgpr, !amdgcn.vgpr) {...}`
// CHECK:    results: [5 = `%{{.*}}#0`, 6 = `%{{.*}}#1`]
// CHECK:  Block: Block<op = %{{.*}}:2 = scf.for %{{.*}} = %{{.*}} to %{{.*}} step %{{.*}} iter_args(%{{.*}} = %{{.*}}, %{{.*}} = %{{.*}}) -> (!amdgcn.vgpr, !amdgcn.vgpr) {...}, region = 0, bb = ^bb0, args = [%{{.*}}, %{{.*}}, %{{.*}}]>
// CHECK:    arguments: [7 = `%{{.*}}`, 8 = `%{{.*}}`, 9 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.test_inst outs %{{.*}} : (!amdgcn.vgpr) -> !amdgcn.vgpr`
// CHECK:    results: [10 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.test_inst outs %{{.*}} : (!amdgcn.vgpr) -> !amdgcn.vgpr`
// CHECK:    results: [11 = `%{{.*}}`]
// CHECK:  Op: module {...}
// CHECK:    LIVE BEFORE: []
// CHECK:    LIVE  AFTER: []
// CHECK:  Symbol: scf_value_liveness
// CHECK:  Op: func.func @scf_value_liveness() {...}
// CHECK:    LIVE BEFORE: []
// CHECK:    LIVE  AFTER: []
// CHECK:  Op: %{{.*}} = arith.constant 0 : index
// CHECK:    LIVE BEFORE: []
// CHECK:    LIVE  AFTER: []
// CHECK:  Op: %{{.*}} = arith.constant 1 : index
// CHECK:    LIVE BEFORE: []
// CHECK:    LIVE  AFTER: []
// CHECK:  Op: %{{.*}} = arith.constant 10 : index
// CHECK:    LIVE BEFORE: []
// CHECK:    LIVE  AFTER: []
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.vgpr
// CHECK:    LIVE BEFORE: []
// CHECK:    LIVE  AFTER: [3 = `%{{.*}}`]
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.vgpr
// CHECK:    LIVE BEFORE: [3 = `%{{.*}}`]
// CHECK:    LIVE  AFTER: [3 = `%{{.*}}`, 4 = `%{{.*}}`]
// CHECK:  Op: %{{.*}}:2 = scf.for %{{.*}} = %{{.*}} to %{{.*}} step %{{.*}} iter_args(%{{.*}} = %{{.*}}, %{{.*}} = %{{.*}}) -> (!amdgcn.vgpr, !amdgcn.vgpr) {...}
// CHECK:    LIVE BEFORE: [3 = `%{{.*}}`, 4 = `%{{.*}}`]
// CHECK:    LIVE  AFTER: [5 = `%{{.*}}#0`, 6 = `%{{.*}}#1`]
// CHECK:  Op: %{{.*}} = amdgcn.test_inst outs %{{.*}} : (!amdgcn.vgpr) -> !amdgcn.vgpr
// CHECK:    LIVE BEFORE: []
// CHECK:    LIVE  AFTER: [10 = `%{{.*}}`]
// CHECK:  Op: %{{.*}} = amdgcn.test_inst outs %{{.*}} : (!amdgcn.vgpr) -> !amdgcn.vgpr
// CHECK:    LIVE BEFORE: [10 = `%{{.*}}`]
// CHECK:    LIVE  AFTER: [10 = `%{{.*}}`, 11 = `%{{.*}}`]
// CHECK:  Op: scf.yield %{{.*}}, %{{.*}} : !amdgcn.vgpr, !amdgcn.vgpr
// CHECK:    LIVE BEFORE: [10 = `%{{.*}}`, 11 = `%{{.*}}`]
// CHECK:    LIVE  AFTER: [10 = `%{{.*}}`, 11 = `%{{.*}}`]
// CHECK:  Op: amdgcn.test_inst ins %{{.*}}#0, %{{.*}}#1 : (!amdgcn.vgpr, !amdgcn.vgpr) -> ()
// CHECK:    LIVE BEFORE: [5 = `%{{.*}}#0`, 6 = `%{{.*}}#1`]
// CHECK:    LIVE  AFTER: []
// CHECK:  Op: func.return
// CHECK:    LIVE BEFORE: []
// CHECK:    LIVE  AFTER: []

func.func @scf_value_liveness() {
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c10 = arith.constant 10 : index
  %0 = amdgcn.alloca : !amdgcn.vgpr
  %1 = amdgcn.alloca : !amdgcn.vgpr
  %2:2 = scf.for %arg0 = %c0 to %c10 step %c1 iter_args(%arg1 = %0, %arg2 = %1) -> (!amdgcn.vgpr, !amdgcn.vgpr) {
    %4 = amdgcn.test_inst outs %arg1 : (!amdgcn.vgpr) -> !amdgcn.vgpr
    %5 = amdgcn.test_inst outs %arg2 : (!amdgcn.vgpr) -> !amdgcn.vgpr
    scf.yield %4, %5 : !amdgcn.vgpr, !amdgcn.vgpr
  }
  amdgcn.test_inst ins %2#0, %2#1 : (!amdgcn.vgpr, !amdgcn.vgpr) -> ()
  return
}

// -----

// CHECK-LABEL:  Block: Block<op = func.func @bb_value_liveness
// CHECK-SAME:   (%{{.*}}: i1) {...}, region = 0, bb = ^bb0, args = [%{{.*}}]>
// CHECK:    arguments: [0 = `%{{.*}}`]
// CHECK:  Block: Block<op = func.func @bb_value_liveness(%{{.*}}: i1) {...}, region = 0, bb = ^bb1, args = [%{{.*}}, %{{.*}}]>
// CHECK:    arguments: [1 = `%{{.*}}`, 2 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.alloca : !amdgcn.vgpr`
// CHECK:    results: [3 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.alloca : !amdgcn.vgpr`
// CHECK:    results: [4 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.make_register_range %{{.*}}, %{{.*}} : !amdgcn.vgpr, !amdgcn.vgpr`
// CHECK:    results: [5 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.test_inst outs %{{.*}} : (!amdgcn.vgpr<[? + 2]>) -> !amdgcn.vgpr<[? + 2]>`
// CHECK:    results: [6 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.test_inst outs %{{.*}} : (!amdgcn.vgpr<[? + 2]>) -> !amdgcn.vgpr<[? + 2]>`
// CHECK:    results: [7 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}} = amdgcn.test_inst outs %{{.*}} ins %{{.*}} : (!amdgcn.vgpr<[? + 2]>, !amdgcn.vgpr<[? + 2]>) -> !amdgcn.vgpr<[? + 2]>`
// CHECK:    results: [8 = `%{{.*}}`]
// CHECK:  Operation: `%{{.*}}:2 = amdgcn.test_inst outs %{{.*}}, %{{.*}} ins %{{.*}}, %{{.*}} : (!amdgcn.vgpr<[? + 2]>, !amdgcn.vgpr<[? + 2]>, !amdgcn.vgpr<[? + 2]>, !amdgcn.vgpr<[? + 2]>) -> (!amdgcn.vgpr<[? + 2]>, !amdgcn.vgpr<[? + 2]>)`
// CHECK:    results: [9 = `%{{.*}}#0`, 10 = `%{{.*}}#1`]
// CHECK:  Op: module {...}
// CHECK:    LIVE BEFORE: []
// CHECK:    LIVE  AFTER: []
// CHECK:  Symbol: bb_value_liveness
// CHECK:  Op: func.func @bb_value_liveness(%{{.*}}: i1) {...}
// CHECK:    LIVE BEFORE: []
// CHECK:    LIVE  AFTER: []
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.vgpr
// CHECK:    LIVE BEFORE: []
// CHECK:    LIVE  AFTER: []
// CHECK:  Op: %{{.*}} = amdgcn.alloca : !amdgcn.vgpr
// CHECK:    LIVE BEFORE: []
// CHECK:    LIVE  AFTER: []
// CHECK:  Op: %{{.*}} = amdgcn.make_register_range %{{.*}}, %{{.*}} : !amdgcn.vgpr, !amdgcn.vgpr
// CHECK:    LIVE BEFORE: []
// CHECK:    LIVE  AFTER: []
// CHECK:  Op: %{{.*}} = amdgcn.test_inst outs %{{.*}} : (!amdgcn.vgpr<[? + 2]>) -> !amdgcn.vgpr<[? + 2]>
// CHECK:    LIVE BEFORE: []
// CHECK:    LIVE  AFTER: [6 = `%{{.*}}`]
// CHECK:  Op: %{{.*}} = amdgcn.test_inst outs %{{.*}} : (!amdgcn.vgpr<[? + 2]>) -> !amdgcn.vgpr<[? + 2]>
// CHECK:    LIVE BEFORE: [6 = `%{{.*}}`]
// CHECK:    LIVE  AFTER: [6 = `%{{.*}}`, 7 = `%{{.*}}`]
// CHECK:  Op: cf.br ^bb1(%{{.*}}, %{{.*}} : !amdgcn.vgpr<[? + 2]>, !amdgcn.vgpr<[? + 2]>)
// CHECK:    LIVE BEFORE: [6 = `%{{.*}}`, 7 = `%{{.*}}`]
// CHECK:    LIVE  AFTER: [6 = `%{{.*}}`, 7 = `%{{.*}}`]
// CHECK:  Op: %{{.*}} = amdgcn.test_inst outs %{{.*}} ins %{{.*}} : (!amdgcn.vgpr<[? + 2]>, !amdgcn.vgpr<[? + 2]>) -> !amdgcn.vgpr<[? + 2]>
// CHECK:    LIVE BEFORE: [1 = `%{{.*}}`, 2 = `%{{.*}}`]
// CHECK:    LIVE  AFTER: [2 = `%{{.*}}`, 8 = `%{{.*}}`]
// CHECK:  Op: cf.cond_br %{{.*}}, ^bb1(%{{.*}}, %{{.*}} : !amdgcn.vgpr<[? + 2]>, !amdgcn.vgpr<[? + 2]>), ^bb2
// CHECK:    LIVE BEFORE: [2 = `%{{.*}}`, 8 = `%{{.*}}`]
// CHECK:    LIVE  AFTER: [2 = `%{{.*}}`, 8 = `%{{.*}}`]
// CHECK:  Op: %{{.*}}:2 = amdgcn.test_inst outs %{{.*}}, %{{.*}} ins %{{.*}}, %{{.*}} : (!amdgcn.vgpr<[? + 2]>, !amdgcn.vgpr<[? + 2]>, !amdgcn.vgpr<[? + 2]>, !amdgcn.vgpr<[? + 2]>) -> (!amdgcn.vgpr<[? + 2]>, !amdgcn.vgpr<[? + 2]>)
// CHECK:    LIVE BEFORE: [2 = `%{{.*}}`, 8 = `%{{.*}}`]
// CHECK:    LIVE  AFTER: [9 = `%{{.*}}#0`, 10 = `%{{.*}}#1`]
// CHECK:  Op: amdgcn.test_inst ins %{{.*}}#0, %{{.*}}#1 : (!amdgcn.vgpr<[? + 2]>, !amdgcn.vgpr<[? + 2]>) -> ()
// CHECK:    LIVE BEFORE: [9 = `%{{.*}}#0`, 10 = `%{{.*}}#1`]
// CHECK:    LIVE  AFTER: []
// CHECK:  Op: func.return
// CHECK:    LIVE BEFORE: []
// CHECK:    LIVE  AFTER: []
func.func @bb_value_liveness(%arg0: i1) {
  %0 = amdgcn.alloca : !amdgcn.vgpr
  %1 = amdgcn.alloca : !amdgcn.vgpr
  %2 = amdgcn.make_register_range %0, %1 : !amdgcn.vgpr, !amdgcn.vgpr
  %3 = amdgcn.test_inst outs %2 : (!amdgcn.vgpr<[? + 2]>) -> !amdgcn.vgpr<[? + 2]>
  %4 = amdgcn.test_inst outs %2 : (!amdgcn.vgpr<[? + 2]>) -> !amdgcn.vgpr<[? + 2]>
  cf.br ^bb1(%3, %4 : !amdgcn.vgpr<[? + 2]>, !amdgcn.vgpr<[? + 2]>)
^bb1(%5: !amdgcn.vgpr<[? + 2]>, %6: !amdgcn.vgpr<[? + 2]>):  // 2 preds: ^bb0, ^bb1
  %7 = amdgcn.test_inst outs %2 ins %5 : (!amdgcn.vgpr<[? + 2]>, !amdgcn.vgpr<[? + 2]>) -> !amdgcn.vgpr<[? + 2]>
  cf.cond_br %arg0, ^bb1(%6, %7 : !amdgcn.vgpr<[? + 2]>, !amdgcn.vgpr<[? + 2]>), ^bb2
^bb2:  // pred: ^bb1
  %8, %9 = amdgcn.test_inst outs %6, %7 ins %6, %7 : (!amdgcn.vgpr<[? + 2]>, !amdgcn.vgpr<[? + 2]>, !amdgcn.vgpr<[? + 2]>, !amdgcn.vgpr<[? + 2]>) -> (!amdgcn.vgpr<[? + 2]>, !amdgcn.vgpr<[? + 2]>)
  amdgcn.test_inst ins %8, %9 : (!amdgcn.vgpr<[? + 2]>, !amdgcn.vgpr<[? + 2]>) -> ()
  return
}
