// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// This script is intended to make adding checks to a test case quick and easy.
// It is *not* authoritative about what constitutes a good test. After using the
// script, be sure to review and refine the generated checks. For example,
// CHECK lines should be minimized and named to reflect the test’s intent.
// For comprehensive guidelines, see:
//   * https://mlir.llvm.org/getting_started/TestingGuide/

// RUN: aster-opt %s -aster-to-amdgcn | FileCheck %s


// CHECK-LABEL:   func.func @test_add_i16(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.vgpr, %[[ARG1:.*]]: !amdgcn.vgpr, %[[ARG2:.*]]: !amdgcn.vgpr) -> !amdgcn.vgpr {
// CHECK:           %[[VAL_0:.*]] = amdgcn.vop2 v_add_u16 outs %[[ARG0]] ins %[[ARG1]], %[[ARG2]] : !amdgcn.vgpr, !amdgcn.vgpr, !amdgcn.vgpr
// CHECK:           return %[[VAL_0]] : !amdgcn.vgpr
// CHECK:         }
func.func @test_add_i16(%dst: !amdgcn.vgpr, %lhs: !amdgcn.vgpr, %rhs: !amdgcn.vgpr) -> !amdgcn.vgpr{
  %res = pir.addi i16 %dst, %lhs, %rhs : !amdgcn.vgpr, !amdgcn.vgpr, !amdgcn.vgpr
  return %res : !amdgcn.vgpr
}

// CHECK-LABEL:   func.func @test_add_i32(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.vgpr, %[[ARG1:.*]]: !amdgcn.vgpr, %[[ARG2:.*]]: !amdgcn.vgpr) -> !amdgcn.vgpr {
// CHECK:           %[[VAL_0:.*]] = amdgcn.vop2 v_add_u32 outs %[[ARG0]] ins %[[ARG1]], %[[ARG2]] : !amdgcn.vgpr, !amdgcn.vgpr, !amdgcn.vgpr
// CHECK:           return %[[VAL_0]] : !amdgcn.vgpr
// CHECK:         }
func.func @test_add_i32(%dst: !amdgcn.vgpr, %lhs: !amdgcn.vgpr, %rhs: !amdgcn.vgpr) -> !amdgcn.vgpr{
  %res = pir.addi i32 %dst, %lhs, %rhs : !amdgcn.vgpr, !amdgcn.vgpr, !amdgcn.vgpr
  return %res : !amdgcn.vgpr
}

// CHECK-LABEL:   func.func @test_add_i64(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.vgpr_range<[? + 2]>, %[[ARG1:.*]]: !amdgcn.vgpr_range<[? + 2]>, %[[ARG2:.*]]: !amdgcn.vgpr_range<[? + 2]>) -> !amdgcn.vgpr_range<[? + 2]> {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant 0 : i32
// CHECK:           %[[VAL_0:.*]] = amdgcn.vop3 v_lshl_add_u64 outs %[[ARG0]] ins %[[ARG1]], %[[CONSTANT_0]] src2 = %[[ARG2]] : !amdgcn.vgpr_range<[? + 2]>, !amdgcn.vgpr_range<[? + 2]>, i32, !amdgcn.vgpr_range<[? + 2]>
// CHECK:           return %[[VAL_0]] : !amdgcn.vgpr_range<[? + 2]>
// CHECK:         }
func.func @test_add_i64(%dst: !amdgcn.vgpr_range<[? + 2]>, %lhs: !amdgcn.vgpr_range<[? + 2]>, %rhs: !amdgcn.vgpr_range<[? + 2]>) -> !amdgcn.vgpr_range<[? + 2]>{
  %res = pir.addi i64 %dst, %lhs, %rhs : !amdgcn.vgpr_range<[? + 2]>, !amdgcn.vgpr_range<[? + 2]>, !amdgcn.vgpr_range<[? + 2]>
  return %res : !amdgcn.vgpr_range<[? + 2]>
}

// CHECK-LABEL:   func.func @test_sadd_i16(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.sgpr, %[[ARG1:.*]]: !amdgcn.sgpr, %[[ARG2:.*]]: !amdgcn.sgpr) -> !amdgcn.sgpr {
// CHECK:           %[[VAL_0:.*]] = amdgcn.sop2 s_add_i32 outs %[[ARG0]] ins %[[ARG1]], %[[ARG2]] : !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr
// CHECK:           return %[[VAL_0]] : !amdgcn.sgpr
// CHECK:         }
func.func @test_sadd_i16(%dst: !amdgcn.sgpr, %lhs: !amdgcn.sgpr, %rhs: !amdgcn.sgpr) -> !amdgcn.sgpr{
  %res = pir.addi i16 %dst, %lhs, %rhs : !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr
  return %res : !amdgcn.sgpr
}

// CHECK-LABEL:   func.func @test_sadd_i32(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.sgpr, %[[ARG1:.*]]: !amdgcn.sgpr, %[[ARG2:.*]]: !amdgcn.sgpr) -> !amdgcn.sgpr {
// CHECK:           %[[VAL_0:.*]] = amdgcn.sop2 s_add_i32 outs %[[ARG0]] ins %[[ARG1]], %[[ARG2]] : !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr
// CHECK:           return %[[VAL_0]] : !amdgcn.sgpr
// CHECK:         }
func.func @test_sadd_i32(%dst: !amdgcn.sgpr, %lhs: !amdgcn.sgpr, %rhs: !amdgcn.sgpr) -> !amdgcn.sgpr{
  %res = pir.addi i32 %dst, %lhs, %rhs : !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr
  return %res : !amdgcn.sgpr
}

// CHECK-LABEL:   func.func @test_sadd_i64(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.sgpr_range<[? + 2]>, %[[ARG1:.*]]: !amdgcn.sgpr_range<[? + 2]>, %[[ARG2:.*]]: !amdgcn.sgpr_range<[? + 2]>) -> !amdgcn.sgpr_range<[? + 2]> {
// CHECK:           %[[SPLIT_REGISTER_RANGE_0:.*]]:2 = amdgcn.split_register_range %[[ARG1]] : !amdgcn.sgpr_range<[? + 2]>
// CHECK:           %[[SPLIT_REGISTER_RANGE_1:.*]]:2 = amdgcn.split_register_range %[[ARG2]] : !amdgcn.sgpr_range<[? + 2]>
// CHECK:           %[[SPLIT_REGISTER_RANGE_2:.*]]:2 = amdgcn.split_register_range %[[ARG0]] : !amdgcn.sgpr_range<[? + 2]>
// CHECK:           %[[VAL_0:.*]] = amdgcn.sop2 s_add_u32 outs %[[SPLIT_REGISTER_RANGE_2]]#0 ins %[[SPLIT_REGISTER_RANGE_0]]#0, %[[SPLIT_REGISTER_RANGE_1]]#0 : !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr
// CHECK:           %[[VAL_1:.*]] = amdgcn.sop2 s_addc_u32 outs %[[SPLIT_REGISTER_RANGE_2]]#1 ins %[[SPLIT_REGISTER_RANGE_0]]#1, %[[SPLIT_REGISTER_RANGE_1]]#1 : !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr
// CHECK:           %[[MAKE_REGISTER_RANGE_0:.*]] = amdgcn.make_register_range %[[VAL_0]], %[[VAL_1]] : !amdgcn.sgpr, !amdgcn.sgpr
// CHECK:           return %[[MAKE_REGISTER_RANGE_0]] : !amdgcn.sgpr_range<[? + 2]>
// CHECK:         }
func.func @test_sadd_i64(%dst: !amdgcn.sgpr_range<[? + 2]>, %lhs: !amdgcn.sgpr_range<[? + 2]>, %rhs: !amdgcn.sgpr_range<[? + 2]>) -> !amdgcn.sgpr_range<[? + 2]>{
  %res = pir.addi i64 %dst, %lhs, %rhs : !amdgcn.sgpr_range<[? + 2]>, !amdgcn.sgpr_range<[? + 2]>, !amdgcn.sgpr_range<[? + 2]>
  return %res : !amdgcn.sgpr_range<[? + 2]>
}

// CHECK-LABEL:   func.func @test_sub_i16(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.vgpr, %[[ARG1:.*]]: !amdgcn.vgpr, %[[ARG2:.*]]: !amdgcn.vgpr) -> !amdgcn.vgpr {
// CHECK:           %[[VAL_0:.*]] = amdgcn.vop2 v_sub_u16 outs %[[ARG0]] ins %[[ARG1]], %[[ARG2]] : !amdgcn.vgpr, !amdgcn.vgpr, !amdgcn.vgpr
// CHECK:           return %[[VAL_0]] : !amdgcn.vgpr
// CHECK:         }
func.func @test_sub_i16(%dst: !amdgcn.vgpr, %lhs: !amdgcn.vgpr, %rhs: !amdgcn.vgpr) -> !amdgcn.vgpr{
  %res = pir.subi i16 %dst, %lhs, %rhs : !amdgcn.vgpr, !amdgcn.vgpr, !amdgcn.vgpr
  return %res : !amdgcn.vgpr
}

// CHECK-LABEL:   func.func @test_sub_i32(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.vgpr, %[[ARG1:.*]]: !amdgcn.vgpr, %[[ARG2:.*]]: !amdgcn.vgpr) -> !amdgcn.vgpr {
// CHECK:           %[[VAL_0:.*]] = amdgcn.vop2 v_sub_u32 outs %[[ARG0]] ins %[[ARG1]], %[[ARG2]] : !amdgcn.vgpr, !amdgcn.vgpr, !amdgcn.vgpr
// CHECK:           return %[[VAL_0]] : !amdgcn.vgpr
// CHECK:         }
func.func @test_sub_i32(%dst: !amdgcn.vgpr, %lhs: !amdgcn.vgpr, %rhs: !amdgcn.vgpr) -> !amdgcn.vgpr{
  %res = pir.subi i32 %dst, %lhs, %rhs : !amdgcn.vgpr, !amdgcn.vgpr, !amdgcn.vgpr
  return %res : !amdgcn.vgpr
}

// CHECK-LABEL:   func.func @test_sub_i64(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.vgpr_range<[? + 2]>, %[[ARG1:.*]]: !amdgcn.vgpr_range<[? + 2]>, %[[ARG2:.*]]: !amdgcn.vgpr_range<[? + 2]>) -> !amdgcn.vgpr_range<[? + 2]> {
// CHECK:           %[[ALLOCA_0:.*]] = amdgcn.alloca : !amdgcn.sgpr
// CHECK:           %[[ALLOCA_1:.*]] = amdgcn.alloca : !amdgcn.sgpr
// CHECK:           %[[MAKE_REGISTER_RANGE_0:.*]] = amdgcn.make_register_range %[[ALLOCA_0]], %[[ALLOCA_1]] : !amdgcn.sgpr, !amdgcn.sgpr
// CHECK:           %[[SPLIT_REGISTER_RANGE_0:.*]]:2 = amdgcn.split_register_range %[[ARG1]] : !amdgcn.vgpr_range<[? + 2]>
// CHECK:           %[[SPLIT_REGISTER_RANGE_1:.*]]:2 = amdgcn.split_register_range %[[ARG2]] : !amdgcn.vgpr_range<[? + 2]>
// CHECK:           %[[SPLIT_REGISTER_RANGE_2:.*]]:2 = amdgcn.split_register_range %[[ARG0]] : !amdgcn.vgpr_range<[? + 2]>
// CHECK:           %[[VAL_0:.*]], %[[VAL_1:.*]] = amdgcn.vop2 v_sub_co_u32 outs %[[SPLIT_REGISTER_RANGE_2]]#0 dst1 = %[[MAKE_REGISTER_RANGE_0]] ins %[[SPLIT_REGISTER_RANGE_0]]#0, %[[SPLIT_REGISTER_RANGE_1]]#0 : !amdgcn.vgpr, !amdgcn.sgpr_range<[? + 2]>, !amdgcn.vgpr, !amdgcn.vgpr
// CHECK:           %[[VAL_2:.*]], %[[VAL_3:.*]] = amdgcn.vop2 v_subb_co_u32 outs %[[SPLIT_REGISTER_RANGE_2]]#1 dst1 = %[[MAKE_REGISTER_RANGE_0]] ins %[[SPLIT_REGISTER_RANGE_0]]#1, %[[SPLIT_REGISTER_RANGE_1]]#1 src2 = %[[MAKE_REGISTER_RANGE_0]] : !amdgcn.vgpr, !amdgcn.sgpr_range<[? + 2]>, !amdgcn.vgpr, !amdgcn.vgpr, !amdgcn.sgpr_range<[? + 2]>
// CHECK:           %[[MAKE_REGISTER_RANGE_1:.*]] = amdgcn.make_register_range %[[VAL_0]], %[[VAL_2]] : !amdgcn.vgpr, !amdgcn.vgpr
// CHECK:           return %[[MAKE_REGISTER_RANGE_1]] : !amdgcn.vgpr_range<[? + 2]>
// CHECK:         }
func.func @test_sub_i64(%dst: !amdgcn.vgpr_range<[? + 2]>, %lhs: !amdgcn.vgpr_range<[? + 2]>, %rhs: !amdgcn.vgpr_range<[? + 2]>) -> !amdgcn.vgpr_range<[? + 2]>{
  %res = pir.subi i64 %dst, %lhs, %rhs : !amdgcn.vgpr_range<[? + 2]>, !amdgcn.vgpr_range<[? + 2]>, !amdgcn.vgpr_range<[? + 2]>
  return %res : !amdgcn.vgpr_range<[? + 2]>
}

// CHECK-LABEL:   func.func @test_ssub_i16(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.sgpr, %[[ARG1:.*]]: !amdgcn.sgpr, %[[ARG2:.*]]: !amdgcn.sgpr) -> !amdgcn.sgpr {
// CHECK:           %[[VAL_0:.*]] = amdgcn.sop2 s_sub_u32 outs %[[ARG0]] ins %[[ARG1]], %[[ARG2]] : !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr
// CHECK:           return %[[VAL_0]] : !amdgcn.sgpr
// CHECK:         }
func.func @test_ssub_i16(%dst: !amdgcn.sgpr, %lhs: !amdgcn.sgpr, %rhs: !amdgcn.sgpr) -> !amdgcn.sgpr{
  %res = pir.subi i16 %dst, %lhs, %rhs : !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr
  return %res : !amdgcn.sgpr
}

// CHECK-LABEL:   func.func @test_ssub_i32(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.sgpr, %[[ARG1:.*]]: !amdgcn.sgpr, %[[ARG2:.*]]: !amdgcn.sgpr) -> !amdgcn.sgpr {
// CHECK:           %[[VAL_0:.*]] = amdgcn.sop2 s_sub_u32 outs %[[ARG0]] ins %[[ARG1]], %[[ARG2]] : !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr
// CHECK:           return %[[VAL_0]] : !amdgcn.sgpr
// CHECK:         }
func.func @test_ssub_i32(%dst: !amdgcn.sgpr, %lhs: !amdgcn.sgpr, %rhs: !amdgcn.sgpr) -> !amdgcn.sgpr{
  %res = pir.subi i32 %dst, %lhs, %rhs : !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr
  return %res : !amdgcn.sgpr
}

// CHECK-LABEL:   func.func @test_ssub_i64(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.sgpr_range<[? + 2]>, %[[ARG1:.*]]: !amdgcn.sgpr_range<[? + 2]>, %[[ARG2:.*]]: !amdgcn.sgpr_range<[? + 2]>) -> !amdgcn.sgpr_range<[? + 2]> {
// CHECK:           %[[SPLIT_REGISTER_RANGE_0:.*]]:2 = amdgcn.split_register_range %[[ARG1]] : !amdgcn.sgpr_range<[? + 2]>
// CHECK:           %[[SPLIT_REGISTER_RANGE_1:.*]]:2 = amdgcn.split_register_range %[[ARG2]] : !amdgcn.sgpr_range<[? + 2]>
// CHECK:           %[[SPLIT_REGISTER_RANGE_2:.*]]:2 = amdgcn.split_register_range %[[ARG0]] : !amdgcn.sgpr_range<[? + 2]>
// CHECK:           %[[VAL_0:.*]] = amdgcn.sop2 s_sub_u32 outs %[[SPLIT_REGISTER_RANGE_2]]#0 ins %[[SPLIT_REGISTER_RANGE_0]]#0, %[[SPLIT_REGISTER_RANGE_1]]#0 : !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr
// CHECK:           %[[VAL_1:.*]] = amdgcn.sop2 s_subb_u32 outs %[[SPLIT_REGISTER_RANGE_2]]#1 ins %[[SPLIT_REGISTER_RANGE_0]]#1, %[[SPLIT_REGISTER_RANGE_1]]#1 : !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr
// CHECK:           %[[MAKE_REGISTER_RANGE_0:.*]] = amdgcn.make_register_range %[[VAL_0]], %[[VAL_1]] : !amdgcn.sgpr, !amdgcn.sgpr
// CHECK:           return %[[MAKE_REGISTER_RANGE_0]] : !amdgcn.sgpr_range<[? + 2]>
// CHECK:         }
func.func @test_ssub_i64(%dst: !amdgcn.sgpr_range<[? + 2]>, %lhs: !amdgcn.sgpr_range<[? + 2]>, %rhs: !amdgcn.sgpr_range<[? + 2]>) -> !amdgcn.sgpr_range<[? + 2]>{
  %res = pir.subi i64 %dst, %lhs, %rhs : !amdgcn.sgpr_range<[? + 2]>, !amdgcn.sgpr_range<[? + 2]>, !amdgcn.sgpr_range<[? + 2]>
  return %res : !amdgcn.sgpr_range<[? + 2]>
}

// CHECK-LABEL:   func.func @test_mul_i16(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.vgpr, %[[ARG1:.*]]: !amdgcn.vgpr, %[[ARG2:.*]]: !amdgcn.vgpr) -> !amdgcn.vgpr {
// CHECK:           %[[VAL_0:.*]] = amdgcn.vop2 v_mul_lo_u16 outs %[[ARG0]] ins %[[ARG1]], %[[ARG2]] : !amdgcn.vgpr, !amdgcn.vgpr, !amdgcn.vgpr
// CHECK:           return %[[VAL_0]] : !amdgcn.vgpr
// CHECK:         }
func.func @test_mul_i16(%dst: !amdgcn.vgpr, %lhs: !amdgcn.vgpr, %rhs: !amdgcn.vgpr) -> !amdgcn.vgpr{
  %res = pir.muli i16 %dst, %lhs, %rhs : !amdgcn.vgpr, !amdgcn.vgpr, !amdgcn.vgpr
  return %res : !amdgcn.vgpr
}

// CHECK-LABEL:   func.func @test_mul_i32(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.vgpr, %[[ARG1:.*]]: !amdgcn.vgpr, %[[ARG2:.*]]: !amdgcn.vgpr) -> !amdgcn.vgpr {
// CHECK:           %[[VAL_0:.*]] = amdgcn.vop3 v_mul_lo_u32 outs %[[ARG0]] ins %[[ARG1]], %[[ARG2]] : !amdgcn.vgpr, !amdgcn.vgpr, !amdgcn.vgpr
// CHECK:           return %[[VAL_0]] : !amdgcn.vgpr
// CHECK:         }
func.func @test_mul_i32(%dst: !amdgcn.vgpr, %lhs: !amdgcn.vgpr, %rhs: !amdgcn.vgpr) -> !amdgcn.vgpr{
  %res = pir.muli i32 %dst, %lhs, %rhs : !amdgcn.vgpr, !amdgcn.vgpr, !amdgcn.vgpr
  return %res : !amdgcn.vgpr
}

// CHECK-LABEL:   func.func @test_mul_i64(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.vgpr_range<[? + 2]>, %[[ARG1:.*]]: !amdgcn.vgpr_range<[? + 2]>, %[[ARG2:.*]]: !amdgcn.vgpr_range<[? + 2]>) -> !amdgcn.vgpr_range<[? + 2]> {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant 0 : i32
// CHECK:           %[[SPLIT_REGISTER_RANGE_0:.*]]:2 = amdgcn.split_register_range %[[ARG1]] : !amdgcn.vgpr_range<[? + 2]>
// CHECK:           %[[SPLIT_REGISTER_RANGE_1:.*]]:2 = amdgcn.split_register_range %[[ARG2]] : !amdgcn.vgpr_range<[? + 2]>
// CHECK:           %[[ALLOCA_0:.*]] = amdgcn.alloca : !amdgcn.vgpr
// CHECK:           %[[ALLOCA_1:.*]] = amdgcn.alloca : !amdgcn.sgpr
// CHECK:           %[[ALLOCA_2:.*]] = amdgcn.alloca : !amdgcn.sgpr
// CHECK:           %[[MAKE_REGISTER_RANGE_0:.*]] = amdgcn.make_register_range %[[ALLOCA_1]], %[[ALLOCA_2]] : !amdgcn.sgpr, !amdgcn.sgpr
// CHECK:           %[[VAL_0:.*]] = amdgcn.vop3 v_mul_lo_u32 outs %[[SPLIT_REGISTER_RANGE_1]]#1 ins %[[SPLIT_REGISTER_RANGE_1]]#1, %[[SPLIT_REGISTER_RANGE_0]]#0 : !amdgcn.vgpr, !amdgcn.vgpr, !amdgcn.vgpr
// CHECK:           %[[VAL_1:.*]], %[[VAL_2:.*]] = amdgcn.vop3 v_mad_u64_u32 outs %[[ARG0]] dst1 = %[[MAKE_REGISTER_RANGE_0]] ins %[[SPLIT_REGISTER_RANGE_1]]#0, %[[SPLIT_REGISTER_RANGE_0]]#0 src2 = %[[CONSTANT_0]] : !amdgcn.vgpr_range<[? + 2]>, !amdgcn.sgpr_range<[? + 2]>, !amdgcn.vgpr, !amdgcn.vgpr, i32
// CHECK:           %[[SPLIT_REGISTER_RANGE_2:.*]]:2 = amdgcn.split_register_range %[[VAL_1]] : !amdgcn.vgpr_range<[? + 2]>
// CHECK:           %[[VAL_3:.*]] = amdgcn.vop3 v_add3_u32 outs %[[SPLIT_REGISTER_RANGE_2]]#1 ins %[[SPLIT_REGISTER_RANGE_2]]#1, %[[ALLOCA_0]] src2 = %[[VAL_0]] : !amdgcn.vgpr, !amdgcn.vgpr, !amdgcn.vgpr, !amdgcn.vgpr
// CHECK:           %[[MAKE_REGISTER_RANGE_1:.*]] = amdgcn.make_register_range %[[SPLIT_REGISTER_RANGE_2]]#0, %[[VAL_3]] : !amdgcn.vgpr, !amdgcn.vgpr
// CHECK:           return %[[MAKE_REGISTER_RANGE_1]] : !amdgcn.vgpr_range<[? + 2]>
// CHECK:         }
func.func @test_mul_i64(%dst: !amdgcn.vgpr_range<[? + 2]>, %lhs: !amdgcn.vgpr_range<[? + 2]>, %rhs: !amdgcn.vgpr_range<[? + 2]>) -> !amdgcn.vgpr_range<[? + 2]>{
  %res = pir.muli i64 %dst, %lhs, %rhs : !amdgcn.vgpr_range<[? + 2]>, !amdgcn.vgpr_range<[? + 2]>, !amdgcn.vgpr_range<[? + 2]>
  return %res : !amdgcn.vgpr_range<[? + 2]>
}

// CHECK-LABEL:   func.func @test_smul_i16(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.sgpr, %[[ARG1:.*]]: !amdgcn.sgpr, %[[ARG2:.*]]: !amdgcn.sgpr) -> !amdgcn.sgpr {
// CHECK:           %[[VAL_0:.*]] = amdgcn.sop2 s_mul_i32 outs %[[ARG0]] ins %[[ARG1]], %[[ARG2]] : !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr
// CHECK:           return %[[VAL_0]] : !amdgcn.sgpr
// CHECK:         }
func.func @test_smul_i16(%dst: !amdgcn.sgpr, %lhs: !amdgcn.sgpr, %rhs: !amdgcn.sgpr) -> !amdgcn.sgpr{
  %res = pir.muli i16 %dst, %lhs, %rhs : !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr
  return %res : !amdgcn.sgpr
}

// CHECK-LABEL:   func.func @test_smul_i32(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.sgpr, %[[ARG1:.*]]: !amdgcn.sgpr, %[[ARG2:.*]]: !amdgcn.sgpr) -> !amdgcn.sgpr {
// CHECK:           %[[VAL_0:.*]] = amdgcn.sop2 s_mul_i32 outs %[[ARG0]] ins %[[ARG1]], %[[ARG2]] : !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr
// CHECK:           return %[[VAL_0]] : !amdgcn.sgpr
// CHECK:         }
func.func @test_smul_i32(%dst: !amdgcn.sgpr, %lhs: !amdgcn.sgpr, %rhs: !amdgcn.sgpr) -> !amdgcn.sgpr{
  %res = pir.muli i32 %dst, %lhs, %rhs : !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr
  return %res : !amdgcn.sgpr
}

// CHECK-LABEL:   func.func @test_smul_i64(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.sgpr_range<[? + 2]>, %[[ARG1:.*]]: !amdgcn.sgpr_range<[? + 2]>, %[[ARG2:.*]]: !amdgcn.sgpr_range<[? + 2]>) -> !amdgcn.sgpr_range<[? + 2]> {
// CHECK:           %[[SPLIT_REGISTER_RANGE_0:.*]]:2 = amdgcn.split_register_range %[[ARG1]] : !amdgcn.sgpr_range<[? + 2]>
// CHECK:           %[[SPLIT_REGISTER_RANGE_1:.*]]:2 = amdgcn.split_register_range %[[ARG2]] : !amdgcn.sgpr_range<[? + 2]>
// CHECK:           %[[SPLIT_REGISTER_RANGE_2:.*]]:2 = amdgcn.split_register_range %[[ARG0]] : !amdgcn.sgpr_range<[? + 2]>
// CHECK:           %[[VAL_0:.*]] = amdgcn.sop2 s_mul_i32 outs %[[SPLIT_REGISTER_RANGE_0]]#1 ins %[[SPLIT_REGISTER_RANGE_1]]#0, %[[SPLIT_REGISTER_RANGE_0]]#1 : !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr
// CHECK:           %[[VAL_1:.*]] = amdgcn.sop2 s_mul_hi_u32 outs %[[SPLIT_REGISTER_RANGE_2]]#0 ins %[[SPLIT_REGISTER_RANGE_1]]#0, %[[SPLIT_REGISTER_RANGE_0]]#0 : !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr
// CHECK:           %[[VAL_2:.*]] = amdgcn.sop2 s_mul_i32 outs %[[SPLIT_REGISTER_RANGE_1]]#1 ins %[[SPLIT_REGISTER_RANGE_1]]#1, %[[SPLIT_REGISTER_RANGE_0]]#0 : !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr
// CHECK:           %[[VAL_3:.*]] = amdgcn.sop2 s_add_i32 outs %[[VAL_0]] ins %[[VAL_1]], %[[VAL_0]] : !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr
// CHECK:           %[[VAL_4:.*]] = amdgcn.sop2 s_mul_i32 outs %[[SPLIT_REGISTER_RANGE_2]]#0 ins %[[SPLIT_REGISTER_RANGE_1]]#0, %[[SPLIT_REGISTER_RANGE_0]]#0 : !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr
// CHECK:           %[[VAL_5:.*]] = amdgcn.sop2 s_add_i32 outs %[[SPLIT_REGISTER_RANGE_2]]#1 ins %[[VAL_3]], %[[VAL_2]] : !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr
// CHECK:           %[[MAKE_REGISTER_RANGE_0:.*]] = amdgcn.make_register_range %[[VAL_4]], %[[VAL_5]] : !amdgcn.sgpr, !amdgcn.sgpr
// CHECK:           return %[[MAKE_REGISTER_RANGE_0]] : !amdgcn.sgpr_range<[? + 2]>
// CHECK:         }
func.func @test_smul_i64(%dst: !amdgcn.sgpr_range<[? + 2]>, %lhs: !amdgcn.sgpr_range<[? + 2]>, %rhs: !amdgcn.sgpr_range<[? + 2]>) -> !amdgcn.sgpr_range<[? + 2]>{
  %res = pir.muli i64 %dst, %lhs, %rhs : !amdgcn.sgpr_range<[? + 2]>, !amdgcn.sgpr_range<[? + 2]>, !amdgcn.sgpr_range<[? + 2]>
  return %res : !amdgcn.sgpr_range<[? + 2]>
}
