// RUN: aster-opt %s -aster-to-amdgcn | FileCheck %s

// CHECK-LABEL:   func.func @test_add_i32(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.vgpr, %[[ARG1:.*]]: !amdgcn.vgpr, %[[ARG2:.*]]: !amdgcn.vgpr) -> !amdgcn.vgpr {
// CHECK:           %[[VAL_0:.*]] = amdgcn.vop2 v_add_u32 outs %[[ARG0]] ins %[[ARG1]], %[[ARG2]] : !amdgcn.vgpr, !amdgcn.vgpr, !amdgcn.vgpr
// CHECK:           return %[[VAL_0]] : !amdgcn.vgpr
// CHECK:         }
func.func @test_add_i32(%dst: !amdgcn.vgpr, %lhs: !amdgcn.vgpr, %rhs: !amdgcn.vgpr) -> !amdgcn.vgpr{
  %res = pir.addi i32 %dst, %lhs, %rhs : !amdgcn.vgpr, !amdgcn.vgpr, !amdgcn.vgpr
  return %res : !amdgcn.vgpr
}

// CHECK-LABEL:   func.func @test_add_i64(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.vgpr_range<[? + 2]>, %[[ARG1:.*]]: !amdgcn.vgpr_range<[? + 2]>, %[[ARG2:.*]]: !amdgcn.vgpr_range<[? + 2]>) -> !amdgcn.vgpr_range<[? + 2]> {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant 0 : i32
// CHECK:           %[[VAL_0:.*]] = amdgcn.vop3 v_lshl_add_u64 outs %[[ARG0]] ins %[[ARG1]], %[[CONSTANT_0]] src2 = %[[ARG2]] : !amdgcn.vgpr_range<[? + 2]>, !amdgcn.vgpr_range<[? + 2]>, i32, !amdgcn.vgpr_range<[? + 2]>
// CHECK:           return %[[VAL_0]] : !amdgcn.vgpr_range<[? + 2]>
// CHECK:         }
func.func @test_add_i64(%dst: !amdgcn.vgpr_range<[? + 2]>, %lhs: !amdgcn.vgpr_range<[? + 2]>, %rhs: !amdgcn.vgpr_range<[? + 2]>) -> !amdgcn.vgpr_range<[? + 2]>{
  %res = pir.addi i64 %dst, %lhs, %rhs : !amdgcn.vgpr_range<[? + 2]>, !amdgcn.vgpr_range<[? + 2]>, !amdgcn.vgpr_range<[? + 2]>
  return %res : !amdgcn.vgpr_range<[? + 2]>
}

// CHECK-LABEL:   func.func @test_sadd_i32(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.sgpr, %[[ARG1:.*]]: !amdgcn.sgpr, %[[ARG2:.*]]: !amdgcn.sgpr) -> !amdgcn.sgpr {
// CHECK:           %[[VAL_0:.*]] = amdgcn.sop2 s_add_u32 outs %[[ARG0]] ins %[[ARG1]], %[[ARG2]] : !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr
// CHECK:           return %[[VAL_0]] : !amdgcn.sgpr
// CHECK:         }
func.func @test_sadd_i32(%dst: !amdgcn.sgpr, %lhs: !amdgcn.sgpr, %rhs: !amdgcn.sgpr) -> !amdgcn.sgpr{
  %res = pir.addi i32 %dst, %lhs, %rhs : !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr
  return %res : !amdgcn.sgpr
}

// CHECK-LABEL:   func.func @test_sadd_i64(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.sgpr_range<[? + 2]>, %[[ARG1:.*]]: !amdgcn.sgpr_range<[? + 2]>, %[[ARG2:.*]]: !amdgcn.sgpr_range<[? + 2]>) -> !amdgcn.sgpr_range<[? + 2]> {
// CHECK:           %[[SPLIT_REGISTER_RANGE_0:.*]]:2 = amdgcn.split_register_range %[[ARG0]] : !amdgcn.sgpr_range<[? + 2]>
// CHECK:           %[[SPLIT_REGISTER_RANGE_1:.*]]:2 = amdgcn.split_register_range %[[ARG1]] : !amdgcn.sgpr_range<[? + 2]>
// CHECK:           %[[SPLIT_REGISTER_RANGE_2:.*]]:2 = amdgcn.split_register_range %[[ARG2]] : !amdgcn.sgpr_range<[? + 2]>
// CHECK:           %[[VAL_0:.*]] = amdgcn.sop2 s_add_u32 outs %[[SPLIT_REGISTER_RANGE_0]]#0 ins %[[SPLIT_REGISTER_RANGE_1]]#0, %[[SPLIT_REGISTER_RANGE_2]]#0 : !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr
// CHECK:           %[[VAL_1:.*]] = amdgcn.sop2 s_addc_u32 outs %[[SPLIT_REGISTER_RANGE_0]]#1 ins %[[SPLIT_REGISTER_RANGE_1]]#1, %[[SPLIT_REGISTER_RANGE_2]]#1 : !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr
// CHECK:           %[[MAKE_REGISTER_RANGE_0:.*]] = amdgcn.make_register_range %[[VAL_0]], %[[VAL_1]] : !amdgcn.sgpr, !amdgcn.sgpr
// CHECK:           return %[[MAKE_REGISTER_RANGE_0]] : !amdgcn.sgpr_range<[? + 2]>
// CHECK:         }
func.func @test_sadd_i64(%dst: !amdgcn.sgpr_range<[? + 2]>, %lhs: !amdgcn.sgpr_range<[? + 2]>, %rhs: !amdgcn.sgpr_range<[? + 2]>) -> !amdgcn.sgpr_range<[? + 2]>{
  %res = pir.addi i64 %dst, %lhs, %rhs : !amdgcn.sgpr_range<[? + 2]>, !amdgcn.sgpr_range<[? + 2]>, !amdgcn.sgpr_range<[? + 2]>
  return %res : !amdgcn.sgpr_range<[? + 2]>
}

// CHECK-LABEL:   func.func @test_sub_i32(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.vgpr, %[[ARG1:.*]]: !amdgcn.vgpr, %[[ARG2:.*]]: !amdgcn.vgpr) -> !amdgcn.vgpr {
// CHECK:           %[[VAL_0:.*]] = amdgcn.vop2 v_sub_u32 outs %[[ARG0]] ins %[[ARG1]], %[[ARG2]] : !amdgcn.vgpr, !amdgcn.vgpr, !amdgcn.vgpr
// CHECK:           return %[[VAL_0]] : !amdgcn.vgpr
// CHECK:         }
func.func @test_sub_i32(%dst: !amdgcn.vgpr, %lhs: !amdgcn.vgpr, %rhs: !amdgcn.vgpr) -> !amdgcn.vgpr{
  %res = pir.subi i32 %dst, %lhs, %rhs : !amdgcn.vgpr, !amdgcn.vgpr, !amdgcn.vgpr
  return %res : !amdgcn.vgpr
}

// CHECK-LABEL:   func.func @test_sub_i64(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.vgpr_range<[? + 2]>, %[[ARG1:.*]]: !amdgcn.vgpr_range<[? + 2]>, %[[ARG2:.*]]: !amdgcn.vgpr_range<[? + 2]>) -> !amdgcn.vgpr_range<[? + 2]> {
// CHECK:           %[[SPLIT_REGISTER_RANGE_0:.*]]:2 = amdgcn.split_register_range %[[ARG0]] : !amdgcn.vgpr_range<[? + 2]>
// CHECK:           %[[SPLIT_REGISTER_RANGE_1:.*]]:2 = amdgcn.split_register_range %[[ARG1]] : !amdgcn.vgpr_range<[? + 2]>
// CHECK:           %[[SPLIT_REGISTER_RANGE_2:.*]]:2 = amdgcn.split_register_range %[[ARG2]] : !amdgcn.vgpr_range<[? + 2]>
// CHECK:           %[[ALLOCA_0:.*]] = amdgcn.alloca : !amdgcn.sgpr
// CHECK:           %[[ALLOCA_1:.*]] = amdgcn.alloca : !amdgcn.sgpr
// CHECK:           %[[MAKE_REGISTER_RANGE_0:.*]] = amdgcn.make_register_range %[[ALLOCA_0]], %[[ALLOCA_1]] : !amdgcn.sgpr, !amdgcn.sgpr
// CHECK:           %[[VAL_0:.*]], %[[VAL_1:.*]] = amdgcn.vop3 v_sub_co_u32_e64 outs %[[SPLIT_REGISTER_RANGE_0]]#0 dst1 = %[[MAKE_REGISTER_RANGE_0]] ins %[[SPLIT_REGISTER_RANGE_1]]#0, %[[SPLIT_REGISTER_RANGE_2]]#0 : !amdgcn.vgpr, !amdgcn.sgpr_range<[? + 2]>, !amdgcn.vgpr, !amdgcn.vgpr
// CHECK:           %[[VAL_2:.*]], %[[VAL_3:.*]] = amdgcn.vop3 v_subb_co_u32_e64 outs %[[SPLIT_REGISTER_RANGE_0]]#1 dst1 = %[[MAKE_REGISTER_RANGE_0]] ins %[[SPLIT_REGISTER_RANGE_1]]#1, %[[SPLIT_REGISTER_RANGE_2]]#1 src2 = %[[MAKE_REGISTER_RANGE_0]] : !amdgcn.vgpr, !amdgcn.sgpr_range<[? + 2]>, !amdgcn.vgpr, !amdgcn.vgpr, !amdgcn.sgpr_range<[? + 2]>
// CHECK:           %[[MAKE_REGISTER_RANGE_1:.*]] = amdgcn.make_register_range %[[VAL_0]], %[[VAL_2]] : !amdgcn.vgpr, !amdgcn.vgpr
// CHECK:           return %[[MAKE_REGISTER_RANGE_1]] : !amdgcn.vgpr_range<[? + 2]>
// CHECK:         }
func.func @test_sub_i64(%dst: !amdgcn.vgpr_range<[? + 2]>, %lhs: !amdgcn.vgpr_range<[? + 2]>, %rhs: !amdgcn.vgpr_range<[? + 2]>) -> !amdgcn.vgpr_range<[? + 2]>{
  %res = pir.subi i64 %dst, %lhs, %rhs : !amdgcn.vgpr_range<[? + 2]>, !amdgcn.vgpr_range<[? + 2]>, !amdgcn.vgpr_range<[? + 2]>
  return %res : !amdgcn.vgpr_range<[? + 2]>
}

// CHECK-LABEL:   func.func @test_ssub_i32(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.sgpr, %[[ARG1:.*]]: !amdgcn.sgpr, %[[ARG2:.*]]: !amdgcn.sgpr) -> !amdgcn.sgpr {
// CHECK:           %[[VAL_0:.*]] = amdgcn.sop2 s_sub_u32 outs %[[ARG0]] ins %[[ARG1]], %[[ARG2]] : !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr
// CHECK:           return %[[VAL_0]] : !amdgcn.sgpr
// CHECK:         }
func.func @test_ssub_i32(%dst: !amdgcn.sgpr, %lhs: !amdgcn.sgpr, %rhs: !amdgcn.sgpr) -> !amdgcn.sgpr{
  %res = pir.subi i32 %dst, %lhs, %rhs : !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr
  return %res : !amdgcn.sgpr
}

// CHECK-LABEL:   func.func @test_ssub_i64(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.sgpr_range<[? + 2]>, %[[ARG1:.*]]: !amdgcn.sgpr_range<[? + 2]>, %[[ARG2:.*]]: !amdgcn.sgpr_range<[? + 2]>) -> !amdgcn.sgpr_range<[? + 2]> {
// CHECK:           %[[SPLIT_REGISTER_RANGE_0:.*]]:2 = amdgcn.split_register_range %[[ARG0]] : !amdgcn.sgpr_range<[? + 2]>
// CHECK:           %[[SPLIT_REGISTER_RANGE_1:.*]]:2 = amdgcn.split_register_range %[[ARG1]] : !amdgcn.sgpr_range<[? + 2]>
// CHECK:           %[[SPLIT_REGISTER_RANGE_2:.*]]:2 = amdgcn.split_register_range %[[ARG2]] : !amdgcn.sgpr_range<[? + 2]>
// CHECK:           %[[VAL_0:.*]] = amdgcn.sop2 s_sub_u32 outs %[[SPLIT_REGISTER_RANGE_0]]#0 ins %[[SPLIT_REGISTER_RANGE_1]]#0, %[[SPLIT_REGISTER_RANGE_2]]#0 : !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr
// CHECK:           %[[VAL_1:.*]] = amdgcn.sop2 s_subb_u32 outs %[[SPLIT_REGISTER_RANGE_0]]#1 ins %[[SPLIT_REGISTER_RANGE_1]]#1, %[[SPLIT_REGISTER_RANGE_2]]#1 : !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr
// CHECK:           %[[MAKE_REGISTER_RANGE_0:.*]] = amdgcn.make_register_range %[[VAL_0]], %[[VAL_1]] : !amdgcn.sgpr, !amdgcn.sgpr
// CHECK:           return %[[MAKE_REGISTER_RANGE_0]] : !amdgcn.sgpr_range<[? + 2]>
// CHECK:         }
func.func @test_ssub_i64(%dst: !amdgcn.sgpr_range<[? + 2]>, %lhs: !amdgcn.sgpr_range<[? + 2]>, %rhs: !amdgcn.sgpr_range<[? + 2]>) -> !amdgcn.sgpr_range<[? + 2]>{
  %res = pir.subi i64 %dst, %lhs, %rhs : !amdgcn.sgpr_range<[? + 2]>, !amdgcn.sgpr_range<[? + 2]>, !amdgcn.sgpr_range<[? + 2]>
  return %res : !amdgcn.sgpr_range<[? + 2]>
}

// CHECK-LABEL:   func.func @test_mul_i32(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.vgpr, %[[ARG1:.*]]: !amdgcn.vgpr, %[[ARG2:.*]]: !amdgcn.vgpr) -> !amdgcn.vgpr {
// CHECK:           %[[VAL_0:.*]] = amdgcn.vop3 v_mul_lo_u32 outs %[[ARG0]] ins %[[ARG1]], %[[ARG2]] : !amdgcn.vgpr, !amdgcn.vgpr, !amdgcn.vgpr
// CHECK:           return %[[VAL_0]] : !amdgcn.vgpr
// CHECK:         }
func.func @test_mul_i32(%dst: !amdgcn.vgpr, %lhs: !amdgcn.vgpr, %rhs: !amdgcn.vgpr) -> !amdgcn.vgpr{
  %res = pir.muli i32 %dst, %lhs, %rhs : !amdgcn.vgpr, !amdgcn.vgpr, !amdgcn.vgpr
  return %res : !amdgcn.vgpr
}

// CHECK-LABEL:   func.func @test_mul_i64(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.vgpr_range<[? + 2]>, %[[ARG1:.*]]: !amdgcn.vgpr_range<[? + 2]>, %[[ARG2:.*]]: !amdgcn.vgpr_range<[? + 2]>) -> !amdgcn.vgpr_range<[? + 2]> {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant 0 : i32
// CHECK:           %[[SPLIT_REGISTER_RANGE_0:.*]]:2 = amdgcn.split_register_range %[[ARG1]] : !amdgcn.vgpr_range<[? + 2]>
// CHECK:           %[[SPLIT_REGISTER_RANGE_1:.*]]:2 = amdgcn.split_register_range %[[ARG2]] : !amdgcn.vgpr_range<[? + 2]>
// CHECK:           %[[ALLOCA_0:.*]] = amdgcn.alloca : !amdgcn.vgpr
// CHECK:           %[[ALLOCA_1:.*]] = amdgcn.alloca : !amdgcn.vgpr
// CHECK:           %[[ALLOCA_2:.*]] = amdgcn.alloca : !amdgcn.sgpr
// CHECK:           %[[ALLOCA_3:.*]] = amdgcn.alloca : !amdgcn.sgpr
// CHECK:           %[[MAKE_REGISTER_RANGE_0:.*]] = amdgcn.make_register_range %[[ALLOCA_2]], %[[ALLOCA_3]] : !amdgcn.sgpr, !amdgcn.sgpr
// CHECK:           %[[VAL_0:.*]] = amdgcn.vop3 v_mul_lo_u32 outs %[[ALLOCA_0]] ins %[[SPLIT_REGISTER_RANGE_1]]#1, %[[SPLIT_REGISTER_RANGE_0]]#0 : !amdgcn.vgpr, !amdgcn.vgpr, !amdgcn.vgpr
// CHECK:           %[[VAL_1:.*]] = amdgcn.vop3 v_mul_lo_u32 outs %[[ALLOCA_1]] ins %[[SPLIT_REGISTER_RANGE_1]]#0, %[[SPLIT_REGISTER_RANGE_0]]#1 : !amdgcn.vgpr, !amdgcn.vgpr, !amdgcn.vgpr
// CHECK:           %[[VAL_2:.*]], %[[VAL_3:.*]] = amdgcn.vop3 v_mad_u64_u32 outs %[[ARG0]] dst1 = %[[MAKE_REGISTER_RANGE_0]] ins %[[SPLIT_REGISTER_RANGE_1]]#0, %[[SPLIT_REGISTER_RANGE_0]]#0 src2 = %[[CONSTANT_0]] : !amdgcn.vgpr_range<[? + 2]>, !amdgcn.sgpr_range<[? + 2]>, !amdgcn.vgpr, !amdgcn.vgpr, i32
// CHECK:           %[[SPLIT_REGISTER_RANGE_2:.*]]:2 = amdgcn.split_register_range %[[VAL_2]] : !amdgcn.vgpr_range<[? + 2]>
// CHECK:           %[[VAL_4:.*]] = amdgcn.vop3 v_add3_u32 outs %[[SPLIT_REGISTER_RANGE_2]]#1 ins %[[SPLIT_REGISTER_RANGE_2]]#1, %[[VAL_1]] src2 = %[[VAL_0]] : !amdgcn.vgpr, !amdgcn.vgpr, !amdgcn.vgpr, !amdgcn.vgpr
// CHECK:           %[[MAKE_REGISTER_RANGE_1:.*]] = amdgcn.make_register_range %[[SPLIT_REGISTER_RANGE_2]]#0, %[[VAL_4]] : !amdgcn.vgpr, !amdgcn.vgpr
// CHECK:           return %[[MAKE_REGISTER_RANGE_1]] : !amdgcn.vgpr_range<[? + 2]>
// CHECK:         }
func.func @test_mul_i64(%dst: !amdgcn.vgpr_range<[? + 2]>, %lhs: !amdgcn.vgpr_range<[? + 2]>, %rhs: !amdgcn.vgpr_range<[? + 2]>) -> !amdgcn.vgpr_range<[? + 2]>{
  %res = pir.muli i64 %dst, %lhs, %rhs : !amdgcn.vgpr_range<[? + 2]>, !amdgcn.vgpr_range<[? + 2]>, !amdgcn.vgpr_range<[? + 2]>
  return %res : !amdgcn.vgpr_range<[? + 2]>
}

// CHECK-LABEL:   func.func @test_smul_i32(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.sgpr, %[[ARG1:.*]]: !amdgcn.sgpr, %[[ARG2:.*]]: !amdgcn.sgpr) -> !amdgcn.sgpr {
// CHECK:           %[[VAL_0:.*]] = amdgcn.sop2 s_mul_i32 outs %[[ARG0]] ins %[[ARG1]], %[[ARG2]] : !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr
// CHECK:           return %[[VAL_0]] : !amdgcn.sgpr
// CHECK:         }

func.func @test_smul_i32(%dst: !amdgcn.sgpr, %lhs: !amdgcn.sgpr, %rhs: !amdgcn.sgpr) -> !amdgcn.sgpr{
  %res = pir.muli i32 %dst, %lhs, %rhs : !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr
  return %res : !amdgcn.sgpr
}

// CHECK-LABEL:   func.func @test_smul_i64(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.sgpr_range<[? + 2]>, %[[ARG1:.*]]: !amdgcn.sgpr_range<[? + 2]>, %[[ARG2:.*]]: !amdgcn.sgpr_range<[? + 2]>) -> !amdgcn.sgpr_range<[? + 2]> {
// CHECK:           %[[SPLIT_REGISTER_RANGE_0:.*]]:2 = amdgcn.split_register_range %[[ARG0]] : !amdgcn.sgpr_range<[? + 2]>
// CHECK:           %[[SPLIT_REGISTER_RANGE_1:.*]]:2 = amdgcn.split_register_range %[[ARG1]] : !amdgcn.sgpr_range<[? + 2]>
// CHECK:           %[[SPLIT_REGISTER_RANGE_2:.*]]:2 = amdgcn.split_register_range %[[ARG2]] : !amdgcn.sgpr_range<[? + 2]>
// CHECK:           %[[ALLOCA_0:.*]] = amdgcn.alloca : !amdgcn.sgpr
// CHECK:           %[[ALLOCA_1:.*]] = amdgcn.alloca : !amdgcn.sgpr
// CHECK:           %[[VAL_0:.*]] = amdgcn.sop2 s_mul_i32 outs %[[SPLIT_REGISTER_RANGE_0]]#1 ins %[[SPLIT_REGISTER_RANGE_2]]#0, %[[SPLIT_REGISTER_RANGE_1]]#1 : !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr
// CHECK:           %[[VAL_1:.*]] = amdgcn.sop2 s_mul_hi_u32 outs %[[ALLOCA_0]] ins %[[SPLIT_REGISTER_RANGE_2]]#0, %[[SPLIT_REGISTER_RANGE_1]]#0 : !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr
// CHECK:           %[[VAL_2:.*]] = amdgcn.sop2 s_mul_i32 outs %[[ALLOCA_1]] ins %[[SPLIT_REGISTER_RANGE_2]]#1, %[[SPLIT_REGISTER_RANGE_1]]#0 : !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr
// CHECK:           %[[VAL_3:.*]] = amdgcn.sop2 s_add_i32 outs %[[VAL_0]] ins %[[VAL_1]], %[[VAL_0]] : !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr
// CHECK:           %[[VAL_4:.*]] = amdgcn.sop2 s_mul_i32 outs %[[SPLIT_REGISTER_RANGE_0]]#0 ins %[[SPLIT_REGISTER_RANGE_2]]#0, %[[SPLIT_REGISTER_RANGE_1]]#0 : !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr
// CHECK:           %[[VAL_5:.*]] = amdgcn.sop2 s_add_i32 outs %[[VAL_3]] ins %[[VAL_3]], %[[VAL_2]] : !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr
// CHECK:           %[[MAKE_REGISTER_RANGE_0:.*]] = amdgcn.make_register_range %[[VAL_4]], %[[VAL_5]] : !amdgcn.sgpr, !amdgcn.sgpr
// CHECK:           return %[[MAKE_REGISTER_RANGE_0]] : !amdgcn.sgpr_range<[? + 2]>
// CHECK:         }
func.func @test_smul_i64(%dst: !amdgcn.sgpr_range<[? + 2]>, %lhs: !amdgcn.sgpr_range<[? + 2]>, %rhs: !amdgcn.sgpr_range<[? + 2]>) -> !amdgcn.sgpr_range<[? + 2]>{
  %res = pir.muli i64 %dst, %lhs, %rhs : !amdgcn.sgpr_range<[? + 2]>, !amdgcn.sgpr_range<[? + 2]>, !amdgcn.sgpr_range<[? + 2]>
  return %res : !amdgcn.sgpr_range<[? + 2]>
}

amdgcn.module @test_timing_module target = #amdgcn.target<gfx942> isa = #amdgcn.isa<cdna3> {
  // CHECK-LABEL: kernel @test_timing_record
  amdgcn.kernel @test_timing_record arguments <[
    #amdgcn.buffer_arg<address_space = generic, access = read_write>,
    #amdgcn.buffer_arg<address_space = generic, access = read_write>
  ]> {
    // CHECK: %[[START_PTR:.*]] = load_arg 0 : !amdgcn.sgpr_range<[? + 2]>
    // CHECK: %[[END_PTR:.*]] = load_arg 1 : !amdgcn.sgpr_range<[? + 2]>
    %start_timing_ptr = amdgcn.load_arg 0 : !amdgcn.sgpr_range<[? + 2]>
    %end_timing_ptr = amdgcn.load_arg 1 : !amdgcn.sgpr_range<[? + 2]>
    amdgcn.sopp.s_waitcnt #amdgcn.inst<s_waitcnt> lgkmcnt = 0

    // Record start time - reads s_memtime and returns it (no store)
    // CHECK: %[[ALLOC1:.*]] = alloca : !amdgcn.sgpr
    // CHECK: %[[ALLOC2:.*]] = alloca : !amdgcn.sgpr
    // CHECK: %[[RANGE1:.*]] = make_register_range %[[ALLOC1]], %[[ALLOC2]]
    // CHECK: %[[START_TIME_SGPR:.*]] = amdgcn.smem.load <s_memtime> %[[RANGE1]]
    // CHECK: amdgcn.sopp.s_waitcnt <s_waitcnt> vmcnt = 0 expcnt = 0 lgkmcnt = 0
    %start_time = pir.timing_start : !amdgcn.sgpr_range<[? + 2]>

    // Record end time - reads s_memtime, then stores both start and end timestamps
    // CHECK: %[[ALLOC3:.*]] = alloca : !amdgcn.sgpr
    // CHECK: %[[ALLOC4:.*]] = alloca : !amdgcn.sgpr
    // CHECK: %[[RANGE2:.*]] = make_register_range %[[ALLOC3]], %[[ALLOC4]]
    // CHECK: %[[END_TIME_SGPR:.*]] = amdgcn.smem.load <s_memtime> %[[RANGE2]]
    // CHECK: amdgcn.sopp.s_waitcnt <s_waitcnt> vmcnt = 0 expcnt = 0 lgkmcnt = 0
    // CHECK: %[[START_SPLIT:.*]]:2 = split_register_range %[[START_TIME_SGPR]]
    // CHECK: %[[VALLOC1:.*]] = alloca : !amdgcn.vgpr
    // CHECK: %[[VALLOC2:.*]] = alloca : !amdgcn.vgpr
    // CHECK: %[[VMOV_LO1:.*]] = amdgcn.vop1.vop1 <v_mov_b32_e32> %[[VALLOC1]], %[[START_SPLIT]]#0
    // CHECK: %[[VMOV_HI1:.*]] = amdgcn.vop1.vop1 <v_mov_b32_e32> %[[VALLOC2]], %[[START_SPLIT]]#1
    // CHECK: %[[START_VGPR:.*]] = make_register_range %[[VMOV_LO1]], %[[VMOV_HI1]]
    // CHECK: %[[ZERO_VGPR1:.*]] = alloca : !amdgcn.vgpr
    // CHECK: %[[ZERO1:.*]] = amdgcn.vop1.vop1 <v_mov_b32_e32> %[[ZERO_VGPR1]], %{{.*}}
    // CHECK: amdgcn.flat.global_store <global_store_dwordx2> %[[START_VGPR]], %[[START_PTR]][%[[ZERO1]]]
    // CHECK: %[[END_SPLIT:.*]]:2 = split_register_range %[[END_TIME_SGPR]]
    // CHECK: %[[VALLOC3:.*]] = alloca : !amdgcn.vgpr
    // CHECK: %[[VALLOC4:.*]] = alloca : !amdgcn.vgpr
    // CHECK: %[[VMOV_LO2:.*]] = amdgcn.vop1.vop1 <v_mov_b32_e32> %[[VALLOC3]], %[[END_SPLIT]]#0
    // CHECK: %[[VMOV_HI2:.*]] = amdgcn.vop1.vop1 <v_mov_b32_e32> %[[VALLOC4]], %[[END_SPLIT]]#1
    // CHECK: %[[END_VGPR:.*]] = make_register_range %[[VMOV_LO2]], %[[VMOV_HI2]]
    // CHECK: %[[ZERO_VGPR2:.*]] = alloca : !amdgcn.vgpr
    // CHECK: %[[ZERO2:.*]] = amdgcn.vop1.vop1 <v_mov_b32_e32> %[[ZERO_VGPR2]], %{{.*}}
    // CHECK: amdgcn.flat.global_store <global_store_dwordx2> %[[END_VGPR]], %[[END_PTR]][%[[ZERO2]]]
    // CHECK: amdgcn.sopp.s_waitcnt <s_waitcnt> vmcnt = 0 expcnt = 0 lgkmcnt = 0
    pir.timing_stop %start_time, %start_timing_ptr, %end_timing_ptr
      : !amdgcn.sgpr_range<[? + 2]>, !amdgcn.sgpr_range<[? + 2]>, !amdgcn.sgpr_range<[? + 2]>

    // CHECK: end_kernel
    amdgcn.end_kernel
  }
}

// CHECK-LABEL:   func.func @test_shl_i16_vgpr(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.vgpr, %[[ARG1:.*]]: !amdgcn.vgpr, %[[ARG2:.*]]: !amdgcn.vgpr) -> !amdgcn.vgpr {
// CHECK:           %[[VAL_0:.*]] = amdgcn.vop2 v_lshlrev_b16 outs %[[ARG0]] ins %[[ARG2]], %[[ARG1]] : !amdgcn.vgpr, !amdgcn.vgpr, !amdgcn.vgpr
// CHECK:           return %[[VAL_0]] : !amdgcn.vgpr
// CHECK:         }
func.func @test_shl_i16_vgpr(%dst: !amdgcn.vgpr, %lhs: !amdgcn.vgpr, %rhs: !amdgcn.vgpr) -> !amdgcn.vgpr{
  %res = pir.shli i16 %dst, %lhs, %rhs : !amdgcn.vgpr, !amdgcn.vgpr, !amdgcn.vgpr
  return %res : !amdgcn.vgpr
}

// CHECK-LABEL:   func.func @test_shl_i32_vgpr(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.vgpr, %[[ARG1:.*]]: !amdgcn.vgpr, %[[ARG2:.*]]: !amdgcn.vgpr) -> !amdgcn.vgpr {
// CHECK:           %[[VAL_0:.*]] = amdgcn.vop2 v_lshlrev_b32_e32 outs %[[ARG0]] ins %[[ARG2]], %[[ARG1]] : !amdgcn.vgpr, !amdgcn.vgpr, !amdgcn.vgpr
// CHECK:           return %[[VAL_0]] : !amdgcn.vgpr
// CHECK:         }
func.func @test_shl_i32_vgpr(%dst: !amdgcn.vgpr, %lhs: !amdgcn.vgpr, %rhs: !amdgcn.vgpr) -> !amdgcn.vgpr{
  %res = pir.shli i32 %dst, %lhs, %rhs : !amdgcn.vgpr, !amdgcn.vgpr, !amdgcn.vgpr
  return %res : !amdgcn.vgpr
}

// CHECK-LABEL:   func.func @test_shl_i64_vgpr(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.vgpr_range<[? + 2]>, %[[ARG1:.*]]: !amdgcn.vgpr_range<[? + 2]>, %[[ARG2:.*]]: !amdgcn.vgpr_range<[? + 2]>) -> !amdgcn.vgpr_range<[? + 2]> {
// CHECK:           %[[VAL_0:.*]] = amdgcn.vop3 v_lshlrev_b64 outs %[[ARG0]] ins %[[ARG2]], %[[ARG1]] : !amdgcn.vgpr_range<[? + 2]>, !amdgcn.vgpr_range<[? + 2]>, !amdgcn.vgpr_range<[? + 2]>
// CHECK:           return %[[VAL_0]] : !amdgcn.vgpr_range<[? + 2]>
// CHECK:         }
func.func @test_shl_i64_vgpr(%dst: !amdgcn.vgpr_range<[? + 2]>, %lhs: !amdgcn.vgpr_range<[? + 2]>, %rhs: !amdgcn.vgpr_range<[? + 2]>) -> !amdgcn.vgpr_range<[? + 2]>{
  %res = pir.shli i64 %dst, %lhs, %rhs : !amdgcn.vgpr_range<[? + 2]>, !amdgcn.vgpr_range<[? + 2]>, !amdgcn.vgpr_range<[? + 2]>
  return %res : !amdgcn.vgpr_range<[? + 2]>
}

// CHECK-LABEL:   func.func @test_shl_i32_sgpr(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.sgpr, %[[ARG1:.*]]: !amdgcn.sgpr, %[[ARG2:.*]]: !amdgcn.sgpr) -> !amdgcn.sgpr {
// CHECK:           %[[VAL_0:.*]] = amdgcn.sop2 s_lshl_b32 outs %[[ARG0]] ins %[[ARG1]], %[[ARG2]] : !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr
// CHECK:           return %[[VAL_0]] : !amdgcn.sgpr
// CHECK:         }
func.func @test_shl_i32_sgpr(%dst: !amdgcn.sgpr, %lhs: !amdgcn.sgpr, %rhs: !amdgcn.sgpr) -> !amdgcn.sgpr{
  %res = pir.shli i32 %dst, %lhs, %rhs : !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr
  return %res : !amdgcn.sgpr
}

// CHECK-LABEL:   func.func @test_shl_i64_sgpr(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.sgpr_range<[? + 2]>, %[[ARG1:.*]]: !amdgcn.sgpr_range<[? + 2]>, %[[ARG2:.*]]: !amdgcn.sgpr_range<[? + 2]>) -> !amdgcn.sgpr_range<[? + 2]> {
// CHECK:           %[[VAL_0:.*]] = amdgcn.sop2 s_lshl_b64 outs %[[ARG0]] ins %[[ARG1]], %[[ARG2]] : !amdgcn.sgpr_range<[? + 2]>, !amdgcn.sgpr_range<[? + 2]>, !amdgcn.sgpr_range<[? + 2]>
// CHECK:           return %[[VAL_0]] : !amdgcn.sgpr_range<[? + 2]>
// CHECK:         }
func.func @test_shl_i64_sgpr(%dst: !amdgcn.sgpr_range<[? + 2]>, %lhs: !amdgcn.sgpr_range<[? + 2]>, %rhs: !amdgcn.sgpr_range<[? + 2]>) -> !amdgcn.sgpr_range<[? + 2]>{
  %res = pir.shli i64 %dst, %lhs, %rhs : !amdgcn.sgpr_range<[? + 2]>, !amdgcn.sgpr_range<[? + 2]>, !amdgcn.sgpr_range<[? + 2]>
  return %res : !amdgcn.sgpr_range<[? + 2]>
}

// CHECK-LABEL:   func.func @test_shrsi_i16_vgpr(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.vgpr, %[[ARG1:.*]]: !amdgcn.vgpr, %[[ARG2:.*]]: !amdgcn.vgpr) -> !amdgcn.vgpr {
// CHECK:           %[[VAL_0:.*]] = amdgcn.vop2 v_ashrrev_i16 outs %[[ARG0]] ins %[[ARG2]], %[[ARG1]] : !amdgcn.vgpr, !amdgcn.vgpr, !amdgcn.vgpr
// CHECK:           return %[[VAL_0]] : !amdgcn.vgpr
// CHECK:         }
func.func @test_shrsi_i16_vgpr(%dst: !amdgcn.vgpr, %lhs: !amdgcn.vgpr, %rhs: !amdgcn.vgpr) -> !amdgcn.vgpr{
  %res = pir.shrsi i16 %dst, %lhs, %rhs : !amdgcn.vgpr, !amdgcn.vgpr, !amdgcn.vgpr
  return %res : !amdgcn.vgpr
}

// CHECK-LABEL:   func.func @test_shrsi_i32_vgpr(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.vgpr, %[[ARG1:.*]]: !amdgcn.vgpr, %[[ARG2:.*]]: !amdgcn.vgpr) -> !amdgcn.vgpr {
// CHECK:           %[[VAL_0:.*]] = amdgcn.vop2 v_ashrrev_i32 outs %[[ARG0]] ins %[[ARG2]], %[[ARG1]] : !amdgcn.vgpr, !amdgcn.vgpr, !amdgcn.vgpr
// CHECK:           return %[[VAL_0]] : !amdgcn.vgpr
// CHECK:         }
func.func @test_shrsi_i32_vgpr(%dst: !amdgcn.vgpr, %lhs: !amdgcn.vgpr, %rhs: !amdgcn.vgpr) -> !amdgcn.vgpr{
  %res = pir.shrsi i32 %dst, %lhs, %rhs : !amdgcn.vgpr, !amdgcn.vgpr, !amdgcn.vgpr
  return %res : !amdgcn.vgpr
}

// CHECK-LABEL:   func.func @test_shrsi_i64_vgpr(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.vgpr_range<[? + 2]>, %[[ARG1:.*]]: !amdgcn.vgpr_range<[? + 2]>, %[[ARG2:.*]]: !amdgcn.vgpr_range<[? + 2]>) -> !amdgcn.vgpr_range<[? + 2]> {
// CHECK:           %[[VAL_0:.*]] = amdgcn.vop3 v_ashrrev_i64 outs %[[ARG0]] ins %[[ARG2]], %[[ARG1]] : !amdgcn.vgpr_range<[? + 2]>, !amdgcn.vgpr_range<[? + 2]>, !amdgcn.vgpr_range<[? + 2]>
// CHECK:           return %[[VAL_0]] : !amdgcn.vgpr_range<[? + 2]>
// CHECK:         }
func.func @test_shrsi_i64_vgpr(%dst: !amdgcn.vgpr_range<[? + 2]>, %lhs: !amdgcn.vgpr_range<[? + 2]>, %rhs: !amdgcn.vgpr_range<[? + 2]>) -> !amdgcn.vgpr_range<[? + 2]>{
  %res = pir.shrsi i64 %dst, %lhs, %rhs : !amdgcn.vgpr_range<[? + 2]>, !amdgcn.vgpr_range<[? + 2]>, !amdgcn.vgpr_range<[? + 2]>
  return %res : !amdgcn.vgpr_range<[? + 2]>
}

// CHECK-LABEL:   func.func @test_shrsi_i32_sgpr(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.sgpr, %[[ARG1:.*]]: !amdgcn.sgpr, %[[ARG2:.*]]: !amdgcn.sgpr) -> !amdgcn.sgpr {
// CHECK:           %[[VAL_0:.*]] = amdgcn.sop2 s_ashr_i32 outs %[[ARG0]] ins %[[ARG1]], %[[ARG2]] : !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr
// CHECK:           return %[[VAL_0]] : !amdgcn.sgpr
// CHECK:         }
func.func @test_shrsi_i32_sgpr(%dst: !amdgcn.sgpr, %lhs: !amdgcn.sgpr, %rhs: !amdgcn.sgpr) -> !amdgcn.sgpr{
  %res = pir.shrsi i32 %dst, %lhs, %rhs : !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr
  return %res : !amdgcn.sgpr
}

// CHECK-LABEL:   func.func @test_shrsi_i64_sgpr(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.sgpr_range<[? + 2]>, %[[ARG1:.*]]: !amdgcn.sgpr_range<[? + 2]>, %[[ARG2:.*]]: !amdgcn.sgpr_range<[? + 2]>) -> !amdgcn.sgpr_range<[? + 2]> {
// CHECK:           %[[VAL_0:.*]] = amdgcn.sop2 s_ashr_i64 outs %[[ARG0]] ins %[[ARG1]], %[[ARG2]] : !amdgcn.sgpr_range<[? + 2]>, !amdgcn.sgpr_range<[? + 2]>, !amdgcn.sgpr_range<[? + 2]>
// CHECK:           return %[[VAL_0]] : !amdgcn.sgpr_range<[? + 2]>
// CHECK:         }
func.func @test_shrsi_i64_sgpr(%dst: !amdgcn.sgpr_range<[? + 2]>, %lhs: !amdgcn.sgpr_range<[? + 2]>, %rhs: !amdgcn.sgpr_range<[? + 2]>) -> !amdgcn.sgpr_range<[? + 2]>{
  %res = pir.shrsi i64 %dst, %lhs, %rhs : !amdgcn.sgpr_range<[? + 2]>, !amdgcn.sgpr_range<[? + 2]>, !amdgcn.sgpr_range<[? + 2]>
  return %res : !amdgcn.sgpr_range<[? + 2]>
}

// CHECK-LABEL:   func.func @test_shrui_i16_vgpr(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.vgpr, %[[ARG1:.*]]: !amdgcn.vgpr, %[[ARG2:.*]]: !amdgcn.vgpr) -> !amdgcn.vgpr {
// CHECK:           %[[VAL_0:.*]] = amdgcn.vop2 v_lshrrev_b16 outs %[[ARG0]] ins %[[ARG2]], %[[ARG1]] : !amdgcn.vgpr, !amdgcn.vgpr, !amdgcn.vgpr
// CHECK:           return %[[VAL_0]] : !amdgcn.vgpr
// CHECK:         }
func.func @test_shrui_i16_vgpr(%dst: !amdgcn.vgpr, %lhs: !amdgcn.vgpr, %rhs: !amdgcn.vgpr) -> !amdgcn.vgpr{
  %res = pir.shrui i16 %dst, %lhs, %rhs : !amdgcn.vgpr, !amdgcn.vgpr, !amdgcn.vgpr
  return %res : !amdgcn.vgpr
}

// CHECK-LABEL:   func.func @test_shrui_i32_vgpr(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.vgpr, %[[ARG1:.*]]: !amdgcn.vgpr, %[[ARG2:.*]]: !amdgcn.vgpr) -> !amdgcn.vgpr {
// CHECK:           %[[VAL_0:.*]] = amdgcn.vop2 v_lshrrev_b32 outs %[[ARG0]] ins %[[ARG2]], %[[ARG1]] : !amdgcn.vgpr, !amdgcn.vgpr, !amdgcn.vgpr
// CHECK:           return %[[VAL_0]] : !amdgcn.vgpr
// CHECK:         }
func.func @test_shrui_i32_vgpr(%dst: !amdgcn.vgpr, %lhs: !amdgcn.vgpr, %rhs: !amdgcn.vgpr) -> !amdgcn.vgpr{
  %res = pir.shrui i32 %dst, %lhs, %rhs : !amdgcn.vgpr, !amdgcn.vgpr, !amdgcn.vgpr
  return %res : !amdgcn.vgpr
}

// CHECK-LABEL:   func.func @test_shrui_i64_vgpr(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.vgpr_range<[? + 2]>, %[[ARG1:.*]]: !amdgcn.vgpr_range<[? + 2]>, %[[ARG2:.*]]: !amdgcn.vgpr_range<[? + 2]>) -> !amdgcn.vgpr_range<[? + 2]> {
// CHECK:           %[[VAL_0:.*]] = amdgcn.vop3 v_lshrrev_b64 outs %[[ARG0]] ins %[[ARG2]], %[[ARG1]] : !amdgcn.vgpr_range<[? + 2]>, !amdgcn.vgpr_range<[? + 2]>, !amdgcn.vgpr_range<[? + 2]>
// CHECK:           return %[[VAL_0]] : !amdgcn.vgpr_range<[? + 2]>
// CHECK:         }
func.func @test_shrui_i64_vgpr(%dst: !amdgcn.vgpr_range<[? + 2]>, %lhs: !amdgcn.vgpr_range<[? + 2]>, %rhs: !amdgcn.vgpr_range<[? + 2]>) -> !amdgcn.vgpr_range<[? + 2]>{
  %res = pir.shrui i64 %dst, %lhs, %rhs : !amdgcn.vgpr_range<[? + 2]>, !amdgcn.vgpr_range<[? + 2]>, !amdgcn.vgpr_range<[? + 2]>
  return %res : !amdgcn.vgpr_range<[? + 2]>
}

// CHECK-LABEL:   func.func @test_shrui_i32_sgpr(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.sgpr, %[[ARG1:.*]]: !amdgcn.sgpr, %[[ARG2:.*]]: !amdgcn.sgpr) -> !amdgcn.sgpr {
// CHECK:           %[[VAL_0:.*]] = amdgcn.sop2 s_lshr_b32 outs %[[ARG0]] ins %[[ARG1]], %[[ARG2]] : !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr
// CHECK:           return %[[VAL_0]] : !amdgcn.sgpr
// CHECK:         }
func.func @test_shrui_i32_sgpr(%dst: !amdgcn.sgpr, %lhs: !amdgcn.sgpr, %rhs: !amdgcn.sgpr) -> !amdgcn.sgpr{
  %res = pir.shrui i32 %dst, %lhs, %rhs : !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr
  return %res : !amdgcn.sgpr
}

// CHECK-LABEL:   func.func @test_shrui_i64_sgpr(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.sgpr_range<[? + 2]>, %[[ARG1:.*]]: !amdgcn.sgpr_range<[? + 2]>, %[[ARG2:.*]]: !amdgcn.sgpr_range<[? + 2]>) -> !amdgcn.sgpr_range<[? + 2]> {
// CHECK:           %[[VAL_0:.*]] = amdgcn.sop2 s_lshr_b64 outs %[[ARG0]] ins %[[ARG1]], %[[ARG2]] : !amdgcn.sgpr_range<[? + 2]>, !amdgcn.sgpr_range<[? + 2]>, !amdgcn.sgpr_range<[? + 2]>
// CHECK:           return %[[VAL_0]] : !amdgcn.sgpr_range<[? + 2]>
// CHECK:         }
func.func @test_shrui_i64_sgpr(%dst: !amdgcn.sgpr_range<[? + 2]>, %lhs: !amdgcn.sgpr_range<[? + 2]>, %rhs: !amdgcn.sgpr_range<[? + 2]>) -> !amdgcn.sgpr_range<[? + 2]>{
  %res = pir.shrui i64 %dst, %lhs, %rhs : !amdgcn.sgpr_range<[? + 2]>, !amdgcn.sgpr_range<[? + 2]>, !amdgcn.sgpr_range<[? + 2]>
  return %res : !amdgcn.sgpr_range<[? + 2]>
}

// CHECK-LABEL:   func.func @test_and_i32_vgpr(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.vgpr, %[[ARG1:.*]]: !amdgcn.vgpr, %[[ARG2:.*]]: !amdgcn.vgpr) -> !amdgcn.vgpr {
// CHECK:           %[[VAL_0:.*]] = amdgcn.vop2 v_and_b32 outs %[[ARG0]] ins %[[ARG1]], %[[ARG2]] : !amdgcn.vgpr, !amdgcn.vgpr, !amdgcn.vgpr
// CHECK:           return %[[VAL_0]] : !amdgcn.vgpr
// CHECK:         }
func.func @test_and_i32_vgpr(%dst: !amdgcn.vgpr, %lhs: !amdgcn.vgpr, %rhs: !amdgcn.vgpr) -> !amdgcn.vgpr{
  %res = pir.andi i32 %dst, %lhs, %rhs : !amdgcn.vgpr, !amdgcn.vgpr, !amdgcn.vgpr
  return %res : !amdgcn.vgpr
}

// CHECK-LABEL:   func.func @test_and_i32_sgpr(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.sgpr, %[[ARG1:.*]]: !amdgcn.sgpr, %[[ARG2:.*]]: !amdgcn.sgpr) -> !amdgcn.sgpr {
// CHECK:           %[[VAL_0:.*]] = amdgcn.sop2 s_and_b32 outs %[[ARG0]] ins %[[ARG1]], %[[ARG2]] : !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr
// CHECK:           return %[[VAL_0]] : !amdgcn.sgpr
// CHECK:         }
func.func @test_and_i32_sgpr(%dst: !amdgcn.sgpr, %lhs: !amdgcn.sgpr, %rhs: !amdgcn.sgpr) -> !amdgcn.sgpr{
  %res = pir.andi i32 %dst, %lhs, %rhs : !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr
  return %res : !amdgcn.sgpr
}

// CHECK-LABEL:   func.func @test_and_i64_sgpr(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.sgpr_range<[? + 2]>, %[[ARG1:.*]]: !amdgcn.sgpr_range<[? + 2]>, %[[ARG2:.*]]: !amdgcn.sgpr_range<[? + 2]>) -> !amdgcn.sgpr_range<[? + 2]> {
// CHECK:           %[[VAL_0:.*]] = amdgcn.sop2 s_and_b64 outs %[[ARG0]] ins %[[ARG1]], %[[ARG2]] : !amdgcn.sgpr_range<[? + 2]>, !amdgcn.sgpr_range<[? + 2]>, !amdgcn.sgpr_range<[? + 2]>
// CHECK:           return %[[VAL_0]] : !amdgcn.sgpr_range<[? + 2]>
// CHECK:         }
func.func @test_and_i64_sgpr(%dst: !amdgcn.sgpr_range<[? + 2]>, %lhs: !amdgcn.sgpr_range<[? + 2]>, %rhs: !amdgcn.sgpr_range<[? + 2]>) -> !amdgcn.sgpr_range<[? + 2]>{
  %res = pir.andi i64 %dst, %lhs, %rhs : !amdgcn.sgpr_range<[? + 2]>, !amdgcn.sgpr_range<[? + 2]>, !amdgcn.sgpr_range<[? + 2]>
  return %res : !amdgcn.sgpr_range<[? + 2]>
}

// CHECK-LABEL:   func.func @test_or_i32_vgpr(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.vgpr, %[[ARG1:.*]]: !amdgcn.vgpr, %[[ARG2:.*]]: !amdgcn.vgpr) -> !amdgcn.vgpr {
// CHECK:           %[[VAL_0:.*]] = amdgcn.vop2 v_or_b32 outs %[[ARG0]] ins %[[ARG1]], %[[ARG2]] : !amdgcn.vgpr, !amdgcn.vgpr, !amdgcn.vgpr
// CHECK:           return %[[VAL_0]] : !amdgcn.vgpr
// CHECK:         }
func.func @test_or_i32_vgpr(%dst: !amdgcn.vgpr, %lhs: !amdgcn.vgpr, %rhs: !amdgcn.vgpr) -> !amdgcn.vgpr{
  %res = pir.ori i32 %dst, %lhs, %rhs : !amdgcn.vgpr, !amdgcn.vgpr, !amdgcn.vgpr
  return %res : !amdgcn.vgpr
}

// CHECK-LABEL:   func.func @test_or_i32_sgpr(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.sgpr, %[[ARG1:.*]]: !amdgcn.sgpr, %[[ARG2:.*]]: !amdgcn.sgpr) -> !amdgcn.sgpr {
// CHECK:           %[[VAL_0:.*]] = amdgcn.sop2 s_or_b32 outs %[[ARG0]] ins %[[ARG1]], %[[ARG2]] : !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr
// CHECK:           return %[[VAL_0]] : !amdgcn.sgpr
// CHECK:         }
func.func @test_or_i32_sgpr(%dst: !amdgcn.sgpr, %lhs: !amdgcn.sgpr, %rhs: !amdgcn.sgpr) -> !amdgcn.sgpr{
  %res = pir.ori i32 %dst, %lhs, %rhs : !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr
  return %res : !amdgcn.sgpr
}

// CHECK-LABEL:   func.func @test_or_i64_sgpr(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.sgpr_range<[? + 2]>, %[[ARG1:.*]]: !amdgcn.sgpr_range<[? + 2]>, %[[ARG2:.*]]: !amdgcn.sgpr_range<[? + 2]>) -> !amdgcn.sgpr_range<[? + 2]> {
// CHECK:           %[[VAL_0:.*]] = amdgcn.sop2 s_or_b64 outs %[[ARG0]] ins %[[ARG1]], %[[ARG2]] : !amdgcn.sgpr_range<[? + 2]>, !amdgcn.sgpr_range<[? + 2]>, !amdgcn.sgpr_range<[? + 2]>
// CHECK:           return %[[VAL_0]] : !amdgcn.sgpr_range<[? + 2]>
// CHECK:         }
func.func @test_or_i64_sgpr(%dst: !amdgcn.sgpr_range<[? + 2]>, %lhs: !amdgcn.sgpr_range<[? + 2]>, %rhs: !amdgcn.sgpr_range<[? + 2]>) -> !amdgcn.sgpr_range<[? + 2]>{
  %res = pir.ori i64 %dst, %lhs, %rhs : !amdgcn.sgpr_range<[? + 2]>, !amdgcn.sgpr_range<[? + 2]>, !amdgcn.sgpr_range<[? + 2]>
  return %res : !amdgcn.sgpr_range<[? + 2]>
}

// CHECK-LABEL:   func.func @test_load_global_dword(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.vgpr_range<[? + 1]>, %[[ARG1:.*]]: !amdgcn.vgpr_range<[? + 2]>) -> !amdgcn.vgpr_range<[? + 1]> {
// CHECK:           %[[FLAT_0:.*]] = amdgcn.flat.global_load <global_load_dword> %[[ARG0]], %[[ARG1]] : <[? + 1]>, !amdgcn.vgpr_range<[? + 2]> -> <[? + 1]>
// CHECK:           return %[[FLAT_0]] : !amdgcn.vgpr_range<[? + 1]>
// CHECK:         }
func.func @test_load_global_dword(%dst: !amdgcn.vgpr_range<[? + 1]>, %addr: !amdgcn.vgpr_range<[? + 2]>) -> !amdgcn.vgpr_range<[? + 1]> {
  %c0 = arith.constant 0 : i32
  %res, %token = pir.load #amdgcn.addr_space<global, read_only> %dst, %addr, %c0, %c0 : !amdgcn.vgpr_range<[? + 1]>, !amdgcn.vgpr_range<[? + 2]>, i32, i32
  return %res : !amdgcn.vgpr_range<[? + 1]>
}

// CHECK-LABEL:   func.func @test_load_global_dword_with_offset(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.vgpr_range<[? + 1]>, %[[ARG1:.*]]: !amdgcn.vgpr_range<[? + 2]>) -> !amdgcn.vgpr_range<[? + 1]> {
// CHECK:           %[[FLAT_0:.*]] = amdgcn.flat.global_load <global_load_dword> %[[ARG0]], %[[ARG1]], offset = 16 : <[? + 1]>, !amdgcn.vgpr_range<[? + 2]> -> <[? + 1]>
// CHECK:           return %[[FLAT_0]] : !amdgcn.vgpr_range<[? + 1]>
// CHECK:         }
func.func @test_load_global_dword_with_offset(%dst: !amdgcn.vgpr_range<[? + 1]>, %addr: !amdgcn.vgpr_range<[? + 2]>) -> !amdgcn.vgpr_range<[? + 1]> {
  %c0 = arith.constant 0 : i32
  %c16 = arith.constant 16 : i32
  %res, %token = pir.load #amdgcn.addr_space<global, read_only> %dst, %addr, %c0, %c16 : !amdgcn.vgpr_range<[? + 1]>, !amdgcn.vgpr_range<[? + 2]>, i32, i32
  return %res : !amdgcn.vgpr_range<[? + 1]>
}

// CHECK-LABEL:   func.func @test_load_global_dwordx2(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.vgpr_range<[? + 2]>, %[[ARG1:.*]]: !amdgcn.vgpr_range<[? + 2]>) -> !amdgcn.vgpr_range<[? + 2]> {
// CHECK:           %[[FLAT_0:.*]] = amdgcn.flat.global_load <global_load_dwordx2> %[[ARG0]], %[[ARG1]] : <[? + 2]>, !amdgcn.vgpr_range<[? + 2]> -> <[? + 2]>
// CHECK:           return %[[FLAT_0]] : !amdgcn.vgpr_range<[? + 2]>
// CHECK:         }
func.func @test_load_global_dwordx2(%dst: !amdgcn.vgpr_range<[? + 2]>, %addr: !amdgcn.vgpr_range<[? + 2]>) -> !amdgcn.vgpr_range<[? + 2]> {
  %c0 = arith.constant 0 : i32
  %res, %token = pir.load #amdgcn.addr_space<global, read_only> %dst, %addr, %c0, %c0 : !amdgcn.vgpr_range<[? + 2]>, !amdgcn.vgpr_range<[? + 2]>, i32, i32
  return %res : !amdgcn.vgpr_range<[? + 2]>
}

// CHECK-LABEL:   func.func @test_load_global_dwordx3(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.vgpr_range<[? + 3]>, %[[ARG1:.*]]: !amdgcn.vgpr_range<[? + 2]>) -> !amdgcn.vgpr_range<[? + 3]> {
// CHECK:           %[[FLAT_0:.*]] = amdgcn.flat.global_load <global_load_dwordx3> %[[ARG0]], %[[ARG1]] : <[? + 3]>, !amdgcn.vgpr_range<[? + 2]> -> <[? + 3]>
// CHECK:           return %[[FLAT_0]] : !amdgcn.vgpr_range<[? + 3]>
// CHECK:         }
func.func @test_load_global_dwordx3(%dst: !amdgcn.vgpr_range<[? + 3]>, %addr: !amdgcn.vgpr_range<[? + 2]>) -> !amdgcn.vgpr_range<[? + 3]> {
  %c0 = arith.constant 0 : i32
  %res, %token = pir.load #amdgcn.addr_space<global, read_only> %dst, %addr, %c0, %c0 : !amdgcn.vgpr_range<[? + 3]>, !amdgcn.vgpr_range<[? + 2]>, i32, i32
  return %res : !amdgcn.vgpr_range<[? + 3]>
}

// CHECK-LABEL:   func.func @test_load_global_dwordx4(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.vgpr_range<[? + 4]>, %[[ARG1:.*]]: !amdgcn.vgpr_range<[? + 2]>) -> !amdgcn.vgpr_range<[? + 4]> {
// CHECK:           %[[FLAT_0:.*]] = amdgcn.flat.global_load <global_load_dwordx4> %[[ARG0]], %[[ARG1]] : <[? + 4]>, !amdgcn.vgpr_range<[? + 2]> -> <[? + 4]>
// CHECK:           return %[[FLAT_0]] : !amdgcn.vgpr_range<[? + 4]>
// CHECK:         }
func.func @test_load_global_dwordx4(%dst: !amdgcn.vgpr_range<[? + 4]>, %addr: !amdgcn.vgpr_range<[? + 2]>) -> !amdgcn.vgpr_range<[? + 4]> {
  %c0 = arith.constant 0 : i32
  %res, %token = pir.load #amdgcn.addr_space<global, read_only> %dst, %addr, %c0, %c0 : !amdgcn.vgpr_range<[? + 4]>, !amdgcn.vgpr_range<[? + 2]>, i32, i32
  return %res : !amdgcn.vgpr_range<[? + 4]>
}

// CHECK-LABEL:   func.func @test_load_smem_dword(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.sgpr_range<[? + 1]>, %[[ARG1:.*]]: !amdgcn.sgpr_range<[? + 2]>) -> !amdgcn.sgpr_range<[? + 1]> {
// CHECK:           %[[SMEM_0:.*]] = amdgcn.smem.load <s_load_dword> %[[ARG0]], %[[ARG1]] : !amdgcn.sgpr_range<[? + 1]>, !amdgcn.sgpr_range<[? + 2]> -> !amdgcn.sgpr_range<[? + 1]>
// CHECK:           return %[[SMEM_0]] : !amdgcn.sgpr_range<[? + 1]>
// CHECK:         }
func.func @test_load_smem_dword(%dst: !amdgcn.sgpr_range<[? + 1]>, %addr: !amdgcn.sgpr_range<[? + 2]>) -> !amdgcn.sgpr_range<[? + 1]> {
  %c0 = arith.constant 0 : i32
  %res, %token = pir.load #amdgcn.addr_space<global, read_only> %dst, %addr, %c0, %c0 : !amdgcn.sgpr_range<[? + 1]>, !amdgcn.sgpr_range<[? + 2]>, i32, i32
  return %res : !amdgcn.sgpr_range<[? + 1]>
}

// CHECK-LABEL:   func.func @test_load_smem_dword_with_offset(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.sgpr_range<[? + 1]>, %[[ARG1:.*]]: !amdgcn.sgpr_range<[? + 2]>) -> !amdgcn.sgpr_range<[? + 1]> {
// CHECK:           %[[SMEM_0:.*]] = amdgcn.smem.load <s_load_dword> %[[ARG0]], %[[ARG1]] offset = 32 : !amdgcn.sgpr_range<[? + 1]>, !amdgcn.sgpr_range<[? + 2]> -> !amdgcn.sgpr_range<[? + 1]>
// CHECK:           return %[[SMEM_0]] : !amdgcn.sgpr_range<[? + 1]>
// CHECK:         }
func.func @test_load_smem_dword_with_offset(%dst: !amdgcn.sgpr_range<[? + 1]>, %addr: !amdgcn.sgpr_range<[? + 2]>) -> !amdgcn.sgpr_range<[? + 1]> {
  %c0 = arith.constant 0 : i32
  %c32 = arith.constant 32 : i32
  %res, %token = pir.load #amdgcn.addr_space<global, read_only> %dst, %addr, %c0, %c32 : !amdgcn.sgpr_range<[? + 1]>, !amdgcn.sgpr_range<[? + 2]>, i32, i32
  return %res : !amdgcn.sgpr_range<[? + 1]>
}

// CHECK-LABEL:   func.func @test_load_smem_dwordx2(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.sgpr_range<[? + 2]>, %[[ARG1:.*]]: !amdgcn.sgpr_range<[? + 2]>) -> !amdgcn.sgpr_range<[? + 2]> {
// CHECK:           %[[SMEM_0:.*]] = amdgcn.smem.load <s_load_dwordx2> %[[ARG0]], %[[ARG1]] : !amdgcn.sgpr_range<[? + 2]>, !amdgcn.sgpr_range<[? + 2]> -> !amdgcn.sgpr_range<[? + 2]>
// CHECK:           return %[[SMEM_0]] : !amdgcn.sgpr_range<[? + 2]>
// CHECK:         }
func.func @test_load_smem_dwordx2(%dst: !amdgcn.sgpr_range<[? + 2]>, %addr: !amdgcn.sgpr_range<[? + 2]>) -> !amdgcn.sgpr_range<[? + 2]> {
  %c0 = arith.constant 0 : i32
  %res, %token = pir.load #amdgcn.addr_space<global, read_only> %dst, %addr, %c0, %c0 : !amdgcn.sgpr_range<[? + 2]>, !amdgcn.sgpr_range<[? + 2]>, i32, i32
  return %res : !amdgcn.sgpr_range<[? + 2]>
}

// CHECK-LABEL:   func.func @test_load_smem_dwordx4(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.sgpr_range<[? + 4]>, %[[ARG1:.*]]: !amdgcn.sgpr_range<[? + 2]>) -> !amdgcn.sgpr_range<[? + 4]> {
// CHECK:           %[[SMEM_0:.*]] = amdgcn.smem.load <s_load_dwordx4> %[[ARG0]], %[[ARG1]] : !amdgcn.sgpr_range<[? + 4]>, !amdgcn.sgpr_range<[? + 2]> -> !amdgcn.sgpr_range<[? + 4]>
// CHECK:           return %[[SMEM_0]] : !amdgcn.sgpr_range<[? + 4]>
// CHECK:         }
func.func @test_load_smem_dwordx4(%dst: !amdgcn.sgpr_range<[? + 4]>, %addr: !amdgcn.sgpr_range<[? + 2]>) -> !amdgcn.sgpr_range<[? + 4]> {
  %c0 = arith.constant 0 : i32
  %res, %token = pir.load #amdgcn.addr_space<global, read_only> %dst, %addr, %c0, %c0 : !amdgcn.sgpr_range<[? + 4]>, !amdgcn.sgpr_range<[? + 2]>, i32, i32
  return %res : !amdgcn.sgpr_range<[? + 4]>
}

// CHECK-LABEL:   func.func @test_load_smem_dwordx8(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.sgpr_range<[? + 8]>, %[[ARG1:.*]]: !amdgcn.sgpr_range<[? + 2]>) -> !amdgcn.sgpr_range<[? + 8]> {
// CHECK:           %[[SMEM_0:.*]] = amdgcn.smem.load <s_load_dwordx8> %[[ARG0]], %[[ARG1]] : !amdgcn.sgpr_range<[? + 8]>, !amdgcn.sgpr_range<[? + 2]> -> !amdgcn.sgpr_range<[? + 8]>
// CHECK:           return %[[SMEM_0]] : !amdgcn.sgpr_range<[? + 8]>
// CHECK:         }
func.func @test_load_smem_dwordx8(%dst: !amdgcn.sgpr_range<[? + 8]>, %addr: !amdgcn.sgpr_range<[? + 2]>) -> !amdgcn.sgpr_range<[? + 8]> {
  %c0 = arith.constant 0 : i32
  %res, %token = pir.load #amdgcn.addr_space<global, read_only> %dst, %addr, %c0, %c0 : !amdgcn.sgpr_range<[? + 8]>, !amdgcn.sgpr_range<[? + 2]>, i32, i32
  return %res : !amdgcn.sgpr_range<[? + 8]>
}

// CHECK-LABEL:   func.func @test_load_smem_dwordx16(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.sgpr_range<[? + 16]>, %[[ARG1:.*]]: !amdgcn.sgpr_range<[? + 2]>) -> !amdgcn.sgpr_range<[? + 16]> {
// CHECK:           %[[SMEM_0:.*]] = amdgcn.smem.load <s_load_dwordx16> %[[ARG0]], %[[ARG1]] : !amdgcn.sgpr_range<[? + 16]>, !amdgcn.sgpr_range<[? + 2]> -> !amdgcn.sgpr_range<[? + 16]>
// CHECK:           return %[[SMEM_0]] : !amdgcn.sgpr_range<[? + 16]>
// CHECK:         }
func.func @test_load_smem_dwordx16(%dst: !amdgcn.sgpr_range<[? + 16]>, %addr: !amdgcn.sgpr_range<[? + 2]>) -> !amdgcn.sgpr_range<[? + 16]> {
  %c0 = arith.constant 0 : i32
  %res, %token = pir.load #amdgcn.addr_space<global, read_only> %dst, %addr, %c0, %c0 : !amdgcn.sgpr_range<[? + 16]>, !amdgcn.sgpr_range<[? + 2]>, i32, i32
  return %res : !amdgcn.sgpr_range<[? + 16]>
}

// CHECK-LABEL:   func.func @test_load_local_dword(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.vgpr_range<[? + 1]>, %[[ARG1:.*]]: !amdgcn.vgpr) -> !amdgcn.vgpr_range<[? + 1]> {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant 0 : i32
// CHECK:           %[[DS_0:.*]] = amdgcn.ds.read <ds_read_b32> %[[ARG0]], %[[ARG1]], offset = %[[CONSTANT_0]] : !amdgcn.vgpr, i32 -> <[? + 1]>
// CHECK:           return %[[DS_0]] : !amdgcn.vgpr_range<[? + 1]>
// CHECK:         }
func.func @test_load_local_dword(%dst: !amdgcn.vgpr_range<[? + 1]>, %addr: !amdgcn.vgpr) -> !amdgcn.vgpr_range<[? + 1]> {
  %c0 = arith.constant 0 : i32
  %res, %token = pir.load #amdgcn.addr_space<local, read_only> %dst, %addr, %c0, %c0 : !amdgcn.vgpr_range<[? + 1]>, !amdgcn.vgpr, i32, i32
  return %res : !amdgcn.vgpr_range<[? + 1]>
}

// CHECK-LABEL:   func.func @test_load_local_dword_with_offset(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.vgpr_range<[? + 1]>, %[[ARG1:.*]]: !amdgcn.vgpr) -> !amdgcn.vgpr_range<[? + 1]> {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant 64 : i32
// CHECK:           %[[DS_0:.*]] = amdgcn.ds.read <ds_read_b32> %[[ARG0]], %[[ARG1]], offset = %[[CONSTANT_0]] : !amdgcn.vgpr, i32 -> <[? + 1]>
// CHECK:           return %[[DS_0]] : !amdgcn.vgpr_range<[? + 1]>
// CHECK:         }
func.func @test_load_local_dword_with_offset(%dst: !amdgcn.vgpr_range<[? + 1]>, %addr: !amdgcn.vgpr) -> !amdgcn.vgpr_range<[? + 1]> {
  %c0 = arith.constant 0 : i32
  %c64 = arith.constant 64 : i32
  %res, %token = pir.load #amdgcn.addr_space<local, read_only> %dst, %addr, %c0, %c64 : !amdgcn.vgpr_range<[? + 1]>, !amdgcn.vgpr, i32, i32
  return %res : !amdgcn.vgpr_range<[? + 1]>
}

// CHECK-LABEL:   func.func @test_load_local_dwordx2(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.vgpr_range<[? + 2]>, %[[ARG1:.*]]: !amdgcn.vgpr) -> !amdgcn.vgpr_range<[? + 2]> {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant 0 : i32
// CHECK:           %[[DS_0:.*]] = amdgcn.ds.read <ds_read_b64> %[[ARG0]], %[[ARG1]], offset = %[[CONSTANT_0]] : !amdgcn.vgpr, i32 -> <[? + 2]>
// CHECK:           return %[[DS_0]] : !amdgcn.vgpr_range<[? + 2]>
// CHECK:         }
func.func @test_load_local_dwordx2(%dst: !amdgcn.vgpr_range<[? + 2]>, %addr: !amdgcn.vgpr) -> !amdgcn.vgpr_range<[? + 2]> {
  %c0 = arith.constant 0 : i32
  %res, %token = pir.load #amdgcn.addr_space<local, read_only> %dst, %addr, %c0, %c0 : !amdgcn.vgpr_range<[? + 2]>, !amdgcn.vgpr, i32, i32
  return %res : !amdgcn.vgpr_range<[? + 2]>
}

// CHECK-LABEL:   func.func @test_load_local_dwordx3(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.vgpr_range<[? + 3]>, %[[ARG1:.*]]: !amdgcn.vgpr) -> !amdgcn.vgpr_range<[? + 3]> {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant 0 : i32
// CHECK:           %[[DS_0:.*]] = amdgcn.ds.read <ds_read_b96> %[[ARG0]], %[[ARG1]], offset = %[[CONSTANT_0]] : !amdgcn.vgpr, i32 -> <[? + 3]>
// CHECK:           return %[[DS_0]] : !amdgcn.vgpr_range<[? + 3]>
// CHECK:         }
func.func @test_load_local_dwordx3(%dst: !amdgcn.vgpr_range<[? + 3]>, %addr: !amdgcn.vgpr) -> !amdgcn.vgpr_range<[? + 3]> {
  %c0 = arith.constant 0 : i32
  %res, %token = pir.load #amdgcn.addr_space<local, read_only> %dst, %addr, %c0, %c0 : !amdgcn.vgpr_range<[? + 3]>, !amdgcn.vgpr, i32, i32
  return %res : !amdgcn.vgpr_range<[? + 3]>
}

// CHECK-LABEL:   func.func @test_load_local_dwordx4(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.vgpr_range<[? + 4]>, %[[ARG1:.*]]: !amdgcn.vgpr) -> !amdgcn.vgpr_range<[? + 4]> {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant 0 : i32
// CHECK:           %[[DS_0:.*]] = amdgcn.ds.read <ds_read_b128> %[[ARG0]], %[[ARG1]], offset = %[[CONSTANT_0]] : !amdgcn.vgpr, i32 -> <[? + 4]>
// CHECK:           return %[[DS_0]] : !amdgcn.vgpr_range<[? + 4]>
// CHECK:         }
func.func @test_load_local_dwordx4(%dst: !amdgcn.vgpr_range<[? + 4]>, %addr: !amdgcn.vgpr) -> !amdgcn.vgpr_range<[? + 4]> {
  %c0 = arith.constant 0 : i32
  %res, %token = pir.load #amdgcn.addr_space<local, read_only> %dst, %addr, %c0, %c0 : !amdgcn.vgpr_range<[? + 4]>, !amdgcn.vgpr, i32, i32
  return %res : !amdgcn.vgpr_range<[? + 4]>
}

// CHECK-LABEL:   func.func @test_store_global_dword(
// CHECK-SAME:      %[[DATA:.*]]: !amdgcn.vgpr_range<[? + 1]>, %[[ADDR:.*]]: !amdgcn.vgpr_range<[? + 2]>) {
// CHECK:           amdgcn.flat.global_store <global_store_dword> %[[DATA]], %[[ADDR]]
// CHECK:           return
// CHECK:         }
func.func @test_store_global_dword(%data: !amdgcn.vgpr_range<[? + 1]>, %addr: !amdgcn.vgpr_range<[? + 2]>) {
  %c0 = arith.constant 0 : i32
  %token = pir.store #amdgcn.addr_space<global, read_write> %data, %addr, %c0, %c0 : !amdgcn.vgpr_range<[? + 1]>, !amdgcn.vgpr_range<[? + 2]>, i32, i32
  return
}

// CHECK-LABEL:   func.func @test_store_global_dword_with_offset(
// CHECK-SAME:      %[[DATA:.*]]: !amdgcn.vgpr_range<[? + 1]>, %[[ADDR:.*]]: !amdgcn.vgpr_range<[? + 2]>) {
// CHECK:           amdgcn.flat.global_store <global_store_dword> %[[DATA]], %[[ADDR]], offset = 16
// CHECK:           return
// CHECK:         }
func.func @test_store_global_dword_with_offset(%data: !amdgcn.vgpr_range<[? + 1]>, %addr: !amdgcn.vgpr_range<[? + 2]>) {
  %c0 = arith.constant 0 : i32
  %c16 = arith.constant 16 : i32
  %token = pir.store #amdgcn.addr_space<global, read_write> %data, %addr, %c0, %c16 : !amdgcn.vgpr_range<[? + 1]>, !amdgcn.vgpr_range<[? + 2]>, i32, i32
  return
}

// CHECK-LABEL:   func.func @test_store_global_dwordx2(
// CHECK-SAME:      %[[DATA:.*]]: !amdgcn.vgpr_range<[? + 2]>, %[[ADDR:.*]]: !amdgcn.vgpr_range<[? + 2]>) {
// CHECK:           amdgcn.flat.global_store <global_store_dwordx2> %[[DATA]], %[[ADDR]]
// CHECK:           return
// CHECK:         }
func.func @test_store_global_dwordx2(%data: !amdgcn.vgpr_range<[? + 2]>, %addr: !amdgcn.vgpr_range<[? + 2]>) {
  %c0 = arith.constant 0 : i32
  %token = pir.store #amdgcn.addr_space<global, read_write> %data, %addr, %c0, %c0 : !amdgcn.vgpr_range<[? + 2]>, !amdgcn.vgpr_range<[? + 2]>, i32, i32
  return
}

// CHECK-LABEL:   func.func @test_store_global_dwordx3(
// CHECK-SAME:      %[[DATA:.*]]: !amdgcn.vgpr_range<[? + 3]>, %[[ADDR:.*]]: !amdgcn.vgpr_range<[? + 2]>) {
// CHECK:           amdgcn.flat.global_store <global_store_dwordx3> %[[DATA]], %[[ADDR]]
// CHECK:           return
// CHECK:         }
func.func @test_store_global_dwordx3(%data: !amdgcn.vgpr_range<[? + 3]>, %addr: !amdgcn.vgpr_range<[? + 2]>) {
  %c0 = arith.constant 0 : i32
  %token = pir.store #amdgcn.addr_space<global, read_write> %data, %addr, %c0, %c0 : !amdgcn.vgpr_range<[? + 3]>, !amdgcn.vgpr_range<[? + 2]>, i32, i32
  return
}

// CHECK-LABEL:   func.func @test_store_global_dwordx4(
// CHECK-SAME:      %[[DATA:.*]]: !amdgcn.vgpr_range<[? + 4]>, %[[ADDR:.*]]: !amdgcn.vgpr_range<[? + 2]>) {
// CHECK:           amdgcn.flat.global_store <global_store_dwordx4> %[[DATA]], %[[ADDR]]
// CHECK:           return
// CHECK:         }
func.func @test_store_global_dwordx4(%data: !amdgcn.vgpr_range<[? + 4]>, %addr: !amdgcn.vgpr_range<[? + 2]>) {
  %c0 = arith.constant 0 : i32
  %token = pir.store #amdgcn.addr_space<global, read_write> %data, %addr, %c0, %c0 : !amdgcn.vgpr_range<[? + 4]>, !amdgcn.vgpr_range<[? + 2]>, i32, i32
  return
}

// CHECK-LABEL:   func.func @test_store_smem_dword(
// CHECK-SAME:      %[[DATA:.*]]: !amdgcn.sgpr_range<[? + 1]>, %[[ADDR:.*]]: !amdgcn.sgpr_range<[? + 2]>) {
// CHECK:           amdgcn.smem.store <s_store_dword> %[[DATA]], %[[ADDR]]
// CHECK:           return
// CHECK:         }
func.func @test_store_smem_dword(%data: !amdgcn.sgpr_range<[? + 1]>, %addr: !amdgcn.sgpr_range<[? + 2]>) {
  %c0 = arith.constant 0 : i32
  %token = pir.store #amdgcn.addr_space<global, read_write> %data, %addr, %c0, %c0 : !amdgcn.sgpr_range<[? + 1]>, !amdgcn.sgpr_range<[? + 2]>, i32, i32
  return
}

// CHECK-LABEL:   func.func @test_store_smem_dword_with_offset(
// CHECK-SAME:      %[[DATA:.*]]: !amdgcn.sgpr_range<[? + 1]>, %[[ADDR:.*]]: !amdgcn.sgpr_range<[? + 2]>) {
// CHECK:           amdgcn.smem.store <s_store_dword> %[[DATA]], %[[ADDR]], offset = 32
// CHECK:           return
// CHECK:         }
func.func @test_store_smem_dword_with_offset(%data: !amdgcn.sgpr_range<[? + 1]>, %addr: !amdgcn.sgpr_range<[? + 2]>) {
  %c0 = arith.constant 0 : i32
  %c32 = arith.constant 32 : i32
  %token = pir.store #amdgcn.addr_space<global, read_write> %data, %addr, %c0, %c32 : !amdgcn.sgpr_range<[? + 1]>, !amdgcn.sgpr_range<[? + 2]>, i32, i32
  return
}

// CHECK-LABEL:   func.func @test_store_smem_dwordx2(
// CHECK-SAME:      %[[DATA:.*]]: !amdgcn.sgpr_range<[? + 2]>, %[[ADDR:.*]]: !amdgcn.sgpr_range<[? + 2]>) {
// CHECK:           amdgcn.smem.store <s_store_dwordx2> %[[DATA]], %[[ADDR]]
// CHECK:           return
// CHECK:         }
func.func @test_store_smem_dwordx2(%data: !amdgcn.sgpr_range<[? + 2]>, %addr: !amdgcn.sgpr_range<[? + 2]>) {
  %c0 = arith.constant 0 : i32
  %token = pir.store #amdgcn.addr_space<global, read_write> %data, %addr, %c0, %c0 : !amdgcn.sgpr_range<[? + 2]>, !amdgcn.sgpr_range<[? + 2]>, i32, i32
  return
}

// CHECK-LABEL:   func.func @test_store_smem_dwordx4(
// CHECK-SAME:      %[[DATA:.*]]: !amdgcn.sgpr_range<[? + 4]>, %[[ADDR:.*]]: !amdgcn.sgpr_range<[? + 2]>) {
// CHECK:           amdgcn.smem.store <s_store_dwordx4> %[[DATA]], %[[ADDR]]
// CHECK:           return
// CHECK:         }
func.func @test_store_smem_dwordx4(%data: !amdgcn.sgpr_range<[? + 4]>, %addr: !amdgcn.sgpr_range<[? + 2]>) {
  %c0 = arith.constant 0 : i32
  %token = pir.store #amdgcn.addr_space<global, read_write> %data, %addr, %c0, %c0 : !amdgcn.sgpr_range<[? + 4]>, !amdgcn.sgpr_range<[? + 2]>, i32, i32
  return
}

// CHECK-LABEL:   func.func @test_store_local_dword(
// CHECK-SAME:      %[[DATA:.*]]: !amdgcn.vgpr_range<[? + 1]>, %[[ADDR:.*]]: !amdgcn.vgpr) {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant 0 : i32
// CHECK:           amdgcn.ds.write <ds_write_b32> %[[DATA]], %[[ADDR]], offset = %[[CONSTANT_0]]
// CHECK:           return
// CHECK:         }
func.func @test_store_local_dword(%data: !amdgcn.vgpr_range<[? + 1]>, %addr: !amdgcn.vgpr) {
  %c0 = arith.constant 0 : i32
  %token = pir.store #amdgcn.addr_space<local, read_write> %data, %addr, %c0, %c0 : !amdgcn.vgpr_range<[? + 1]>, !amdgcn.vgpr, i32, i32
  return
}

// CHECK-LABEL:   func.func @test_store_local_dword_with_offset(
// CHECK-SAME:      %[[DATA:.*]]: !amdgcn.vgpr_range<[? + 1]>, %[[ADDR:.*]]: !amdgcn.vgpr) {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant 64 : i32
// CHECK:           amdgcn.ds.write <ds_write_b32> %[[DATA]], %[[ADDR]], offset = %[[CONSTANT_0]]
// CHECK:           return
// CHECK:         }
func.func @test_store_local_dword_with_offset(%data: !amdgcn.vgpr_range<[? + 1]>, %addr: !amdgcn.vgpr) {
  %c0 = arith.constant 0 : i32
  %c64 = arith.constant 64 : i32
  %token = pir.store #amdgcn.addr_space<local, read_write> %data, %addr, %c0, %c64 : !amdgcn.vgpr_range<[? + 1]>, !amdgcn.vgpr, i32, i32
  return
}

// CHECK-LABEL:   func.func @test_store_local_dwordx2(
// CHECK-SAME:      %[[DATA:.*]]: !amdgcn.vgpr_range<[? + 2]>, %[[ADDR:.*]]: !amdgcn.vgpr) {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant 0 : i32
// CHECK:           amdgcn.ds.write <ds_write_b64> %[[DATA]], %[[ADDR]], offset = %[[CONSTANT_0]]
// CHECK:           return
// CHECK:         }
func.func @test_store_local_dwordx2(%data: !amdgcn.vgpr_range<[? + 2]>, %addr: !amdgcn.vgpr) {
  %c0 = arith.constant 0 : i32
  %token = pir.store #amdgcn.addr_space<local, read_write> %data, %addr, %c0, %c0 : !amdgcn.vgpr_range<[? + 2]>, !amdgcn.vgpr, i32, i32
  return
}

// CHECK-LABEL:   func.func @test_store_local_dwordx3(
// CHECK-SAME:      %[[DATA:.*]]: !amdgcn.vgpr_range<[? + 3]>, %[[ADDR:.*]]: !amdgcn.vgpr) {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant 0 : i32
// CHECK:           amdgcn.ds.write <ds_write_b96> %[[DATA]], %[[ADDR]], offset = %[[CONSTANT_0]]
// CHECK:           return
// CHECK:         }
func.func @test_store_local_dwordx3(%data: !amdgcn.vgpr_range<[? + 3]>, %addr: !amdgcn.vgpr) {
  %c0 = arith.constant 0 : i32
  %token = pir.store #amdgcn.addr_space<local, read_write> %data, %addr, %c0, %c0 : !amdgcn.vgpr_range<[? + 3]>, !amdgcn.vgpr, i32, i32
  return
}

// CHECK-LABEL:   func.func @test_store_local_dwordx4(
// CHECK-SAME:      %[[DATA:.*]]: !amdgcn.vgpr_range<[? + 4]>, %[[ADDR:.*]]: !amdgcn.vgpr) {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant 0 : i32
// CHECK:           amdgcn.ds.write <ds_write_b128> %[[DATA]], %[[ADDR]], offset = %[[CONSTANT_0]]
// CHECK:           return
// CHECK:         }
func.func @test_store_local_dwordx4(%data: !amdgcn.vgpr_range<[? + 4]>, %addr: !amdgcn.vgpr) {
  %c0 = arith.constant 0 : i32
  %token = pir.store #amdgcn.addr_space<local, read_write> %data, %addr, %c0, %c0 : !amdgcn.vgpr_range<[? + 4]>, !amdgcn.vgpr, i32, i32
  return
}

// CHECK-LABEL:   func.func @test_wait_single_vmem_load(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.vgpr_range<[? + 1]>, %[[ARG1:.*]]: !amdgcn.vgpr_range<[? + 2]>) -> !amdgcn.vgpr_range<[? + 1]> {
// CHECK:           %[[FLAT_0:.*]] = amdgcn.flat.global_load <global_load_dword> %[[ARG0]], %[[ARG1]] : <[? + 1]>, !amdgcn.vgpr_range<[? + 2]> -> <[? + 1]>
// CHECK:           amdgcn.sopp.s_waitcnt <s_waitcnt> vmcnt = 1
// CHECK:           return %[[FLAT_0]] : !amdgcn.vgpr_range<[? + 1]>
// CHECK:         }
func.func @test_wait_single_vmem_load(%dst: !amdgcn.vgpr_range<[? + 1]>, %addr: !amdgcn.vgpr_range<[? + 2]>) -> !amdgcn.vgpr_range<[? + 1]> {
  %c0 = arith.constant 0 : i32
  %res, %token = pir.load #amdgcn.addr_space<global, read_only> %dst, %addr, %c0, %c0 : !amdgcn.vgpr_range<[? + 1]>, !amdgcn.vgpr_range<[? + 2]>, i32, i32
  pir.wait %token : !pir.load_token
  return %res : !amdgcn.vgpr_range<[? + 1]>
}

// CHECK-LABEL:   func.func @test_wait_single_vmem_store(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.vgpr_range<[? + 1]>, %[[ARG1:.*]]: !amdgcn.vgpr_range<[? + 2]>) {
// CHECK:           amdgcn.flat.global_store <global_store_dword> %[[ARG0]], %[[ARG1]] : !amdgcn.vgpr_range<[? + 1]>, !amdgcn.vgpr_range<[? + 2]>
// CHECK:           amdgcn.sopp.s_waitcnt <s_waitcnt> vmcnt = 1
// CHECK:           return
// CHECK:         }
func.func @test_wait_single_vmem_store(%data: !amdgcn.vgpr_range<[? + 1]>, %addr: !amdgcn.vgpr_range<[? + 2]>) {
  %c0 = arith.constant 0 : i32
  %token = pir.store #amdgcn.addr_space<global, read_write> %data, %addr, %c0, %c0 : !amdgcn.vgpr_range<[? + 1]>, !amdgcn.vgpr_range<[? + 2]>, i32, i32
  pir.wait %token : !pir.store_token
  return
}

// CHECK-LABEL:   func.func @test_wait_single_smem_load(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.sgpr_range<[? + 1]>, %[[ARG1:.*]]: !amdgcn.sgpr_range<[? + 2]>) -> !amdgcn.sgpr_range<[? + 1]> {
// CHECK:           %[[SMEM_0:.*]] = amdgcn.smem.load <s_load_dword> %[[ARG0]], %[[ARG1]] : !amdgcn.sgpr_range<[? + 1]>, !amdgcn.sgpr_range<[? + 2]> -> !amdgcn.sgpr_range<[? + 1]>
// CHECK:           amdgcn.sopp.s_waitcnt <s_waitcnt> lgkmcnt = 1
// CHECK:           return %[[SMEM_0]] : !amdgcn.sgpr_range<[? + 1]>
// CHECK:         }
func.func @test_wait_single_smem_load(%dst: !amdgcn.sgpr_range<[? + 1]>, %addr: !amdgcn.sgpr_range<[? + 2]>) -> !amdgcn.sgpr_range<[? + 1]> {
  %c0 = arith.constant 0 : i32
  %res, %token = pir.load #amdgcn.addr_space<global, read_only> %dst, %addr, %c0, %c0 : !amdgcn.sgpr_range<[? + 1]>, !amdgcn.sgpr_range<[? + 2]>, i32, i32
  pir.wait %token : !pir.load_token
  return %res : !amdgcn.sgpr_range<[? + 1]>
}

// CHECK-LABEL:   func.func @test_wait_single_ds_load(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.vgpr_range<[? + 1]>, %[[ARG1:.*]]: !amdgcn.vgpr) -> !amdgcn.vgpr_range<[? + 1]> {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant 0 : i32
// CHECK:           %[[DS_0:.*]] = amdgcn.ds.read <ds_read_b32> %[[ARG0]], %[[ARG1]], offset = %[[CONSTANT_0]] : !amdgcn.vgpr, i32 -> <[? + 1]>
// CHECK:           amdgcn.sopp.s_waitcnt <s_waitcnt> lgkmcnt = 1
// CHECK:           return %[[DS_0]] : !amdgcn.vgpr_range<[? + 1]>
// CHECK:         }
func.func @test_wait_single_ds_load(%dst: !amdgcn.vgpr_range<[? + 1]>, %addr: !amdgcn.vgpr) -> !amdgcn.vgpr_range<[? + 1]> {
  %c0 = arith.constant 0 : i32
  %res, %token = pir.load #amdgcn.addr_space<local, read_only> %dst, %addr, %c0, %c0 : !amdgcn.vgpr_range<[? + 1]>, !amdgcn.vgpr, i32, i32
  pir.wait %token : !pir.load_token
  return %res : !amdgcn.vgpr_range<[? + 1]>
}

// CHECK-LABEL:   func.func @test_wait_single_ds_store(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.vgpr_range<[? + 1]>, %[[ARG1:.*]]: !amdgcn.vgpr) {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant 0 : i32
// CHECK:           amdgcn.ds.write <ds_write_b32> %[[ARG0]], %[[ARG1]], offset = %[[CONSTANT_0]] : <[? + 1]>, !amdgcn.vgpr, i32
// CHECK:           amdgcn.sopp.s_waitcnt <s_waitcnt> lgkmcnt = 1
// CHECK:           return
// CHECK:         }
func.func @test_wait_single_ds_store(%data: !amdgcn.vgpr_range<[? + 1]>, %addr: !amdgcn.vgpr) {
  %c0 = arith.constant 0 : i32
  %token = pir.store #amdgcn.addr_space<local, read_write> %data, %addr, %c0, %c0 : !amdgcn.vgpr_range<[? + 1]>, !amdgcn.vgpr, i32, i32
  pir.wait %token : !pir.store_token
  return
}

// CHECK-LABEL:   func.func @test_wait_multiple_vmem_loads(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.vgpr_range<[? + 1]>, %[[ARG1:.*]]: !amdgcn.vgpr_range<[? + 1]>, %[[ARG2:.*]]: !amdgcn.vgpr_range<[? + 2]>) -> (!amdgcn.vgpr_range<[? + 1]>, !amdgcn.vgpr_range<[? + 1]>) {
// CHECK:           %[[FLAT_0:.*]] = amdgcn.flat.global_load <global_load_dword> %[[ARG0]], %[[ARG2]] : <[? + 1]>, !amdgcn.vgpr_range<[? + 2]> -> <[? + 1]>
// CHECK:           %[[FLAT_1:.*]] = amdgcn.flat.global_load <global_load_dword> %[[ARG1]], %[[ARG2]], offset = 4 : <[? + 1]>, !amdgcn.vgpr_range<[? + 2]> -> <[? + 1]>
// CHECK:           amdgcn.sopp.s_waitcnt <s_waitcnt> vmcnt = 2
// CHECK:           return %[[FLAT_0]], %[[FLAT_1]] : !amdgcn.vgpr_range<[? + 1]>, !amdgcn.vgpr_range<[? + 1]>
// CHECK:         }
func.func @test_wait_multiple_vmem_loads(%dst0: !amdgcn.vgpr_range<[? + 1]>, %dst1: !amdgcn.vgpr_range<[? + 1]>, %addr: !amdgcn.vgpr_range<[? + 2]>) -> (!amdgcn.vgpr_range<[? + 1]>, !amdgcn.vgpr_range<[? + 1]>) {
  %c0 = arith.constant 0 : i32
  %c4 = arith.constant 4 : i32
  %res0, %token0 = pir.load #amdgcn.addr_space<global, read_only> %dst0, %addr, %c0, %c0 : !amdgcn.vgpr_range<[? + 1]>, !amdgcn.vgpr_range<[? + 2]>, i32, i32
  %res1, %token1 = pir.load #amdgcn.addr_space<global, read_only> %dst1, %addr, %c0, %c4 : !amdgcn.vgpr_range<[? + 1]>, !amdgcn.vgpr_range<[? + 2]>, i32, i32
  pir.wait %token0, %token1 : !pir.load_token, !pir.load_token
  return %res0, %res1 : !amdgcn.vgpr_range<[? + 1]>, !amdgcn.vgpr_range<[? + 1]>
}

// CHECK-LABEL:   func.func @test_wait_multiple_smem_loads(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.sgpr_range<[? + 1]>, %[[ARG1:.*]]: !amdgcn.sgpr_range<[? + 1]>, %[[ARG2:.*]]: !amdgcn.sgpr_range<[? + 2]>) -> (!amdgcn.sgpr_range<[? + 1]>, !amdgcn.sgpr_range<[? + 1]>) {
// CHECK:           %[[SMEM_0:.*]] = amdgcn.smem.load <s_load_dword> %[[ARG0]], %[[ARG2]] : !amdgcn.sgpr_range<[? + 1]>, !amdgcn.sgpr_range<[? + 2]> -> !amdgcn.sgpr_range<[? + 1]>
// CHECK:           %[[SMEM_1:.*]] = amdgcn.smem.load <s_load_dword> %[[ARG1]], %[[ARG2]] offset = 4 : !amdgcn.sgpr_range<[? + 1]>, !amdgcn.sgpr_range<[? + 2]> -> !amdgcn.sgpr_range<[? + 1]>
// CHECK:           amdgcn.sopp.s_waitcnt <s_waitcnt> lgkmcnt = 2
// CHECK:           return %[[SMEM_0]], %[[SMEM_1]] : !amdgcn.sgpr_range<[? + 1]>, !amdgcn.sgpr_range<[? + 1]>
// CHECK:         }
func.func @test_wait_multiple_smem_loads(%dst0: !amdgcn.sgpr_range<[? + 1]>, %dst1: !amdgcn.sgpr_range<[? + 1]>, %addr: !amdgcn.sgpr_range<[? + 2]>) -> (!amdgcn.sgpr_range<[? + 1]>, !amdgcn.sgpr_range<[? + 1]>) {
  %c0 = arith.constant 0 : i32
  %c4 = arith.constant 4 : i32
  %res0, %token0 = pir.load #amdgcn.addr_space<global, read_only> %dst0, %addr, %c0, %c0 : !amdgcn.sgpr_range<[? + 1]>, !amdgcn.sgpr_range<[? + 2]>, i32, i32
  %res1, %token1 = pir.load #amdgcn.addr_space<global, read_only> %dst1, %addr, %c0, %c4 : !amdgcn.sgpr_range<[? + 1]>, !amdgcn.sgpr_range<[? + 2]>, i32, i32
  pir.wait %token0, %token1 : !pir.load_token, !pir.load_token
  return %res0, %res1 : !amdgcn.sgpr_range<[? + 1]>, !amdgcn.sgpr_range<[? + 1]>
}

// CHECK-LABEL:   func.func @test_wait_mixed_vmem_and_smem(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.vgpr_range<[? + 1]>, %[[ARG1:.*]]: !amdgcn.sgpr_range<[? + 1]>, %[[ARG2:.*]]: !amdgcn.vgpr_range<[? + 2]>, %[[ARG3:.*]]: !amdgcn.sgpr_range<[? + 2]>) -> (!amdgcn.vgpr_range<[? + 1]>, !amdgcn.sgpr_range<[? + 1]>) {
// CHECK:           %[[FLAT_0:.*]] = amdgcn.flat.global_load <global_load_dword> %[[ARG0]], %[[ARG2]] : <[? + 1]>, !amdgcn.vgpr_range<[? + 2]> -> <[? + 1]>
// CHECK:           %[[SMEM_0:.*]] = amdgcn.smem.load <s_load_dword> %[[ARG1]], %[[ARG3]] : !amdgcn.sgpr_range<[? + 1]>, !amdgcn.sgpr_range<[? + 2]> -> !amdgcn.sgpr_range<[? + 1]>
// CHECK:           amdgcn.sopp.s_waitcnt <s_waitcnt> vmcnt = 1 lgkmcnt = 1
// CHECK:           return %[[FLAT_0]], %[[SMEM_0]] : !amdgcn.vgpr_range<[? + 1]>, !amdgcn.sgpr_range<[? + 1]>
// CHECK:         }
func.func @test_wait_mixed_vmem_and_smem(%vdst: !amdgcn.vgpr_range<[? + 1]>, %sdst: !amdgcn.sgpr_range<[? + 1]>, %vaddr: !amdgcn.vgpr_range<[? + 2]>, %saddr: !amdgcn.sgpr_range<[? + 2]>) -> (!amdgcn.vgpr_range<[? + 1]>, !amdgcn.sgpr_range<[? + 1]>) {
  %c0 = arith.constant 0 : i32
  %vres, %vtoken = pir.load #amdgcn.addr_space<global, read_only> %vdst, %vaddr, %c0, %c0 : !amdgcn.vgpr_range<[? + 1]>, !amdgcn.vgpr_range<[? + 2]>, i32, i32
  %sres, %stoken = pir.load #amdgcn.addr_space<global, read_only> %sdst, %saddr, %c0, %c0 : !amdgcn.sgpr_range<[? + 1]>, !amdgcn.sgpr_range<[? + 2]>, i32, i32
  pir.wait %vtoken, %stoken : !pir.load_token, !pir.load_token
  return %vres, %sres : !amdgcn.vgpr_range<[? + 1]>, !amdgcn.sgpr_range<[? + 1]>
}

// CHECK-LABEL:   func.func @test_wait_mixed_vmem_and_ds(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.vgpr_range<[? + 1]>, %[[ARG1:.*]]: !amdgcn.vgpr_range<[? + 1]>, %[[ARG2:.*]]: !amdgcn.vgpr_range<[? + 2]>, %[[ARG3:.*]]: !amdgcn.vgpr) -> (!amdgcn.vgpr_range<[? + 1]>, !amdgcn.vgpr_range<[? + 1]>) {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant 0 : i32
// CHECK:           %[[FLAT_0:.*]] = amdgcn.flat.global_load <global_load_dword> %[[ARG0]], %[[ARG2]] : <[? + 1]>, !amdgcn.vgpr_range<[? + 2]> -> <[? + 1]>
// CHECK:           %[[DS_0:.*]] = amdgcn.ds.read <ds_read_b32> %[[ARG1]], %[[ARG3]], offset = %[[CONSTANT_0]] : !amdgcn.vgpr, i32 -> <[? + 1]>
// CHECK:           amdgcn.sopp.s_waitcnt <s_waitcnt> vmcnt = 1 lgkmcnt = 1
// CHECK:           return %[[FLAT_0]], %[[DS_0]] : !amdgcn.vgpr_range<[? + 1]>, !amdgcn.vgpr_range<[? + 1]>
// CHECK:         }
func.func @test_wait_mixed_vmem_and_ds(%vdst: !amdgcn.vgpr_range<[? + 1]>, %ddst: !amdgcn.vgpr_range<[? + 1]>, %vaddr: !amdgcn.vgpr_range<[? + 2]>, %daddr: !amdgcn.vgpr) -> (!amdgcn.vgpr_range<[? + 1]>, !amdgcn.vgpr_range<[? + 1]>) {
  %c0 = arith.constant 0 : i32
  %vres, %vtoken = pir.load #amdgcn.addr_space<global, read_only> %vdst, %vaddr, %c0, %c0 : !amdgcn.vgpr_range<[? + 1]>, !amdgcn.vgpr_range<[? + 2]>, i32, i32
  %dres, %dtoken = pir.load #amdgcn.addr_space<local, read_only> %ddst, %daddr, %c0, %c0 : !amdgcn.vgpr_range<[? + 1]>, !amdgcn.vgpr, i32, i32
  pir.wait %vtoken, %dtoken : !pir.load_token, !pir.load_token
  return %vres, %dres : !amdgcn.vgpr_range<[? + 1]>, !amdgcn.vgpr_range<[? + 1]>
}

// CHECK-LABEL:   func.func @test_wait_load_and_store(
// CHECK-SAME:      %[[ARG0:.*]]: !amdgcn.vgpr_range<[? + 1]>, %[[ARG1:.*]]: !amdgcn.vgpr_range<[? + 1]>, %[[ARG2:.*]]: !amdgcn.vgpr_range<[? + 2]>, %[[ARG3:.*]]: !amdgcn.vgpr_range<[? + 2]>) -> !amdgcn.vgpr_range<[? + 1]> {
// CHECK:           %[[FLAT_0:.*]] = amdgcn.flat.global_load <global_load_dword> %[[ARG0]], %[[ARG2]] : <[? + 1]>, !amdgcn.vgpr_range<[? + 2]> -> <[? + 1]>
// CHECK:           amdgcn.flat.global_store <global_store_dword> %[[ARG1]], %[[ARG3]] : !amdgcn.vgpr_range<[? + 1]>, !amdgcn.vgpr_range<[? + 2]>
// CHECK:           amdgcn.sopp.s_waitcnt <s_waitcnt> vmcnt = 2
// CHECK:           return %[[FLAT_0]] : !amdgcn.vgpr_range<[? + 1]>
// CHECK:         }
func.func @test_wait_load_and_store(%dst: !amdgcn.vgpr_range<[? + 1]>, %data: !amdgcn.vgpr_range<[? + 1]>, %laddr: !amdgcn.vgpr_range<[? + 2]>, %saddr: !amdgcn.vgpr_range<[? + 2]>) -> !amdgcn.vgpr_range<[? + 1]> {
  %c0 = arith.constant 0 : i32
  %res, %ltoken = pir.load #amdgcn.addr_space<global, read_only> %dst, %laddr, %c0, %c0 : !amdgcn.vgpr_range<[? + 1]>, !amdgcn.vgpr_range<[? + 2]>, i32, i32
  %stoken = pir.store #amdgcn.addr_space<global, read_write> %data, %saddr, %c0, %c0 : !amdgcn.vgpr_range<[? + 1]>, !amdgcn.vgpr_range<[? + 2]>, i32, i32
  pir.wait %ltoken, %stoken : !pir.load_token, !pir.store_token
  return %res : !amdgcn.vgpr_range<[? + 1]>
}
