// RUN: aster-opt --amdgcn-to-register-semantics --split-input-file %s | FileCheck %s

// CHECK-LABEL:   func.func @range_amdgcn.allocations() {
// CHECK-DAG:       %[[ALLOCA_0:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK-DAG:       %[[ALLOCA_1:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK-DAG:       %[[ALLOCA_2:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK-DAG:       %[[ALLOCA_3:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK-DAG:       %[[ALLOCA_4:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK-DAG:       %[[ALLOCA_5:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK-DAG:       %[[ALLOCA_6:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:           lsir.copy %[[ALLOCA_6]], %[[ALLOCA_0]] : !amdgcn.vgpr<?>, !amdgcn.vgpr<?>
// CHECK:           amdgcn.test_inst outs %[[ALLOCA_0]] : (!amdgcn.vgpr<?>) -> ()
// CHECK-DAG:       %[[ALLOCA_7:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:           lsir.copy %[[ALLOCA_7]], %[[ALLOCA_1]] : !amdgcn.vgpr<?>, !amdgcn.vgpr<?>
// CHECK:           amdgcn.test_inst outs %[[ALLOCA_1]] : (!amdgcn.vgpr<?>) -> ()
// CHECK:           %[[MAKE_REGISTER_RANGE_0:.*]] = amdgcn.make_register_range %[[ALLOCA_6]], %[[ALLOCA_7]] : !amdgcn.vgpr<?>, !amdgcn.vgpr<?>
// CHECK:           %[[MAKE_REGISTER_RANGE_1:.*]] = amdgcn.make_register_range %[[ALLOCA_6]], %[[ALLOCA_7]], %[[ALLOCA_2]], %[[ALLOCA_3]] : !amdgcn.vgpr<?>, !amdgcn.vgpr<?>, !amdgcn.vgpr<?>, !amdgcn.vgpr<?>
// CHECK:           %[[MAKE_REGISTER_RANGE_2:.*]] = amdgcn.make_register_range %[[ALLOCA_4]], %[[ALLOCA_5]] : !amdgcn.vgpr<?>, !amdgcn.vgpr<?>
// CHECK:           amdgcn.test_inst outs %[[MAKE_REGISTER_RANGE_0]] ins %[[MAKE_REGISTER_RANGE_2]] : (!amdgcn.vgpr<[? : ? + 2]>, !amdgcn.vgpr<[? : ? + 2]>) -> ()
// CHECK:           amdgcn.test_inst ins %[[MAKE_REGISTER_RANGE_1]] : (!amdgcn.vgpr<[? : ? + 4]>) -> ()
// CHECK:           amdgcn.test_inst ins %[[ALLOCA_0]], %[[ALLOCA_1]] : (!amdgcn.vgpr<?>, !amdgcn.vgpr<?>) -> ()
// CHECK:           return
// CHECK:         }
func.func @range_amdgcn.allocations() {
  %0 = amdgcn.alloca : !amdgcn.vgpr
  %1 = amdgcn.alloca : !amdgcn.vgpr
  %2 = amdgcn.alloca : !amdgcn.vgpr
  %3 = amdgcn.alloca : !amdgcn.vgpr
  %4 = amdgcn.alloca : !amdgcn.vgpr
  %5 = amdgcn.alloca : !amdgcn.vgpr
  %6 = amdgcn.alloca : !amdgcn.vgpr
  %7 = lsir.copy %6, %0 : !amdgcn.vgpr, !amdgcn.vgpr
  %8 = amdgcn.test_inst outs %0 : (!amdgcn.vgpr) -> !amdgcn.vgpr
  %9 = amdgcn.alloca : !amdgcn.vgpr
  %10 = lsir.copy %9, %1 : !amdgcn.vgpr, !amdgcn.vgpr
  %11 = amdgcn.test_inst outs %1 : (!amdgcn.vgpr) -> !amdgcn.vgpr
  %12 = amdgcn.make_register_range %7, %10 : !amdgcn.vgpr, !amdgcn.vgpr
  %13 = amdgcn.make_register_range %7, %10, %2, %3 : !amdgcn.vgpr, !amdgcn.vgpr, !amdgcn.vgpr, !amdgcn.vgpr
  %14 = amdgcn.make_register_range %4, %5 : !amdgcn.vgpr, !amdgcn.vgpr
  %15 = amdgcn.test_inst outs %12 ins %14 : (!amdgcn.vgpr<[? + 2]>, !amdgcn.vgpr<[? + 2]>) -> !amdgcn.vgpr<[? + 2]>
  amdgcn.test_inst ins %13 : (!amdgcn.vgpr<[? + 4]>) -> ()
  amdgcn.test_inst ins %8, %11 : (!amdgcn.vgpr, !amdgcn.vgpr) -> ()
  func.return
}

// -----
// CHECK-LABEL:   func.func @no_interferencemixed_with_values() {
// CHECK-DAG:       %[[ALLOCA_0:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK-DAG:       %[[ALLOCA_1:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK-DAG:       %[[ALLOCA_2:.*]] = amdgcn.alloca : !amdgcn.sgpr<?>
// CHECK-DAG:       %[[ALLOCA_3:.*]] = amdgcn.alloca : !amdgcn.sgpr<?>
// CHECK:           amdgcn.test_inst outs %[[ALLOCA_2]] : (!amdgcn.sgpr<?>) -> ()
// CHECK:           amdgcn.test_inst outs %[[ALLOCA_3]] : (!amdgcn.sgpr<?>) -> ()
// CHECK:           amdgcn.test_inst outs %[[ALLOCA_0]] ins %[[ALLOCA_2]] : (!amdgcn.vgpr<?>, !amdgcn.sgpr<?>) -> ()
// CHECK:           amdgcn.test_inst outs %[[ALLOCA_1]] ins %[[ALLOCA_3]] : (!amdgcn.vgpr<?>, !amdgcn.sgpr<?>) -> ()
// CHECK:           return
// CHECK:         }
func.func @no_interferencemixed_with_values() {
  %0 = amdgcn.alloca : !amdgcn.vgpr
  %1 = amdgcn.alloca : !amdgcn.vgpr
  %2 = amdgcn.alloca : !amdgcn.sgpr
  %3 = amdgcn.alloca : !amdgcn.sgpr
  %4 = amdgcn.test_inst outs %2 : (!amdgcn.sgpr) -> !amdgcn.sgpr
  %5 = amdgcn.test_inst outs %3 : (!amdgcn.sgpr) -> !amdgcn.sgpr
  %6 = amdgcn.test_inst outs %0 ins %4 : (!amdgcn.vgpr, !amdgcn.sgpr) -> !amdgcn.vgpr
  %7 = amdgcn.test_inst outs %1 ins %5 : (!amdgcn.vgpr, !amdgcn.sgpr) -> !amdgcn.vgpr
  func.return
}

// -----
// CHECK-LABEL:   func.func @interference_mixed_with_reuse_with_values() {
// CHECK-DAG:       %[[ALLOCA_0:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK-DAG:       %[[ALLOCA_1:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK-DAG:       %[[ALLOCA_2:.*]] = amdgcn.alloca : !amdgcn.sgpr<?>
// CHECK-DAG:       %[[ALLOCA_3:.*]] = amdgcn.alloca : !amdgcn.sgpr<?>
// CHECK-DAG:       %[[ALLOCA_4:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK-DAG:       %[[ALLOCA_5:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK-DAG:       %[[ALLOCA_6:.*]] = amdgcn.alloca : !amdgcn.sgpr<?>
// CHECK:           lsir.copy %[[ALLOCA_6]], %[[ALLOCA_3]] : !amdgcn.sgpr<?>, !amdgcn.sgpr<?>
// CHECK:           amdgcn.test_inst outs %[[ALLOCA_2]], %[[ALLOCA_3]] : (!amdgcn.sgpr<?>, !amdgcn.sgpr<?>) -> ()
// CHECK:           amdgcn.test_inst outs %[[ALLOCA_4]], %[[ALLOCA_5]] : (!amdgcn.vgpr<?>, !amdgcn.vgpr<?>) -> ()
// CHECK:           amdgcn.test_inst outs %[[ALLOCA_0]] ins %[[ALLOCA_2]], %[[ALLOCA_3]] : (!amdgcn.vgpr<?>, !amdgcn.sgpr<?>, !amdgcn.sgpr<?>) -> ()
// CHECK:           amdgcn.test_inst outs %[[ALLOCA_1]] ins %[[ALLOCA_6]], %[[ALLOCA_5]] : (!amdgcn.vgpr<?>, !amdgcn.sgpr<?>, !amdgcn.vgpr<?>) -> ()
// CHECK:           amdgcn.test_inst ins %[[ALLOCA_0]], %[[ALLOCA_1]] : (!amdgcn.vgpr<?>, !amdgcn.vgpr<?>) -> ()
// CHECK:           return
// CHECK:         }
func.func @interference_mixed_with_reuse_with_values() {
  %0 = amdgcn.alloca : !amdgcn.vgpr
  %1 = amdgcn.alloca : !amdgcn.vgpr
  %2 = amdgcn.alloca : !amdgcn.sgpr
  %3 = amdgcn.alloca : !amdgcn.sgpr
  %4 = amdgcn.alloca : !amdgcn.vgpr
  %5 = amdgcn.alloca : !amdgcn.vgpr
  %6 = amdgcn.alloca : !amdgcn.sgpr
  %7 = lsir.copy %6, %3 : !amdgcn.sgpr, !amdgcn.sgpr
  %8:2 = amdgcn.test_inst outs %2, %3 : (!amdgcn.sgpr, !amdgcn.sgpr) -> (!amdgcn.sgpr, !amdgcn.sgpr)
  %9:2 = amdgcn.test_inst outs %4, %5 : (!amdgcn.vgpr, !amdgcn.vgpr) -> (!amdgcn.vgpr, !amdgcn.vgpr)
  %10 = amdgcn.test_inst outs %0 ins %8#0, %8#1 : (!amdgcn.vgpr, !amdgcn.sgpr, !amdgcn.sgpr) -> !amdgcn.vgpr
  %11 = amdgcn.test_inst outs %1 ins %7, %9#1 : (!amdgcn.vgpr, !amdgcn.sgpr, !amdgcn.vgpr) -> !amdgcn.vgpr
  amdgcn.test_inst ins %10, %11 : (!amdgcn.vgpr, !amdgcn.vgpr) -> ()
  func.return
}

// -----
// CHECK-LABEL:   func.func @interference_mixed_all_live_undef_values() {
// CHECK-DAG:       %[[ALLOCA_0:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK-DAG:       %[[ALLOCA_1:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK-DAG:       %[[ALLOCA_2:.*]] = amdgcn.alloca : !amdgcn.sgpr<?>
// CHECK-DAG:       %[[ALLOCA_3:.*]] = amdgcn.alloca : !amdgcn.sgpr<?>
// CHECK-DAG:       %[[ALLOCA_4:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK-DAG:       %[[ALLOCA_5:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:           amdgcn.test_inst outs %[[ALLOCA_0]] ins %[[ALLOCA_2]], %[[ALLOCA_4]] : (!amdgcn.vgpr<?>, !amdgcn.sgpr<?>, !amdgcn.vgpr<?>) -> ()
// CHECK:           amdgcn.test_inst outs %[[ALLOCA_1]] ins %[[ALLOCA_3]], %[[ALLOCA_5]] : (!amdgcn.vgpr<?>, !amdgcn.sgpr<?>, !amdgcn.vgpr<?>) -> ()
// CHECK:           amdgcn.test_inst ins %[[ALLOCA_0]], %[[ALLOCA_1]], %[[ALLOCA_4]], %[[ALLOCA_5]] : (!amdgcn.vgpr<?>, !amdgcn.vgpr<?>, !amdgcn.vgpr<?>, !amdgcn.vgpr<?>) -> ()
// CHECK:           return
// CHECK:         }
func.func @interference_mixed_all_live_undef_values() {
  %0 = amdgcn.alloca : !amdgcn.vgpr
  %1 = amdgcn.alloca : !amdgcn.vgpr
  %2 = amdgcn.alloca : !amdgcn.sgpr
  %3 = amdgcn.alloca : !amdgcn.sgpr
  %4 = amdgcn.alloca : !amdgcn.vgpr
  %5 = amdgcn.alloca : !amdgcn.vgpr
  %6 = amdgcn.test_inst outs %0 ins %2, %4 : (!amdgcn.vgpr, !amdgcn.sgpr, !amdgcn.vgpr) -> !amdgcn.vgpr
  %7 = amdgcn.test_inst outs %1 ins %3, %5 : (!amdgcn.vgpr, !amdgcn.sgpr, !amdgcn.vgpr) -> !amdgcn.vgpr
  amdgcn.test_inst ins %6, %7, %4, %5 : (!amdgcn.vgpr, !amdgcn.vgpr, !amdgcn.vgpr, !amdgcn.vgpr) -> ()
  func.return
}

// -----
// CHECK-LABEL:   func.func @interference_mixed_all_live_with_values() {
// CHECK-DAG:       %[[ALLOCA_0:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK-DAG:       %[[ALLOCA_1:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK-DAG:       %[[ALLOCA_2:.*]] = amdgcn.alloca : !amdgcn.sgpr<?>
// CHECK-DAG:       %[[ALLOCA_3:.*]] = amdgcn.alloca : !amdgcn.sgpr<?>
// CHECK-DAG:       %[[ALLOCA_4:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK-DAG:       %[[ALLOCA_5:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:           amdgcn.test_inst outs %[[ALLOCA_2]], %[[ALLOCA_3]] : (!amdgcn.sgpr<?>, !amdgcn.sgpr<?>) -> ()
// CHECK:           amdgcn.test_inst outs %[[ALLOCA_4]], %[[ALLOCA_5]] : (!amdgcn.vgpr<?>, !amdgcn.vgpr<?>) -> ()
// CHECK:           amdgcn.test_inst outs %[[ALLOCA_0]] ins %[[ALLOCA_2]], %[[ALLOCA_4]] : (!amdgcn.vgpr<?>, !amdgcn.sgpr<?>, !amdgcn.vgpr<?>) -> ()
// CHECK:           amdgcn.test_inst outs %[[ALLOCA_1]] ins %[[ALLOCA_3]], %[[ALLOCA_5]] : (!amdgcn.vgpr<?>, !amdgcn.sgpr<?>, !amdgcn.vgpr<?>) -> ()
// CHECK:           amdgcn.test_inst ins %[[ALLOCA_0]], %[[ALLOCA_1]], %[[ALLOCA_4]], %[[ALLOCA_5]] : (!amdgcn.vgpr<?>, !amdgcn.vgpr<?>, !amdgcn.vgpr<?>, !amdgcn.vgpr<?>) -> ()
// CHECK:           return
// CHECK:         }
// CHECK:         func.func private @rand() -> i1
func.func @interference_mixed_all_live_with_values() {
  %0 = amdgcn.alloca : !amdgcn.vgpr
  %1 = amdgcn.alloca : !amdgcn.vgpr
  %2 = amdgcn.alloca : !amdgcn.sgpr
  %3 = amdgcn.alloca : !amdgcn.sgpr
  %4 = amdgcn.alloca : !amdgcn.vgpr
  %5 = amdgcn.alloca : !amdgcn.vgpr
  %6:2 = amdgcn.test_inst outs %2, %3 : (!amdgcn.sgpr, !amdgcn.sgpr) -> (!amdgcn.sgpr, !amdgcn.sgpr)
  %7:2 = amdgcn.test_inst outs %4, %5 : (!amdgcn.vgpr, !amdgcn.vgpr) -> (!amdgcn.vgpr, !amdgcn.vgpr)
  %8 = amdgcn.test_inst outs %0 ins %6#0, %7#0 : (!amdgcn.vgpr, !amdgcn.sgpr, !amdgcn.vgpr) -> !amdgcn.vgpr
  %9 = amdgcn.test_inst outs %1 ins %6#1, %7#1 : (!amdgcn.vgpr, !amdgcn.sgpr, !amdgcn.vgpr) -> !amdgcn.vgpr
  amdgcn.test_inst ins %8, %9, %7#0, %7#1 : (!amdgcn.vgpr, !amdgcn.vgpr, !amdgcn.vgpr, !amdgcn.vgpr) -> ()
  func.return
}

// -----
func.func private @rand() -> i1
// CHECK-LABEL:   func.func @no_interference_cf_with_values() {
// CHECK:           %[[VAL_0:.*]] = call @rand() : () -> i1
// CHECK-DAG:       %[[ALLOCA_0:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK-DAG:       %[[ALLOCA_1:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK-DAG:       %[[ALLOCA_2:.*]] = amdgcn.alloca : !amdgcn.sgpr<?>
// CHECK-DAG:       %[[ALLOCA_3:.*]] = amdgcn.alloca : !amdgcn.sgpr<?>
// CHECK-DAG:       %[[ALLOCA_4:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK-DAG:       %[[ALLOCA_5:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:           amdgcn.test_inst outs %[[ALLOCA_2]], %[[ALLOCA_3]] : (!amdgcn.sgpr<?>, !amdgcn.sgpr<?>) -> ()
// CHECK:           amdgcn.test_inst outs %[[ALLOCA_4]], %[[ALLOCA_5]] : (!amdgcn.vgpr<?>, !amdgcn.vgpr<?>) -> ()
// CHECK-DAG:       %[[ALLOCA_6:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:           lsir.copy %[[ALLOCA_6]], %[[ALLOCA_0]] : !amdgcn.vgpr<?>, !amdgcn.vgpr<?>
// CHECK:           amdgcn.test_inst outs %[[ALLOCA_0]] ins %[[ALLOCA_2]], %[[ALLOCA_4]] : (!amdgcn.vgpr<?>, !amdgcn.sgpr<?>, !amdgcn.vgpr<?>) -> ()
// CHECK-DAG:       %[[ALLOCA_7:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:           lsir.copy %[[ALLOCA_7]], %[[ALLOCA_1]] : !amdgcn.vgpr<?>, !amdgcn.vgpr<?>
// CHECK:           amdgcn.test_inst outs %[[ALLOCA_1]] ins %[[ALLOCA_3]], %[[ALLOCA_5]] : (!amdgcn.vgpr<?>, !amdgcn.sgpr<?>, !amdgcn.vgpr<?>) -> ()
// CHECK:           cf.cond_br %[[VAL_0]], ^bb1, ^bb2
// CHECK:         ^bb1:
// CHECK:           amdgcn.test_inst outs %[[ALLOCA_7]] ins %[[ALLOCA_0]], %[[ALLOCA_4]] : (!amdgcn.vgpr<?>, !amdgcn.vgpr<?>, !amdgcn.vgpr<?>) -> ()
// CHECK:           cf.br ^bb3
// CHECK:         ^bb2:
// CHECK:           amdgcn.test_inst outs %[[ALLOCA_6]] ins %[[ALLOCA_1]], %[[ALLOCA_5]] : (!amdgcn.vgpr<?>, !amdgcn.vgpr<?>, !amdgcn.vgpr<?>) -> ()
// CHECK:           cf.br ^bb3
// CHECK:         ^bb3:
// CHECK:           return
// CHECK:         }
// CHECK:         func.func private @rand() -> i1
func.func @no_interference_cf_with_values() {
  %0 = func.call @rand() : () -> i1
  %1 = amdgcn.alloca : !amdgcn.vgpr
  %2 = amdgcn.alloca : !amdgcn.vgpr
  %3 = amdgcn.alloca : !amdgcn.sgpr
  %4 = amdgcn.alloca : !amdgcn.sgpr
  %5 = amdgcn.alloca : !amdgcn.vgpr
  %6 = amdgcn.alloca : !amdgcn.vgpr
  %7:2 = amdgcn.test_inst outs %3, %4 : (!amdgcn.sgpr, !amdgcn.sgpr) -> (!amdgcn.sgpr, !amdgcn.sgpr)
  %8:2 = amdgcn.test_inst outs %5, %6 : (!amdgcn.vgpr, !amdgcn.vgpr) -> (!amdgcn.vgpr, !amdgcn.vgpr)
  %9 = amdgcn.alloca : !amdgcn.vgpr
  %10 = lsir.copy %9, %1 : !amdgcn.vgpr, !amdgcn.vgpr
  %11 = amdgcn.test_inst outs %1 ins %7#0, %8#0 : (!amdgcn.vgpr, !amdgcn.sgpr, !amdgcn.vgpr) -> !amdgcn.vgpr
  %12 = amdgcn.alloca : !amdgcn.vgpr
  %13 = lsir.copy %12, %2 : !amdgcn.vgpr, !amdgcn.vgpr
  %14 = amdgcn.test_inst outs %2 ins %7#1, %8#1 : (!amdgcn.vgpr, !amdgcn.sgpr, !amdgcn.vgpr) -> !amdgcn.vgpr
  cf.cond_br %0, ^bb1, ^bb2
^bb1:  // pred: ^bb0
  %15 = amdgcn.test_inst outs %13 ins %11, %8#0 : (!amdgcn.vgpr, !amdgcn.vgpr, !amdgcn.vgpr) -> !amdgcn.vgpr
  cf.br ^bb3
^bb2:  // pred: ^bb0
  %16 = amdgcn.test_inst outs %10 ins %14, %8#1 : (!amdgcn.vgpr, !amdgcn.vgpr, !amdgcn.vgpr) -> !amdgcn.vgpr
  cf.br ^bb3
^bb3:  // 2 preds: ^bb1, ^bb2
  func.return
}

// -----
func.func private @rand() -> i1
// CHECK-LABEL:   func.func @interference_cf_with_values() {
// CHECK:           %[[VAL_0:.*]] = call @rand() : () -> i1
// CHECK-DAG:       %[[ALLOCA_0:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK-DAG:       %[[ALLOCA_1:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK-DAG:       %[[ALLOCA_2:.*]] = amdgcn.alloca : !amdgcn.sgpr<?>
// CHECK-DAG:       %[[ALLOCA_3:.*]] = amdgcn.alloca : !amdgcn.sgpr<?>
// CHECK-DAG:       %[[ALLOCA_4:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK-DAG:       %[[ALLOCA_5:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:           amdgcn.test_inst outs %[[ALLOCA_0]] ins %[[ALLOCA_2]] : (!amdgcn.vgpr<?>, !amdgcn.sgpr<?>) -> ()
// CHECK:           amdgcn.test_inst outs %[[ALLOCA_1]] ins %[[ALLOCA_3]] : (!amdgcn.vgpr<?>, !amdgcn.sgpr<?>) -> ()
// CHECK:           cf.cond_br %[[VAL_0]], ^bb1, ^bb2
// CHECK:         ^bb1:
// CHECK:           amdgcn.test_inst outs %[[ALLOCA_4]] ins %[[ALLOCA_0]] : (!amdgcn.vgpr<?>, !amdgcn.vgpr<?>) -> ()
// CHECK:           cf.br ^bb3
// CHECK:         ^bb2:
// CHECK:           amdgcn.test_inst outs %[[ALLOCA_5]] ins %[[ALLOCA_1]] : (!amdgcn.vgpr<?>, !amdgcn.vgpr<?>) -> ()
// CHECK:           cf.br ^bb3
// CHECK:         ^bb3:
// CHECK:           amdgcn.test_inst ins %[[ALLOCA_4]], %[[ALLOCA_5]] : (!amdgcn.vgpr<?>, !amdgcn.vgpr<?>) -> ()
// CHECK:           return
// CHECK:         }
func.func @interference_cf_with_values() {
  %0 = func.call @rand() : () -> i1
  %1 = amdgcn.alloca : !amdgcn.vgpr
  %2 = amdgcn.alloca : !amdgcn.vgpr
  %3 = amdgcn.alloca : !amdgcn.sgpr
  %4 = amdgcn.alloca : !amdgcn.sgpr
  %5 = amdgcn.alloca : !amdgcn.vgpr
  %6 = amdgcn.alloca : !amdgcn.vgpr
  %7 = amdgcn.test_inst outs %1 ins %3 : (!amdgcn.vgpr, !amdgcn.sgpr) -> !amdgcn.vgpr
  %8 = amdgcn.test_inst outs %2 ins %4 : (!amdgcn.vgpr, !amdgcn.sgpr) -> !amdgcn.vgpr
  cf.cond_br %0, ^bb1, ^bb2
^bb1:  // pred: ^bb0
  %9 = amdgcn.test_inst outs %5 ins %7 : (!amdgcn.vgpr, !amdgcn.vgpr) -> !amdgcn.vgpr
  cf.br ^bb3
^bb2:  // pred: ^bb0
  %10 = amdgcn.test_inst outs %6 ins %8 : (!amdgcn.vgpr, !amdgcn.vgpr) -> !amdgcn.vgpr
  cf.br ^bb3
^bb3:  // 2 preds: ^bb1, ^bb2
  amdgcn.test_inst ins %5, %6 : (!amdgcn.vgpr, !amdgcn.vgpr) -> ()
  func.return
}

// -----
// CHECK-LABEL:   func.func @existing_regs_with_values() {
// CHECK-DAG:       %[[ALLOCA_0:.*]] = amdgcn.alloca : !amdgcn.vgpr<0>
// CHECK-DAG:       %[[ALLOCA_1:.*]] = amdgcn.alloca : !amdgcn.vgpr<1>
// CHECK-DAG:       %[[ALLOCA_2:.*]] = amdgcn.alloca : !amdgcn.sgpr<0>
// CHECK-DAG:       %[[ALLOCA_3:.*]] = amdgcn.alloca : !amdgcn.sgpr<2>
// CHECK-DAG:       %[[ALLOCA_4:.*]] = amdgcn.alloca : !amdgcn.sgpr<5>
// CHECK-DAG:       %[[ALLOCA_5:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK-DAG:       %[[ALLOCA_6:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK-DAG:       %[[ALLOCA_7:.*]] = amdgcn.alloca : !amdgcn.sgpr<?>
// CHECK-DAG:       %[[ALLOCA_8:.*]] = amdgcn.alloca : !amdgcn.sgpr<?>
// CHECK-DAG:       %[[ALLOCA_9:.*]] = amdgcn.alloca : !amdgcn.sgpr<?>
// CHECK-DAG:       %[[ALLOCA_10:.*]] = amdgcn.alloca : !amdgcn.sgpr<?>
// CHECK-DAG:       %[[ALLOCA_11:.*]] = amdgcn.alloca : !amdgcn.sgpr<?>
// CHECK-DAG:       %[[ALLOCA_12:.*]] = amdgcn.alloca : !amdgcn.sgpr<?>
// CHECK:           amdgcn.test_inst outs %[[ALLOCA_2]], %[[ALLOCA_3]] : (!amdgcn.sgpr<0>, !amdgcn.sgpr<2>) -> ()
// CHECK:           amdgcn.test_inst outs %[[ALLOCA_5]], %[[ALLOCA_6]] : (!amdgcn.vgpr<?>, !amdgcn.vgpr<?>) -> ()
// CHECK:           amdgcn.test_inst outs %[[ALLOCA_7]], %[[ALLOCA_8]] : (!amdgcn.sgpr<?>, !amdgcn.sgpr<?>) -> ()
// CHECK:           amdgcn.test_inst outs %[[ALLOCA_9]], %[[ALLOCA_10]] : (!amdgcn.sgpr<?>, !amdgcn.sgpr<?>) -> ()
// CHECK:           amdgcn.test_inst outs %[[ALLOCA_11]], %[[ALLOCA_12]] : (!amdgcn.sgpr<?>, !amdgcn.sgpr<?>) -> ()
// CHECK:           amdgcn.test_inst outs %[[ALLOCA_0]] ins %[[ALLOCA_2]], %[[ALLOCA_5]] : (!amdgcn.vgpr<0>, !amdgcn.sgpr<0>, !amdgcn.vgpr<?>) -> ()
// CHECK:           amdgcn.test_inst outs %[[ALLOCA_1]] ins %[[ALLOCA_3]], %[[ALLOCA_6]] : (!amdgcn.vgpr<1>, !amdgcn.sgpr<2>, !amdgcn.vgpr<?>) -> ()
// CHECK:           %[[MAKE_REGISTER_RANGE_0:.*]] = amdgcn.make_register_range %[[ALLOCA_9]], %[[ALLOCA_10]], %[[ALLOCA_11]], %[[ALLOCA_12]] : !amdgcn.sgpr<?>, !amdgcn.sgpr<?>, !amdgcn.sgpr<?>, !amdgcn.sgpr<?>
// CHECK:           amdgcn.test_inst ins %[[ALLOCA_0]], %[[ALLOCA_1]], %[[ALLOCA_7]], %[[ALLOCA_8]], %[[ALLOCA_4]], %[[ALLOCA_5]], %[[ALLOCA_6]], %[[ALLOCA_2]], %[[ALLOCA_3]], %[[MAKE_REGISTER_RANGE_0]] : (!amdgcn.vgpr<0>, !amdgcn.vgpr<1>, !amdgcn.sgpr<?>, !amdgcn.sgpr<?>, !amdgcn.sgpr<5>, !amdgcn.vgpr<?>, !amdgcn.vgpr<?>, !amdgcn.sgpr<0>, !amdgcn.sgpr<2>, !amdgcn.sgpr<[? : ? + 4]>) -> ()
// CHECK:           return
// CHECK:         }
func.func @existing_regs_with_values() {
  %0 = amdgcn.alloca : !amdgcn.vgpr<0>
  %1 = amdgcn.alloca : !amdgcn.vgpr<1>
  %2 = amdgcn.alloca : !amdgcn.sgpr<0>
  %3 = amdgcn.alloca : !amdgcn.sgpr<2>
  %4 = amdgcn.alloca : !amdgcn.sgpr<5>
  %5 = amdgcn.alloca : !amdgcn.vgpr
  %6 = amdgcn.alloca : !amdgcn.vgpr
  %7 = amdgcn.alloca : !amdgcn.sgpr
  %8 = amdgcn.alloca : !amdgcn.sgpr
  %9 = amdgcn.alloca : !amdgcn.sgpr
  %10 = amdgcn.alloca : !amdgcn.sgpr
  %11 = amdgcn.alloca : !amdgcn.sgpr
  %12 = amdgcn.alloca : !amdgcn.sgpr
  amdgcn.test_inst outs %2, %3 : (!amdgcn.sgpr<0>, !amdgcn.sgpr<2>) -> ()
  %14:2 = amdgcn.test_inst outs %5, %6 : (!amdgcn.vgpr, !amdgcn.vgpr) -> (!amdgcn.vgpr, !amdgcn.vgpr)
  %15:2 = amdgcn.test_inst outs %7, %8 : (!amdgcn.sgpr, !amdgcn.sgpr) -> (!amdgcn.sgpr, !amdgcn.sgpr)
  %16:2 = amdgcn.test_inst outs %9, %10 : (!amdgcn.sgpr, !amdgcn.sgpr) -> (!amdgcn.sgpr, !amdgcn.sgpr)
  %17:2 = amdgcn.test_inst outs %11, %12 : (!amdgcn.sgpr, !amdgcn.sgpr) -> (!amdgcn.sgpr, !amdgcn.sgpr)
  amdgcn.test_inst outs %0 ins %2, %14#0 : (!amdgcn.vgpr<0>, !amdgcn.sgpr<0>, !amdgcn.vgpr) -> ()
  amdgcn.test_inst outs %1 ins %3, %14#1 : (!amdgcn.vgpr<1>, !amdgcn.sgpr<2>, !amdgcn.vgpr) -> ()
  %20 = amdgcn.make_register_range %16#0, %16#1, %17#0, %17#1 : !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr
  amdgcn.test_inst ins %0, %1, %15#0, %15#1, %4, %14#0, %14#1, %2, %3, %20 : (!amdgcn.vgpr<0>, !amdgcn.vgpr<1>, !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr<5>, !amdgcn.vgpr, !amdgcn.vgpr, !amdgcn.sgpr<0>, !amdgcn.sgpr<2>, !amdgcn.sgpr<[? + 4]>) -> ()
  func.return
}

// -----
// CHECK-LABEL:   func.func @reg_interference_with_values() {
// CHECK-DAG:       %[[ALLOCA_0:.*]] = amdgcn.alloca : !amdgcn.sgpr<?>
// CHECK-DAG:       %[[ALLOCA_1:.*]] = amdgcn.alloca : !amdgcn.sgpr<?>
// CHECK:           amdgcn.test_inst outs %[[ALLOCA_0]], %[[ALLOCA_1]] : (!amdgcn.sgpr<?>, !amdgcn.sgpr<?>) -> ()
// CHECK:           amdgcn.test_inst ins %[[ALLOCA_0]], %[[ALLOCA_1]] : (!amdgcn.sgpr<?>, !amdgcn.sgpr<?>) -> ()
// CHECK-DAG:       %[[ALLOCA_2:.*]] = amdgcn.alloca : !amdgcn.sgpr<?>
// CHECK-DAG:       %[[ALLOCA_3:.*]] = amdgcn.alloca : !amdgcn.sgpr<?>
// CHECK:           amdgcn.test_inst outs %[[ALLOCA_2]], %[[ALLOCA_3]] : (!amdgcn.sgpr<?>, !amdgcn.sgpr<?>) -> ()
// CHECK:           amdgcn.test_inst ins %[[ALLOCA_1]], %[[ALLOCA_2]] : (!amdgcn.sgpr<?>, !amdgcn.sgpr<?>) -> ()
// CHECK:           amdgcn.reg_interference %[[ALLOCA_0]], %[[ALLOCA_2]], %[[ALLOCA_3]] : !amdgcn.sgpr<?>, !amdgcn.sgpr<?>, !amdgcn.sgpr<?>
// CHECK-DAG:       %[[ALLOCA_4:.*]] = amdgcn.alloca : !amdgcn.sgpr<?>
// CHECK-DAG:       %[[ALLOCA_5:.*]] = amdgcn.alloca : !amdgcn.sgpr<?>
// CHECK:           amdgcn.test_inst outs %[[ALLOCA_4]], %[[ALLOCA_5]] : (!amdgcn.sgpr<?>, !amdgcn.sgpr<?>) -> ()
// CHECK:           amdgcn.test_inst ins %[[ALLOCA_4]], %[[ALLOCA_5]] : (!amdgcn.sgpr<?>, !amdgcn.sgpr<?>) -> ()
// CHECK-DAG:       %[[ALLOCA_6:.*]] = amdgcn.alloca : !amdgcn.sgpr<?>
// CHECK-DAG:       %[[ALLOCA_7:.*]] = amdgcn.alloca : !amdgcn.sgpr<?>
// CHECK:           amdgcn.test_inst outs %[[ALLOCA_6]], %[[ALLOCA_7]] : (!amdgcn.sgpr<?>, !amdgcn.sgpr<?>) -> ()
// CHECK:           amdgcn.test_inst ins %[[ALLOCA_6]], %[[ALLOCA_7]] : (!amdgcn.sgpr<?>, !amdgcn.sgpr<?>) -> ()
// CHECK:           amdgcn.reg_interference %[[ALLOCA_4]], %[[ALLOCA_1]], %[[ALLOCA_3]], %[[ALLOCA_7]] : !amdgcn.sgpr<?>, !amdgcn.sgpr<?>, !amdgcn.sgpr<?>, !amdgcn.sgpr<?>
// CHECK:           amdgcn.test_inst ins %[[ALLOCA_0]], %[[ALLOCA_5]] : (!amdgcn.sgpr<?>, !amdgcn.sgpr<?>) -> ()
// CHECK:           return
// CHECK:         }
func.func @reg_interference_with_values() {
  %0 = amdgcn.alloca : !amdgcn.sgpr
  %1 = amdgcn.alloca : !amdgcn.sgpr
  %2:2 = amdgcn.test_inst outs %0, %1 : (!amdgcn.sgpr, !amdgcn.sgpr) -> (!amdgcn.sgpr, !amdgcn.sgpr)
  amdgcn.test_inst ins %2#0, %2#1 : (!amdgcn.sgpr, !amdgcn.sgpr) -> ()
  %3 = amdgcn.alloca : !amdgcn.sgpr
  %4 = amdgcn.alloca : !amdgcn.sgpr
  %5:2 = amdgcn.test_inst outs %3, %4 : (!amdgcn.sgpr, !amdgcn.sgpr) -> (!amdgcn.sgpr, !amdgcn.sgpr)
  amdgcn.test_inst ins %2#1, %5#0 : (!amdgcn.sgpr, !amdgcn.sgpr) -> ()
  amdgcn.reg_interference %2#0, %5#0, %5#1 : !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr
  %6 = amdgcn.alloca : !amdgcn.sgpr
  %7 = amdgcn.alloca : !amdgcn.sgpr
  %8:2 = amdgcn.test_inst outs %6, %7 : (!amdgcn.sgpr, !amdgcn.sgpr) -> (!amdgcn.sgpr, !amdgcn.sgpr)
  amdgcn.test_inst ins %8#0, %8#1 : (!amdgcn.sgpr, !amdgcn.sgpr) -> ()
  %9 = amdgcn.alloca : !amdgcn.sgpr
  %10 = amdgcn.alloca : !amdgcn.sgpr
  %11:2 = amdgcn.test_inst outs %9, %10 : (!amdgcn.sgpr, !amdgcn.sgpr) -> (!amdgcn.sgpr, !amdgcn.sgpr)
  amdgcn.test_inst ins %11#0, %11#1 : (!amdgcn.sgpr, !amdgcn.sgpr) -> ()
  amdgcn.reg_interference %8#0, %2#1, %5#1, %11#1 : !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr
  amdgcn.test_inst ins %2#0, %8#1 : (!amdgcn.sgpr, !amdgcn.sgpr) -> ()
  func.return
}

// -----
// CHECK-LABEL:   func.func @test_index_bxmxnxk() {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant 42 : i32
// CHECK-DAG:       %[[ALLOCA_0:.*]] = amdgcn.alloca : !amdgcn.sgpr<2>
// CHECK-DAG:       %[[ALLOCA_1:.*]] = amdgcn.alloca : !amdgcn.sgpr<0>
// CHECK-DAG:       %[[ALLOCA_2:.*]] = amdgcn.alloca : !amdgcn.sgpr<1>
// CHECK:           %[[MAKE_REGISTER_RANGE_0:.*]] = amdgcn.make_register_range %[[ALLOCA_1]], %[[ALLOCA_2]] : !amdgcn.sgpr<0>, !amdgcn.sgpr<1>
// CHECK:           %[[ALLOCA_3:.*]] = amdgcn.alloca : !amdgcn.sgpr<?>
// CHECK:           %{{.*}} = amdgcn.s_load_dword dest %[[ALLOCA_3]] addr %[[MAKE_REGISTER_RANGE_0]] offset c(%[[CONSTANT_0]]) : outs(!amdgcn.sgpr<?>) ins(!amdgcn.sgpr<[0 : 2]>) mods(i32) -> !amdgcn.read_token<constant>
// CHECK:           amdgcn.s_waitcnt vmcnt = 0 expcnt = 0 lgkmcnt = 0
// CHECK:           %[[ALLOCA_4:.*]] = amdgcn.alloca : !amdgcn.sgpr<?>
// CHECK:           %[[SCC_ALLOCA:.*]] = amdgcn.alloca : !amdgcn.scc<0>
// CHECK:           amdgcn.s_and_b32 outs(%[[ALLOCA_4]], %[[SCC_ALLOCA]]) ins(%[[ALLOCA_3]], %[[CONSTANT_0]]) : outs(!amdgcn.sgpr<?>, !amdgcn.scc<0>) ins(!amdgcn.sgpr<?>, i32)
// CHECK:           %[[ALLOCA_5:.*]] = amdgcn.alloca : !amdgcn.sgpr<?>
// CHECK:           %[[ALLOCA_6:.*]] = amdgcn.alloca : !amdgcn.sgpr<?>
// CHECK:           %[[MAKE_REGISTER_RANGE_1:.*]] = amdgcn.make_register_range %[[ALLOCA_5]], %[[ALLOCA_6]] : !amdgcn.sgpr<?>, !amdgcn.sgpr<?>
// CHECK:           %{{.*}} = amdgcn.s_load_dwordx2 dest %[[MAKE_REGISTER_RANGE_1]] addr %[[MAKE_REGISTER_RANGE_0]] offset c(%[[CONSTANT_0]]) : outs(!amdgcn.sgpr<[? : ? + 2]>) ins(!amdgcn.sgpr<[0 : 2]>) mods(i32) -> !amdgcn.read_token<constant>
// CHECK:           amdgcn.test_inst ins %[[ALLOCA_0]], %[[ALLOCA_4]] : (!amdgcn.sgpr<2>, !amdgcn.sgpr<?>) -> ()
// CHECK:           return
// CHECK:         }
func.func @test_index_bxmxnxk() {
  %c42_i32 = arith.constant 42 : i32
  %0 = amdgcn.alloca : !amdgcn.sgpr<2>
  %1 = amdgcn.alloca : !amdgcn.sgpr<0>
  %2 = amdgcn.alloca : !amdgcn.sgpr<1>
  %3 = amdgcn.make_register_range %1, %2 : !amdgcn.sgpr<0>, !amdgcn.sgpr<1>
  %4 = amdgcn.alloca : !amdgcn.sgpr
  %result, %token = amdgcn.s_load_dword dest %4 addr %3 offset c(%c42_i32) : outs(!amdgcn.sgpr) ins(!amdgcn.sgpr<[0 : 2]>) mods(i32) -> !amdgcn.read_token<constant>
  amdgcn.s_waitcnt vmcnt = 0 expcnt = 0 lgkmcnt = 0
  %5 = amdgcn.alloca : !amdgcn.sgpr
  %_scc_dst_and_b32 = amdgcn.alloca : !amdgcn.scc<0>
  %6 = amdgcn.s_and_b32 outs(%5, %_scc_dst_and_b32) ins(%result, %c42_i32) : outs(!amdgcn.sgpr, !amdgcn.scc<0>) ins(!amdgcn.sgpr, i32)
  %7 = amdgcn.alloca : !amdgcn.sgpr
  %8 = amdgcn.alloca : !amdgcn.sgpr
  %9 = amdgcn.make_register_range %7, %8 : !amdgcn.sgpr, !amdgcn.sgpr
  %result_0, %token_1 = amdgcn.s_load_dwordx2 dest %9 addr %3 offset c(%c42_i32) : outs(!amdgcn.sgpr<[? + 2]>) ins(!amdgcn.sgpr<[0 : 2]>) mods(i32) -> !amdgcn.read_token<constant>
  amdgcn.test_inst ins %0, %6 : (!amdgcn.sgpr<2>, !amdgcn.sgpr) -> ()
  func.return
}

// -----
func.func private @rand() -> i1
// CHECK-LABEL:   func.func @split_range() {
// CHECK:           %[[VAL_0:.*]] = call @rand() : () -> i1
// CHECK-DAG:       %[[ALLOCA_0:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK-DAG:       %[[ALLOCA_1:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK-DAG:       %[[ALLOCA_2:.*]] = amdgcn.alloca : !amdgcn.sgpr<?>
// CHECK-DAG:       %[[ALLOCA_3:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK-DAG:       %[[ALLOCA_4:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:           %[[MAKE_REGISTER_RANGE_0:.*]] = amdgcn.make_register_range %[[ALLOCA_0]], %[[ALLOCA_1]] : !amdgcn.vgpr<?>, !amdgcn.vgpr<?>
// CHECK:           amdgcn.test_inst outs %[[ALLOCA_1]] ins %[[ALLOCA_2]] : (!amdgcn.vgpr<?>, !amdgcn.sgpr<?>) -> ()
// CHECK:           cf.cond_br %[[VAL_0]], ^bb1, ^bb2
// CHECK:         ^bb1:
// CHECK:           amdgcn.test_inst outs %[[ALLOCA_3]] ins %[[MAKE_REGISTER_RANGE_0]] : (!amdgcn.vgpr<?>, !amdgcn.vgpr<[? : ? + 2]>) -> ()
// CHECK:           cf.br ^bb3
// CHECK:         ^bb2:
// CHECK:           amdgcn.test_inst outs %[[ALLOCA_4]] ins %[[ALLOCA_1]] : (!amdgcn.vgpr<?>, !amdgcn.vgpr<?>) -> ()
// CHECK:           cf.br ^bb3
// CHECK:         ^bb3:
// CHECK:           amdgcn.test_inst ins %[[ALLOCA_3]], %[[ALLOCA_4]], %[[ALLOCA_0]], %[[ALLOCA_1]] : (!amdgcn.vgpr<?>, !amdgcn.vgpr<?>, !amdgcn.vgpr<?>, !amdgcn.vgpr<?>) -> ()
// CHECK:           return
// CHECK:         }
func.func @split_range() {
  %0 = func.call @rand() : () -> i1
  %1 = amdgcn.alloca : !amdgcn.vgpr
  %2 = amdgcn.alloca : !amdgcn.vgpr
  %3 = amdgcn.alloca : !amdgcn.sgpr
  %4 = amdgcn.alloca : !amdgcn.sgpr
  %5 = amdgcn.alloca : !amdgcn.vgpr
  %6 = amdgcn.alloca : !amdgcn.vgpr
  %7 = amdgcn.make_register_range %1, %2 : !amdgcn.vgpr, !amdgcn.vgpr
  %8 = amdgcn.test_inst outs %2 ins %4 : (!amdgcn.vgpr, !amdgcn.sgpr) -> !amdgcn.vgpr
  cf.cond_br %0, ^bb1, ^bb2
^bb1:  // pred: ^bb0
  %9 = amdgcn.test_inst outs %5 ins %7 : (!amdgcn.vgpr, !amdgcn.vgpr<[? + 2]>) -> !amdgcn.vgpr
  cf.br ^bb3
^bb2:  // pred: ^bb0
  %10 = amdgcn.test_inst outs %6 ins %8 : (!amdgcn.vgpr, !amdgcn.vgpr) -> !amdgcn.vgpr
  cf.br ^bb3
^bb3:  // 2 preds: ^bb1, ^bb2
  %11, %12 = amdgcn.split_register_range %7 : !amdgcn.vgpr<[? + 2]>
  amdgcn.test_inst ins %5, %6, %11, %12 : (!amdgcn.vgpr, !amdgcn.vgpr, !amdgcn.vgpr, !amdgcn.vgpr) -> ()
  func.return
}

// -----

// CHECK-LABEL:   func.func @dealloc() -> !amdgcn.vgpr {
// CHECK-DAG:       %[[ALLOCA_0:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:           %[[UNREALIZED_CONVERSION_CAST_0:.*]] = builtin.unrealized_conversion_cast %[[ALLOCA_0]] : !amdgcn.vgpr<?> to !amdgcn.vgpr {__to_register_semantics__}
// CHECK:           return %[[UNREALIZED_CONVERSION_CAST_0]] : !amdgcn.vgpr
// CHECK:         }
func.func @dealloc() -> !amdgcn.vgpr {
  %a = amdgcn.alloca : !amdgcn.vgpr<?>
  %r = amdgcn.dealloc_cast %a : !amdgcn.vgpr<?>
  return %r : !amdgcn.vgpr
}

// -----

// CHECK-LABEL:   func.func @special_reg_alloca_to_allocated() {
// CHECK-DAG:       %[[SCC:.*]] = amdgcn.alloca : !amdgcn.scc<0>
// CHECK-DAG:       %[[VCC_LO:.*]] = amdgcn.alloca : !amdgcn.vcc_lo<0>
// CHECK-DAG:       %[[VCC_HI:.*]] = amdgcn.alloca : !amdgcn.vcc_hi<0>
// CHECK:           %[[VCC:.*]] = amdgcn.make_register_range %[[VCC_LO]], %[[VCC_HI]] : !amdgcn.vcc_lo<0>, !amdgcn.vcc_hi<0>
// CHECK-DAG:       %[[SGPR:.*]] = amdgcn.alloca : !amdgcn.sgpr<?>
// CHECK:           amdgcn.test_inst outs %[[SGPR]] : (!amdgcn.sgpr<?>) -> ()
// CHECK:           amdgcn.test_inst ins %[[SCC]], %[[VCC]], %[[SGPR]] : (!amdgcn.scc<0>, !amdgcn.vcc<0>, !amdgcn.sgpr<?>) -> ()
// CHECK:           return
// CHECK:         }
func.func @special_reg_alloca_to_allocated() {
  %0 = amdgcn.alloca : !amdgcn.scc
  %1 = amdgcn.alloca : !amdgcn.vcc_lo
  %2 = amdgcn.alloca : !amdgcn.vcc_hi
  %3 = amdgcn.make_register_range %1, %2 : !amdgcn.vcc_lo, !amdgcn.vcc_hi
  %4 = amdgcn.alloca : !amdgcn.sgpr
  %5 = amdgcn.test_inst outs %4 : (!amdgcn.sgpr) -> !amdgcn.sgpr
  amdgcn.test_inst ins %0, %3, %5 : (!amdgcn.scc, !amdgcn.vcc, !amdgcn.sgpr) -> ()
  func.return
}

// -----

// CHECK-LABEL:   func.func @global_load_out_trailing_token() {
// CHECK:           %[[DST:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:           %[[TOK:.*]] = amdgcn.global_load_b32 dest %[[DST]] {{.*}} -> !amdgcn.read_token<flat>
// CHECK:           amdgcn.test_inst ins %[[DST]] : (!amdgcn.vgpr<?>) -> ()
// CHECK:           amdgcn.wait_gfx1250 deps %[[TOK]]
// CHECK:           return
func.func @global_load_out_trailing_token() {
  %dst = amdgcn.alloca : !amdgcn.vgpr
  %a0 = amdgcn.alloca : !amdgcn.sgpr
  %a1 = amdgcn.alloca : !amdgcn.sgpr
  %addr = amdgcn.make_register_range %a0, %a1 : !amdgcn.sgpr, !amdgcn.sgpr
  %voff = amdgcn.alloca : !amdgcn.vgpr
  %c0 = arith.constant 0 : i32
  %result, %tok = amdgcn.global_load_b32 dest %dst addr %addr offset d(%voff) + c(%c0) : outs(!amdgcn.vgpr) ins(!amdgcn.sgpr<[? + 2]>, !amdgcn.vgpr) mods(i32) -> !amdgcn.read_token<flat>
  amdgcn.test_inst ins %result : (!amdgcn.vgpr) -> ()
  %f = amdgcn.wait_gfx1250 deps %tok : !amdgcn.read_token<flat> -> !amdgcn.fence_token
  func.return
}

// -----

// CHECK-LABEL:   func.func @cluster_load_async_trailing_token() {
// CHECK:           %[[LDS:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:           amdgcn.test_inst outs %[[LDS]] : (!amdgcn.vgpr<?>) -> ()
// CHECK:           %[[TOK:.*]] = amdgcn.cluster_load_async_to_lds_b128 lds_dest %[[LDS]]
// CHECK:           amdgcn.wait_gfx1250 deps %[[TOK]]
// CHECK:           return
func.func @cluster_load_async_trailing_token() {
  %c0 = arith.constant 0 : i32
  %mask = arith.constant 15 : i32
  %m0 = amdgcn.alloca : !amdgcn.m0<0>
  amdgcn.s_mov_b32 outs(%m0) ins(%mask) : outs(!amdgcn.m0<0>) ins(i32)

  %lds_a = amdgcn.alloca : !amdgcn.vgpr
  %lds_dest = amdgcn.test_inst outs %lds_a : (!amdgcn.vgpr) -> !amdgcn.vgpr

  %a0 = amdgcn.alloca : !amdgcn.vgpr
  %a1 = amdgcn.alloca : !amdgcn.vgpr
  %addr = amdgcn.make_register_range %a0, %a1 : !amdgcn.vgpr, !amdgcn.vgpr

  %tok = amdgcn.cluster_load_async_to_lds_b128 lds_dest %lds_dest addr %addr m0 %m0 offset c(%c0)
           : ins(!amdgcn.vgpr, !amdgcn.vgpr<[? + 2]>, !amdgcn.m0<0>) mods(i32) -> !amdgcn.read_token<async>
  %f = amdgcn.wait_gfx1250 deps %tok : !amdgcn.read_token<async> -> !amdgcn.fence_token
  func.return
}

// -----

// CHECK-LABEL:   func.func @tensor_load_to_lds_trailing_token() {
// CHECK:           %[[DESC0_0:.*]] = amdgcn.alloca : !amdgcn.sgpr<?>
// CHECK:           amdgcn.test_inst outs %[[DESC0_0]] : (!amdgcn.sgpr<?>) -> ()
// CHECK:           %[[DESC0:.*]] = amdgcn.make_register_range %[[DESC0_0]],
// CHECK:           %[[TOK:.*]] = amdgcn.tensor_load_to_lds desc0 %[[DESC0]]
// CHECK:           amdgcn.wait_gfx1250 deps %[[TOK]]
// CHECK:           return
func.func @tensor_load_to_lds_trailing_token() {
  %s0 = amdgcn.alloca : !amdgcn.sgpr
  %d0e = amdgcn.test_inst outs %s0 : (!amdgcn.sgpr) -> !amdgcn.sgpr
  %s1 = amdgcn.alloca : !amdgcn.sgpr
  %s2 = amdgcn.alloca : !amdgcn.sgpr
  %s3 = amdgcn.alloca : !amdgcn.sgpr
  %desc0 = amdgcn.make_register_range %d0e, %s1, %s2, %s3 : !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr

  %e0 = amdgcn.alloca : !amdgcn.sgpr
  %e1 = amdgcn.alloca : !amdgcn.sgpr
  %e2 = amdgcn.alloca : !amdgcn.sgpr
  %e3 = amdgcn.alloca : !amdgcn.sgpr
  %e4 = amdgcn.alloca : !amdgcn.sgpr
  %e5 = amdgcn.alloca : !amdgcn.sgpr
  %e6 = amdgcn.alloca : !amdgcn.sgpr
  %e7 = amdgcn.alloca : !amdgcn.sgpr
  %desc1 = amdgcn.make_register_range %e0, %e1, %e2, %e3, %e4, %e5, %e6, %e7 : !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr

  %g0 = amdgcn.alloca : !amdgcn.sgpr
  %g1 = amdgcn.alloca : !amdgcn.sgpr
  %g2 = amdgcn.alloca : !amdgcn.sgpr
  %g3 = amdgcn.alloca : !amdgcn.sgpr
  %desc2 = amdgcn.make_register_range %g0, %g1, %g2, %g3 : !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr

  %h0 = amdgcn.alloca : !amdgcn.sgpr
  %h1 = amdgcn.alloca : !amdgcn.sgpr
  %h2 = amdgcn.alloca : !amdgcn.sgpr
  %h3 = amdgcn.alloca : !amdgcn.sgpr
  %desc3 = amdgcn.make_register_range %h0, %h1, %h2, %h3 : !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr, !amdgcn.sgpr

  %tok = amdgcn.tensor_load_to_lds desc0 %desc0 desc1 %desc1 desc2 %desc2 desc3 %desc3
      : ins(!amdgcn.sgpr<[? + 4]>, !amdgcn.sgpr<[? + 8]>, !amdgcn.sgpr<[? + 4]>, !amdgcn.sgpr<[? + 4]>) -> !amdgcn.read_token<tensor>
  %f = amdgcn.wait_gfx1250 deps %tok : !amdgcn.read_token<tensor> -> !amdgcn.fence_token
  func.return
}
