// RUN: aster-opt %s --pass-pipeline="builtin.module(amdgcn.module(amdgcn-wait-insertion))" | FileCheck %s

amdgcn.module @test_wait_insertion target = #amdgcn.target<gfx942> {

// CHECK-LABEL:   func.func @simple_load_store() {
// CHECK:           %[[ALLOCA_0:.*]] = memref.alloca() : memref<!amdgcn.read_token<flat>>
// CHECK:           %[[ALLOCA_1:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:           %[[ALLOCA_2:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:           %[[MAKE_REGISTER_RANGE_0:.*]] = amdgcn.make_register_range %[[ALLOCA_1]], %[[ALLOCA_2]] : !amdgcn.vgpr<?>, !amdgcn.vgpr<?>
// CHECK:           %[[ALLOCA_3:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:           %[[LOAD_0:.*]] = amdgcn.global_load_dword dest %[[ALLOCA_3]] addr %[[MAKE_REGISTER_RANGE_0]] offset c(%{{.*}}) : outs(!amdgcn.vgpr<?>) ins(!amdgcn.vgpr<[? : ? + 2]>) mods(i32) -> !amdgcn.read_token<flat>
// CHECK:           memref.store %[[LOAD_0]], %[[ALLOCA_0]][] : memref<!amdgcn.read_token<flat>>
// CHECK:           %[[LOAD_1:.*]] = memref.load %[[ALLOCA_0]][] : memref<!amdgcn.read_token<flat>>
// CHECK:           amdgcn.wait deps %[[LOAD_1]] : !amdgcn.read_token<flat> -> !amdgcn.fence_token
// CHECK:           %[[STORE_0:.*]] = amdgcn.global_store_dword data %[[ALLOCA_3]] addr %[[MAKE_REGISTER_RANGE_0]] offset c(%{{.*}}) : ins(!amdgcn.vgpr<?>, !amdgcn.vgpr<[? : ? + 2]>) mods(i32) -> !amdgcn.write_token<flat>
// CHECK:           return
// CHECK:         }
func.func @simple_load_store() {
  %0 = amdgcn.alloca : !amdgcn.vgpr<?>
  %1 = amdgcn.alloca : !amdgcn.vgpr<?>
  %2 = amdgcn.make_register_range %0, %1 : !amdgcn.vgpr<?>, !amdgcn.vgpr<?>
  %3 = amdgcn.alloca : !amdgcn.vgpr<?>
  %c0_i32_mig1 = arith.constant 0 : i32
  %token = amdgcn.global_load_dword dest %3 addr %2 offset c(%c0_i32_mig1) : outs(!amdgcn.vgpr<?>) ins(!amdgcn.vgpr<[? : ? + 2]>) mods(i32) -> !amdgcn.read_token<flat>
  %4 = amdgcn.global_store_dword data %3 addr %2 offset c(%c0_i32_mig1) : ins(!amdgcn.vgpr<?>, !amdgcn.vgpr<[? : ? + 2]>) mods(i32) -> !amdgcn.write_token<flat>
  return
}

// CHECK-LABEL:   func.func @load_then_vop() {
// CHECK:           %[[ALLOCA_0:.*]] = memref.alloca() : memref<!amdgcn.read_token<flat>>
// CHECK:           %[[ALLOCA_1:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:           %[[ALLOCA_2:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:           %[[ALLOCA_3:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:           %[[ALLOCA_4:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:           %[[MAKE_REGISTER_RANGE_0:.*]] = amdgcn.make_register_range %[[ALLOCA_3]], %[[ALLOCA_4]] : !amdgcn.vgpr<?>, !amdgcn.vgpr<?>
// CHECK:           %[[LOAD_0:.*]] = amdgcn.global_load_dword dest %[[ALLOCA_1]] addr %[[MAKE_REGISTER_RANGE_0]] offset c(%{{.*}}) : outs(!amdgcn.vgpr<?>) ins(!amdgcn.vgpr<[? : ? + 2]>) mods(i32) -> !amdgcn.read_token<flat>
// CHECK:           memref.store %[[LOAD_0]], %[[ALLOCA_0]][] : memref<!amdgcn.read_token<flat>>
// CHECK:           %[[LOAD_1:.*]] = memref.load %[[ALLOCA_0]][] : memref<!amdgcn.read_token<flat>>
// CHECK:           amdgcn.wait deps %[[LOAD_1]] : !amdgcn.read_token<flat> -> !amdgcn.fence_token
// CHECK:           amdgcn.v_mov_b32 outs(%[[ALLOCA_2]]) ins(%[[ALLOCA_1]]) : outs(!amdgcn.vgpr<?>) ins(!amdgcn.vgpr<?>)
// CHECK:           amdgcn.test_inst ins %[[ALLOCA_2]] : (!amdgcn.vgpr<?>) -> ()
// CHECK:           return
// CHECK:         }
func.func @load_then_vop() {
  %0 = amdgcn.alloca : !amdgcn.vgpr<?>
  %1 = amdgcn.alloca : !amdgcn.vgpr<?>
  %2 = amdgcn.alloca : !amdgcn.vgpr<?>
  %3 = amdgcn.alloca : !amdgcn.vgpr<?>
  %4 = amdgcn.make_register_range %2, %3 : !amdgcn.vgpr<?>, !amdgcn.vgpr<?>
  %c0_i32_mig2 = arith.constant 0 : i32
  %token = amdgcn.global_load_dword dest %0 addr %4 offset c(%c0_i32_mig2) : outs(!amdgcn.vgpr<?>) ins(!amdgcn.vgpr<[? : ? + 2]>) mods(i32) -> !amdgcn.read_token<flat>
  amdgcn.v_mov_b32 outs(%1) ins(%0) : outs(!amdgcn.vgpr<?>) ins(!amdgcn.vgpr<?>)
  amdgcn.test_inst ins %1 : (!amdgcn.vgpr<?>) -> ()
  return
}

// CHECK-LABEL:   func.func @multiple_loads_multiple_consumers() {
// CHECK:           %[[ALLOCA_0:.*]] = memref.alloca() : memref<!amdgcn.read_token<flat>>
// CHECK:           %[[ALLOCA_1:.*]] = memref.alloca() : memref<!amdgcn.read_token<flat>>
// CHECK-DAG:       %[[CONSTANT_0:.*]] = arith.constant 8 : i32
// CHECK-DAG:       %[[CONSTANT_1:.*]] = arith.constant 4 : i32
// CHECK-DAG:       %[[CONSTANT_2:.*]] = arith.constant 0 : i32
// CHECK:           %[[ALLOCA_2:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:           %[[ALLOCA_3:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:           %[[ALLOCA_4:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:           %[[ALLOCA_5:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:           %[[MAKE_REGISTER_RANGE_0:.*]] = amdgcn.make_register_range %[[ALLOCA_4]], %[[ALLOCA_5]] : !amdgcn.vgpr<?>, !amdgcn.vgpr<?>
// CHECK:           %[[LOAD_0:.*]] = amdgcn.global_load_dword dest %[[ALLOCA_2]] addr %[[MAKE_REGISTER_RANGE_0]] offset c(%[[CONSTANT_2]]) : outs(!amdgcn.vgpr<?>) ins(!amdgcn.vgpr<[? : ? + 2]>) mods(i32) -> !amdgcn.read_token<flat>
// CHECK:           memref.store %[[LOAD_0]], %[[ALLOCA_1]][] : memref<!amdgcn.read_token<flat>>
// CHECK:           %[[LOAD_1:.*]] = amdgcn.global_load_dword dest %[[ALLOCA_3]] addr %[[MAKE_REGISTER_RANGE_0]] offset c(%[[CONSTANT_1]]) : outs(!amdgcn.vgpr<?>) ins(!amdgcn.vgpr<[? : ? + 2]>) mods(i32) -> !amdgcn.read_token<flat>
// CHECK:           memref.store %[[LOAD_1]], %[[ALLOCA_0]][] : memref<!amdgcn.read_token<flat>>
// CHECK:           %[[LOAD_2:.*]] = memref.load %[[ALLOCA_1]][] : memref<!amdgcn.read_token<flat>>
// CHECK:           amdgcn.wait deps %[[LOAD_2]] : !amdgcn.read_token<flat> -> !amdgcn.fence_token
// CHECK:           %[[STORE_0:.*]] = amdgcn.global_store_dword data %[[ALLOCA_2]] addr %[[MAKE_REGISTER_RANGE_0]] offset c(%[[CONSTANT_2]]) : ins(!amdgcn.vgpr<?>, !amdgcn.vgpr<[? : ? + 2]>) mods(i32) -> !amdgcn.write_token<flat>
// CHECK:           %[[LOAD_3:.*]] = memref.load %[[ALLOCA_0]][] : memref<!amdgcn.read_token<flat>>
// CHECK:           amdgcn.wait deps %[[LOAD_3]] : !amdgcn.read_token<flat> -> !amdgcn.fence_token
// CHECK:           %[[STORE_1:.*]] = amdgcn.global_store_dword data %[[ALLOCA_3]] addr %[[MAKE_REGISTER_RANGE_0]] offset c(%[[CONSTANT_0]]) : ins(!amdgcn.vgpr<?>, !amdgcn.vgpr<[? : ? + 2]>) mods(i32) -> !amdgcn.write_token<flat>
// CHECK:           return
// CHECK:         }
func.func @multiple_loads_multiple_consumers() {
  %c8_i32 = arith.constant 8 : i32
  %c4_i32 = arith.constant 4 : i32
  %c0_i32 = arith.constant 0 : i32
  %0 = amdgcn.alloca : !amdgcn.vgpr<?>
  %1 = amdgcn.alloca : !amdgcn.vgpr<?>
  %2 = amdgcn.alloca : !amdgcn.vgpr<?>
  %3 = amdgcn.alloca : !amdgcn.vgpr<?>
  %4 = amdgcn.make_register_range %2, %3 : !amdgcn.vgpr<?>, !amdgcn.vgpr<?>
  %token = amdgcn.global_load_dword dest %0 addr %4 offset c(%c0_i32) : outs(!amdgcn.vgpr<?>) ins(!amdgcn.vgpr<[? : ? + 2]>) mods(i32) -> !amdgcn.read_token<flat>
  %token_0 = amdgcn.global_load_dword dest %1 addr %4 offset c(%c4_i32) : outs(!amdgcn.vgpr<?>) ins(!amdgcn.vgpr<[? : ? + 2]>) mods(i32) -> !amdgcn.read_token<flat>
  %5 = amdgcn.global_store_dword data %0 addr %4 offset c(%c0_i32) : ins(!amdgcn.vgpr<?>, !amdgcn.vgpr<[? : ? + 2]>) mods(i32) -> !amdgcn.write_token<flat>
  %6 = amdgcn.global_store_dword data %1 addr %4 offset c(%c8_i32) : ins(!amdgcn.vgpr<?>, !amdgcn.vgpr<[? : ? + 2]>) mods(i32) -> !amdgcn.write_token<flat>
  return
}

// CHECK-LABEL:   func.func @load_with_existing_wait() {
// CHECK:           %[[ALLOCA_0:.*]] = memref.alloca() : memref<!amdgcn.read_token<flat>>
// CHECK:           %[[ALLOCA_1:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:           %[[ALLOCA_2:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:           %[[MAKE_REGISTER_RANGE_0:.*]] = amdgcn.make_register_range %[[ALLOCA_1]], %[[ALLOCA_2]] : !amdgcn.vgpr<?>, !amdgcn.vgpr<?>
// CHECK:           %[[ALLOCA_3:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:           %[[LOAD_0:.*]] = amdgcn.global_load_dword dest %[[ALLOCA_3]] addr %[[MAKE_REGISTER_RANGE_0]] offset c(%{{.*}}) : outs(!amdgcn.vgpr<?>) ins(!amdgcn.vgpr<[? : ? + 2]>) mods(i32) -> !amdgcn.read_token<flat>
// CHECK:           memref.store %[[LOAD_0]], %[[ALLOCA_0]][] : memref<!amdgcn.read_token<flat>>
// CHECK:           amdgcn.wait deps %[[LOAD_0]] : !amdgcn.read_token<flat> -> !amdgcn.fence_token
// CHECK:           %[[LOAD_1:.*]] = memref.load %[[ALLOCA_0]][] : memref<!amdgcn.read_token<flat>>
// CHECK:           amdgcn.wait deps %[[LOAD_1]] : !amdgcn.read_token<flat> -> !amdgcn.fence_token
// CHECK:           %[[STORE_0:.*]] = amdgcn.global_store_dword data %[[ALLOCA_3]] addr %[[MAKE_REGISTER_RANGE_0]] offset c(%{{.*}}) : ins(!amdgcn.vgpr<?>, !amdgcn.vgpr<[? : ? + 2]>) mods(i32) -> !amdgcn.write_token<flat>
// CHECK:           return
// CHECK:         }
func.func @load_with_existing_wait() {
  %0 = amdgcn.alloca : !amdgcn.vgpr<?>
  %1 = amdgcn.alloca : !amdgcn.vgpr<?>
  %2 = amdgcn.make_register_range %0, %1 : !amdgcn.vgpr<?>, !amdgcn.vgpr<?>
  %3 = amdgcn.alloca : !amdgcn.vgpr<?>
  %c0_i32_mig3 = arith.constant 0 : i32
  %token = amdgcn.global_load_dword dest %3 addr %2 offset c(%c0_i32_mig3) : outs(!amdgcn.vgpr<?>) ins(!amdgcn.vgpr<[? : ? + 2]>) mods(i32) -> !amdgcn.read_token<flat>
  %wf0 = amdgcn.wait deps %token : !amdgcn.read_token<flat> -> !amdgcn.fence_token
  %c0_i32_mig2 = arith.constant 0 : i32
  %4 = amdgcn.global_store_dword data %3 addr %2 offset c(%c0_i32_mig2) : ins(!amdgcn.vgpr<?>, !amdgcn.vgpr<[? : ? + 2]>) mods(i32) -> !amdgcn.write_token<flat>
  return
}

// CHECK-LABEL:   func.func @load_in_branch_consumed_in_merge(
// CHECK-SAME:      %[[ARG0:.*]]: i1) {
// CHECK:           %[[ALLOCA_0:.*]] = memref.alloca() : memref<!amdgcn.read_token<flat>>
// CHECK:           %[[ALLOCA_1:.*]] = memref.alloca() : memref<!amdgcn.read_token<flat>>
// CHECK:           %[[ALLOCA_2:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:           %[[ALLOCA_3:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:           %[[ALLOCA_4:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:           %[[ALLOCA_5:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:           %[[ALLOCA_6:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:           %[[ALLOCA_7:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:           %[[MAKE_REGISTER_RANGE_0:.*]] = amdgcn.make_register_range %[[ALLOCA_6]], %[[ALLOCA_7]] : !amdgcn.vgpr<?>, !amdgcn.vgpr<?>
// CHECK:           cf.cond_br %[[ARG0]], ^bb1, ^bb2
// CHECK:         ^bb1:
// CHECK:           %[[LOAD_0:.*]] = amdgcn.global_load_dword dest %[[ALLOCA_4]] addr %[[MAKE_REGISTER_RANGE_0]] offset c(%{{.*}}) : outs(!amdgcn.vgpr<?>) ins(!amdgcn.vgpr<[? : ? + 2]>) mods(i32) -> !amdgcn.read_token<flat>
// CHECK:           memref.store %[[LOAD_0]], %[[ALLOCA_1]][] : memref<!amdgcn.read_token<flat>>
// CHECK:           %[[LOAD_1:.*]] = memref.load %[[ALLOCA_1]][] : memref<!amdgcn.read_token<flat>>
// CHECK:           amdgcn.wait deps %[[LOAD_1]] : !amdgcn.read_token<flat> -> !amdgcn.fence_token
// CHECK:           lsir.copy %[[ALLOCA_2]], %[[ALLOCA_4]] : !amdgcn.vgpr<?>, !amdgcn.vgpr<?>
// CHECK:           cf.br ^bb3
// CHECK:         ^bb2:
// CHECK:           %[[LOAD_2:.*]] = amdgcn.global_load_dword dest %[[ALLOCA_5]] addr %[[MAKE_REGISTER_RANGE_0]] offset c(%{{.*}}) : outs(!amdgcn.vgpr<?>) ins(!amdgcn.vgpr<[? : ? + 2]>) mods(i32) -> !amdgcn.read_token<flat>
// CHECK:           memref.store %[[LOAD_2]], %[[ALLOCA_0]][] : memref<!amdgcn.read_token<flat>>
// CHECK:           %[[LOAD_3:.*]] = memref.load %[[ALLOCA_0]][] : memref<!amdgcn.read_token<flat>>
// CHECK:           amdgcn.wait deps %[[LOAD_3]] : !amdgcn.read_token<flat> -> !amdgcn.fence_token
// CHECK:           lsir.copy %[[ALLOCA_2]], %[[ALLOCA_5]] : !amdgcn.vgpr<?>, !amdgcn.vgpr<?>
// CHECK:           cf.br ^bb3
// CHECK:         ^bb3:
// CHECK:           lsir.copy %[[ALLOCA_3]], %[[ALLOCA_2]] : !amdgcn.vgpr<?>, !amdgcn.vgpr<?>
// CHECK:           %[[STORE_0:.*]] = amdgcn.global_store_dword data %[[ALLOCA_3]] addr %[[MAKE_REGISTER_RANGE_0]] offset c(%{{.*}}) : ins(!amdgcn.vgpr<?>, !amdgcn.vgpr<[? : ? + 2]>) mods(i32) -> !amdgcn.write_token<flat>
// CHECK:           return
// CHECK:         }
func.func @load_in_branch_consumed_in_merge(%arg0: i1) {
  %0 = amdgcn.alloca : !amdgcn.vgpr<?>
  %1 = amdgcn.alloca : !amdgcn.vgpr<?>
  %2 = amdgcn.alloca : !amdgcn.vgpr<?>
  %3 = amdgcn.alloca : !amdgcn.vgpr<?>
  %4 = amdgcn.alloca : !amdgcn.vgpr<?>
  %5 = amdgcn.alloca : !amdgcn.vgpr<?>
  %6 = amdgcn.make_register_range %4, %5 : !amdgcn.vgpr<?>, !amdgcn.vgpr<?>
  cf.cond_br %arg0, ^bb1, ^bb2
^bb1:  // pred: ^bb0
  %c0_i32_mig4 = arith.constant 0 : i32
  %token = amdgcn.global_load_dword dest %2 addr %6 offset c(%c0_i32_mig4) : outs(!amdgcn.vgpr<?>) ins(!amdgcn.vgpr<[? : ? + 2]>) mods(i32) -> !amdgcn.read_token<flat>
  lsir.copy %0, %2 : !amdgcn.vgpr<?>, !amdgcn.vgpr<?>
  cf.br ^bb3
^bb2:  // pred: ^bb0
  %c0_i32_mig5 = arith.constant 0 : i32
  %token_0 = amdgcn.global_load_dword dest %3 addr %6 offset c(%c0_i32_mig5) : outs(!amdgcn.vgpr<?>) ins(!amdgcn.vgpr<[? : ? + 2]>) mods(i32) -> !amdgcn.read_token<flat>
  lsir.copy %0, %3 : !amdgcn.vgpr<?>, !amdgcn.vgpr<?>
  cf.br ^bb3
^bb3:  // 2 preds: ^bb1, ^bb2
  lsir.copy %1, %0 : !amdgcn.vgpr<?>, !amdgcn.vgpr<?>
  %c0_i32_mig3 = arith.constant 0 : i32
  %7 = amdgcn.global_store_dword data %1 addr %6 offset c(%c0_i32_mig3) : ins(!amdgcn.vgpr<?>, !amdgcn.vgpr<[? : ? + 2]>) mods(i32) -> !amdgcn.write_token<flat>
  return
}

// CHECK-LABEL:   func.func @no_load_consumption() {
// CHECK:           %[[ALLOCA_0:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:           %[[ALLOCA_1:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:           %[[ALLOCA_2:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:           %[[MAKE_REGISTER_RANGE_0:.*]] = amdgcn.make_register_range %[[ALLOCA_1]], %[[ALLOCA_2]] : !amdgcn.vgpr<?>, !amdgcn.vgpr<?>
// CHECK:           %[[STORE_0:.*]] = amdgcn.global_store_dword data %[[ALLOCA_0]] addr %[[MAKE_REGISTER_RANGE_0]] offset c(%{{.*}}) : ins(!amdgcn.vgpr<?>, !amdgcn.vgpr<[? : ? + 2]>) mods(i32) -> !amdgcn.write_token<flat>
// CHECK:           return
// CHECK:         }
func.func @no_load_consumption() {
  %0 = amdgcn.alloca : !amdgcn.vgpr<?>
  %1 = amdgcn.alloca : !amdgcn.vgpr<?>
  %2 = amdgcn.alloca : !amdgcn.vgpr<?>
  %3 = amdgcn.make_register_range %1, %2 : !amdgcn.vgpr<?>, !amdgcn.vgpr<?>
  %c0_i32_mig4 = arith.constant 0 : i32
  %4 = amdgcn.global_store_dword data %0 addr %3 offset c(%c0_i32_mig4) : ins(!amdgcn.vgpr<?>, !amdgcn.vgpr<[? : ? + 2]>) mods(i32) -> !amdgcn.write_token<flat>
  return
}

// CHECK-LABEL:   func.func @load_in_loop() {
// CHECK:           %[[ALLOCA_0:.*]] = memref.alloca() : memref<!amdgcn.read_token<flat>>
// CHECK-DAG:       %[[CONSTANT_0:.*]] = arith.constant 4 : index
// CHECK-DAG:       %[[CONSTANT_1:.*]] = arith.constant 1 : index
// CHECK-DAG:       %[[CONSTANT_2:.*]] = arith.constant 0 : index
// CHECK:           %[[ALLOCA_1:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:           %[[ALLOCA_2:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:           %[[ALLOCA_3:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:           %[[MAKE_REGISTER_RANGE_0:.*]] = amdgcn.make_register_range %[[ALLOCA_2]], %[[ALLOCA_3]] : !amdgcn.vgpr<?>, !amdgcn.vgpr<?>
// CHECK:           cf.br ^bb1(%[[CONSTANT_2]] : index)
// CHECK:         ^bb1(%[[VAL_0:.*]]: index):
// CHECK:           %[[LOAD_1:.*]] = amdgcn.global_load_dword dest %[[ALLOCA_1]] addr %[[MAKE_REGISTER_RANGE_0]] offset c(%{{.*}}) : outs(!amdgcn.vgpr<?>) ins(!amdgcn.vgpr<[? : ? + 2]>) mods(i32) -> !amdgcn.read_token<flat>
// CHECK:           memref.store %[[LOAD_1]], %[[ALLOCA_0]][] : memref<!amdgcn.read_token<flat>>
// CHECK:           %[[LOAD_2:.*]] = memref.load %[[ALLOCA_0]][] : memref<!amdgcn.read_token<flat>>
// CHECK:           amdgcn.wait deps %[[LOAD_2]] : !amdgcn.read_token<flat> -> !amdgcn.fence_token
// CHECK:           %[[STORE_0:.*]] = amdgcn.global_store_dword data %[[ALLOCA_1]] addr %[[MAKE_REGISTER_RANGE_0]] offset c(%{{.*}}) : ins(!amdgcn.vgpr<?>, !amdgcn.vgpr<[? : ? + 2]>) mods(i32) -> !amdgcn.write_token<flat>
// CHECK:           %[[ADDI_0:.*]] = arith.addi %[[VAL_0]], %[[CONSTANT_1]] : index
// CHECK:           %[[CMPI_0:.*]] = arith.cmpi ult, %[[ADDI_0]], %[[CONSTANT_0]] : index
// CHECK:           cf.cond_br %[[CMPI_0]], ^bb1(%[[ADDI_0]] : index), ^bb2
// CHECK:         ^bb2:
// CHECK:           return
// CHECK:         }
func.func @load_in_loop() {
  %c4 = arith.constant 4 : index
  %c1 = arith.constant 1 : index
  %c0 = arith.constant 0 : index
  %0 = amdgcn.alloca : !amdgcn.vgpr<?>
  %1 = amdgcn.alloca : !amdgcn.vgpr<?>
  %2 = amdgcn.alloca : !amdgcn.vgpr<?>
  %3 = amdgcn.make_register_range %1, %2 : !amdgcn.vgpr<?>, !amdgcn.vgpr<?>
  cf.br ^bb1(%c0 : index)
^bb1(%4: index):  // 2 preds: ^bb0, ^bb1
  %c0_i32_mig6 = arith.constant 0 : i32
  %token = amdgcn.global_load_dword dest %0 addr %3 offset c(%c0_i32_mig6) : outs(!amdgcn.vgpr<?>) ins(!amdgcn.vgpr<[? : ? + 2]>) mods(i32) -> !amdgcn.read_token<flat>
  %c0_i32_mig5 = arith.constant 0 : i32
  %5 = amdgcn.global_store_dword data %0 addr %3 offset c(%c0_i32_mig5) : ins(!amdgcn.vgpr<?>, !amdgcn.vgpr<[? : ? + 2]>) mods(i32) -> !amdgcn.write_token<flat>
  %6 = arith.addi %4, %c1 : index
  %7 = arith.cmpi ult, %6, %c4 : index
  cf.cond_br %7, ^bb1(%6 : index), ^bb2
^bb2:  // pred: ^bb1
  return
}

// CHECK-LABEL:   func.func @ds_load_store() {
// CHECK:           %[[ALLOCA_0:.*]] = memref.alloca() : memref<!amdgcn.read_token<shared>>
// CHECK:           %[[ALLOCA_1:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:           %[[ALLOCA_2:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:           %[[LOAD_0:.*]] = amdgcn.ds_read_b32 dest %[[ALLOCA_1]] addr %[[ALLOCA_2]] offset c(%{{.*}}) : outs(!amdgcn.vgpr<?>) ins(<?>) mods(i32) -> !amdgcn.read_token<shared>
// CHECK:           memref.store %[[LOAD_0]], %[[ALLOCA_0]][] : memref<!amdgcn.read_token<shared>>
// CHECK:           %[[LOAD_1:.*]] = memref.load %[[ALLOCA_0]][] : memref<!amdgcn.read_token<shared>>
// CHECK:           amdgcn.wait deps %[[LOAD_1]] : !amdgcn.read_token<shared> -> !amdgcn.fence_token
// CHECK:           %[[STORE_0:.*]] = amdgcn.ds_write_b32 data %[[ALLOCA_1]] addr %[[ALLOCA_2]] offset c(%{{.*}}) : ins(!amdgcn.vgpr<?>, <?>) mods(i32) -> !amdgcn.write_token<shared>
// CHECK:           return
// CHECK:         }
func.func @ds_load_store() {
  %0 = amdgcn.alloca : !amdgcn.vgpr<?>
  %1 = amdgcn.alloca : !amdgcn.vgpr<?>
  %c0_i32_mig1 = arith.constant 0 : i32
  %token = amdgcn.ds_read_b32 dest %0 addr %1 offset c(%c0_i32_mig1) : outs(!amdgcn.vgpr<?>) ins(<?>) mods(i32) -> !amdgcn.read_token<shared>
  %2 = amdgcn.ds_write_b32 data %0 addr %1 offset c(%c0_i32_mig1) : ins(!amdgcn.vgpr<?>, <?>) mods(i32) -> !amdgcn.write_token<shared>
  return
}

// CHECK-LABEL:   func.func @one_load_two_consumers() {
// CHECK:           %[[ALLOCA_0:.*]] = memref.alloca() : memref<!amdgcn.read_token<flat>>
// CHECK-NOT:       memref.alloca() : memref<!amdgcn.read_token<flat>>
// CHECK:           %[[ALLOCA_1:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:           %[[ALLOCA_2:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:           %[[ALLOCA_3:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:           %[[ALLOCA_4:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:           %[[MRR:.*]] = amdgcn.make_register_range %[[ALLOCA_3]], %[[ALLOCA_4]] : !amdgcn.vgpr<?>, !amdgcn.vgpr<?>
// CHECK:           %[[LOAD_0:.*]] = amdgcn.global_load_dword dest %[[ALLOCA_1]] addr %[[MRR]] offset c(%{{.*}}) : outs(!amdgcn.vgpr<?>) ins(!amdgcn.vgpr<[? : ? + 2]>) mods(i32) -> !amdgcn.read_token<flat>
// CHECK:           memref.store %[[LOAD_0]], %[[ALLOCA_0]][] : memref<!amdgcn.read_token<flat>>
// CHECK-NOT:       memref.store
// CHECK:           %{{.*}} = amdgcn.global_store_dword data %[[ALLOCA_1]] addr %[[MRR]] offset c(%{{.*}}) : ins(!amdgcn.vgpr<?>, !amdgcn.vgpr<[? : ? + 2]>) mods(i32) -> !amdgcn.write_token<flat>
// CHECK:           lsir.copy %[[ALLOCA_2]], %[[ALLOCA_1]] : !amdgcn.vgpr<?>, !amdgcn.vgpr<?>
// CHECK:           return
// CHECK:         }
func.func @one_load_two_consumers() {
  %0 = amdgcn.alloca : !amdgcn.vgpr<?>
  %1 = amdgcn.alloca : !amdgcn.vgpr<?>
  %2 = amdgcn.alloca : !amdgcn.vgpr<?>
  %3 = amdgcn.alloca : !amdgcn.vgpr<?>
  %addr = amdgcn.make_register_range %2, %3 : !amdgcn.vgpr<?>, !amdgcn.vgpr<?>
  %c0_i32_mig7 = arith.constant 0 : i32
  %token = amdgcn.global_load_dword dest %0 addr %addr offset c(%c0_i32_mig7) : outs(!amdgcn.vgpr<?>) ins(!amdgcn.vgpr<[? : ? + 2]>) mods(i32) -> !amdgcn.read_token<flat>
  %c0_i32_mig6 = arith.constant 0 : i32
  %w = amdgcn.global_store_dword data %0 addr %addr offset c(%c0_i32_mig6) : ins(!amdgcn.vgpr<?>, !amdgcn.vgpr<[? : ? + 2]>) mods(i32) -> !amdgcn.write_token<flat>
  lsir.copy %1, %0 : !amdgcn.vgpr<?>, !amdgcn.vgpr<?>
  return
}

// CHECK-LABEL:   func.func @load_killed_before_consumer() {
// CHECK:           %[[ALLOCA_0:.*]] = memref.alloca() : memref<!amdgcn.read_token<flat>>
// CHECK:           %[[ALLOCA_1:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:           %[[ALLOCA_2:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:           %[[ALLOCA_3:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:           %[[ALLOCA_4:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:           %[[MRR:.*]] = amdgcn.make_register_range %[[ALLOCA_3]], %[[ALLOCA_4]] : !amdgcn.vgpr<?>, !amdgcn.vgpr<?>
// CHECK:           %[[LOAD_0:.*]] = amdgcn.global_load_dword dest %[[ALLOCA_1]] addr %[[MRR]] offset c(%{{.*}}) : outs(!amdgcn.vgpr<?>) ins(!amdgcn.vgpr<[? : ? + 2]>) mods(i32) -> !amdgcn.read_token<flat>
// CHECK:           memref.store %[[LOAD_0]], %[[ALLOCA_0]][] : memref<!amdgcn.read_token<flat>>
// CHECK:           %[[TOK_0:.*]] = memref.load %[[ALLOCA_0]][] : memref<!amdgcn.read_token<flat>>
// CHECK:           amdgcn.wait deps %[[TOK_0]] : !amdgcn.read_token<flat> -> !amdgcn.fence_token
// CHECK:           amdgcn.v_mov_b32 outs(%[[ALLOCA_1]]) ins(%[[ALLOCA_2]]) : outs(!amdgcn.vgpr<?>) ins(!amdgcn.vgpr<?>)
// CHECK-NOT:       amdgcn.wait -> !amdgcn.fence_token
// CHECK:           %{{.*}} = amdgcn.global_store_dword data %[[ALLOCA_1]] addr %[[MRR]] offset c(%{{.*}}) : ins(!amdgcn.vgpr<?>, !amdgcn.vgpr<[? : ? + 2]>) mods(i32) -> !amdgcn.write_token<flat>
// CHECK:           return
// CHECK:         }
func.func @load_killed_before_consumer() {
  %0 = amdgcn.alloca : !amdgcn.vgpr<?>
  %1 = amdgcn.alloca : !amdgcn.vgpr<?>
  %2 = amdgcn.alloca : !amdgcn.vgpr<?>
  %3 = amdgcn.alloca : !amdgcn.vgpr<?>
  %addr = amdgcn.make_register_range %2, %3 : !amdgcn.vgpr<?>, !amdgcn.vgpr<?>
  %c0_i32_mig8 = arith.constant 0 : i32
  %token = amdgcn.global_load_dword dest %0 addr %addr offset c(%c0_i32_mig8) : outs(!amdgcn.vgpr<?>) ins(!amdgcn.vgpr<[? : ? + 2]>) mods(i32) -> !amdgcn.read_token<flat>
  amdgcn.v_mov_b32 outs(%0) ins(%1) : outs(!amdgcn.vgpr<?>) ins(!amdgcn.vgpr<?>)
  %c0_i32_mig7 = arith.constant 0 : i32
  %w = amdgcn.global_store_dword data %0 addr %addr offset c(%c0_i32_mig7) : ins(!amdgcn.vgpr<?>, !amdgcn.vgpr<[? : ? + 2]>) mods(i32) -> !amdgcn.write_token<flat>
  return
}

// CHECK-LABEL:   func.func @load_before_branch_consumed_in_both(
//  CHECK-SAME:       %[[ARG0:.*]]: i1
// CHECK:           %[[ALLOCA_0:.*]] = memref.alloca() : memref<!amdgcn.read_token<flat>>
// CHECK-NOT:       memref.alloca() : memref<!amdgcn.read_token<flat>>
// CHECK:           %[[ALLOCA_1:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:           %[[ALLOCA_2:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:           %[[ALLOCA_3:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:           %[[MRR:.*]] = amdgcn.make_register_range %[[ALLOCA_2]], %[[ALLOCA_3]] : !amdgcn.vgpr<?>, !amdgcn.vgpr<?>
// CHECK:           %[[LOAD_0:.*]] = amdgcn.global_load_dword dest %[[ALLOCA_1]] addr %[[MRR]] offset c(%{{.*}}) : outs(!amdgcn.vgpr<?>) ins(!amdgcn.vgpr<[? : ? + 2]>) mods(i32) -> !amdgcn.read_token<flat>
// CHECK:           memref.store %[[LOAD_0]], %[[ALLOCA_0]][] : memref<!amdgcn.read_token<flat>>
// CHECK:           cf.cond_br %[[ARG0]], ^bb1, ^bb2
// CHECK:         ^bb1:
// CHECK:           %[[TOK_0:.*]] = memref.load %[[ALLOCA_0]][] : memref<!amdgcn.read_token<flat>>
// CHECK:           amdgcn.wait deps %[[TOK_0]] : !amdgcn.read_token<flat> -> !amdgcn.fence_token
// CHECK:           %{{.*}} = amdgcn.global_store_dword data %[[ALLOCA_1]] addr %[[MRR]] offset c(%{{.*}}) : ins(!amdgcn.vgpr<?>, !amdgcn.vgpr<[? : ? + 2]>) mods(i32) -> !amdgcn.write_token<flat>
// CHECK:           cf.br ^bb3
// CHECK:         ^bb2:
// CHECK:           %[[TOK_1:.*]] = memref.load %[[ALLOCA_0]][] : memref<!amdgcn.read_token<flat>>
// CHECK:           amdgcn.wait deps %[[TOK_1]] : !amdgcn.read_token<flat> -> !amdgcn.fence_token
// CHECK:           %{{.*}} = amdgcn.global_store_dword data %[[ALLOCA_1]] addr %[[MRR]] offset c(%{{.*}}) : ins(!amdgcn.vgpr<?>, !amdgcn.vgpr<[? : ? + 2]>) mods(i32) -> !amdgcn.write_token<flat>
// CHECK:           cf.br ^bb3
// CHECK:         ^bb3:
// CHECK:           return
// CHECK:         }
func.func @load_before_branch_consumed_in_both(%cond: i1) {
  %0 = amdgcn.alloca : !amdgcn.vgpr<?>
  %1 = amdgcn.alloca : !amdgcn.vgpr<?>
  %2 = amdgcn.alloca : !amdgcn.vgpr<?>
  %addr = amdgcn.make_register_range %1, %2 : !amdgcn.vgpr<?>, !amdgcn.vgpr<?>
  %c0_i32_mig9 = arith.constant 0 : i32
  %token = amdgcn.global_load_dword dest %0 addr %addr offset c(%c0_i32_mig9) : outs(!amdgcn.vgpr<?>) ins(!amdgcn.vgpr<[? : ? + 2]>) mods(i32) -> !amdgcn.read_token<flat>
  cf.cond_br %cond, ^bb1, ^bb2
^bb1:
  %c0_i32_mig8 = arith.constant 0 : i32
  %w0 = amdgcn.global_store_dword data %0 addr %addr offset c(%c0_i32_mig8) : ins(!amdgcn.vgpr<?>, !amdgcn.vgpr<[? : ? + 2]>) mods(i32) -> !amdgcn.write_token<flat>
  cf.br ^bb3
^bb2:
  %w1 = amdgcn.global_store_dword data %0 addr %addr offset c(%c0_i32_mig9) : ins(!amdgcn.vgpr<?>, !amdgcn.vgpr<[? : ? + 2]>) mods(i32) -> !amdgcn.write_token<flat>
  cf.br ^bb3
^bb3:
  return
}

// CHECK-LABEL:   func.func @load_before_branch_consumed_in_single(
// CHECK-SAME:      %[[ARG0:.*]]: i1) {
// CHECK:           %[[ALLOCA_0:.*]] = memref.alloca() : memref<!amdgcn.read_token<flat>>
// CHECK:           %[[ALLOCA_1:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:           %[[ALLOCA_2:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:           %[[ALLOCA_3:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:           %[[MAKE_REGISTER_RANGE_0:.*]] = amdgcn.make_register_range %[[ALLOCA_2]], %[[ALLOCA_3]] : !amdgcn.vgpr<?>, !amdgcn.vgpr<?>
// CHECK:           %[[LOAD_0:.*]] = amdgcn.global_load_dword dest %[[ALLOCA_1]] addr %[[MAKE_REGISTER_RANGE_0]] offset c(%{{.*}}) : outs(!amdgcn.vgpr<?>) ins(!amdgcn.vgpr<[? : ? + 2]>) mods(i32) -> !amdgcn.read_token<flat>
// CHECK:           memref.store %[[LOAD_0]], %[[ALLOCA_0]][] : memref<!amdgcn.read_token<flat>>
// CHECK:           cf.cond_br %[[ARG0]], ^bb1, ^bb2
// CHECK:         ^bb1:
// CHECK:           %[[LOAD_1:.*]] = memref.load %[[ALLOCA_0]][] : memref<!amdgcn.read_token<flat>>
// CHECK:           amdgcn.wait deps %[[LOAD_1]] : !amdgcn.read_token<flat> -> !amdgcn.fence_token
// CHECK:           %[[STORE_0:.*]] = amdgcn.global_store_dword data %[[ALLOCA_1]] addr %[[MAKE_REGISTER_RANGE_0]] offset c(%{{.*}}) : ins(!amdgcn.vgpr<?>, !amdgcn.vgpr<[? : ? + 2]>) mods(i32) -> !amdgcn.write_token<flat>
// CHECK:           cf.br ^bb3
// CHECK:         ^bb2:
// CHECK:           cf.br ^bb3
// CHECK:         ^bb3:
// CHECK:           %[[LOAD_2:.*]] = memref.load %[[ALLOCA_0]][] : memref<!amdgcn.read_token<flat>>
// CHECK:           amdgcn.wait deps %[[LOAD_2]] : !amdgcn.read_token<flat> -> !amdgcn.fence_token
// CHECK:           %[[STORE_1:.*]] = amdgcn.global_store_dword data %[[ALLOCA_1]] addr %[[MAKE_REGISTER_RANGE_0]] offset c(%{{.*}}) : ins(!amdgcn.vgpr<?>, !amdgcn.vgpr<[? : ? + 2]>) mods(i32) -> !amdgcn.write_token<flat>
// CHECK:           return
// CHECK:         }
func.func @load_before_branch_consumed_in_single(%cond: i1) {
  %0 = amdgcn.alloca : !amdgcn.vgpr<?>
  %1 = amdgcn.alloca : !amdgcn.vgpr<?>
  %2 = amdgcn.alloca : !amdgcn.vgpr<?>
  %addr = amdgcn.make_register_range %1, %2 : !amdgcn.vgpr<?>, !amdgcn.vgpr<?>
  %c0_i32_mig10 = arith.constant 0 : i32
  %token = amdgcn.global_load_dword dest %0 addr %addr offset c(%c0_i32_mig10) : outs(!amdgcn.vgpr<?>) ins(!amdgcn.vgpr<[? : ? + 2]>) mods(i32) -> !amdgcn.read_token<flat>
  cf.cond_br %cond, ^bb1, ^bb2
^bb1:
  %w0 = amdgcn.global_store_dword data %0 addr %addr offset c(%c0_i32_mig10) : ins(!amdgcn.vgpr<?>, !amdgcn.vgpr<[? : ? + 2]>) mods(i32) -> !amdgcn.write_token<flat>
  cf.br ^bb3
^bb2:
  cf.br ^bb3
^bb3:
  %c0_i32_mig11 = arith.constant 0 : i32
  %w1 = amdgcn.global_store_dword data %0 addr %addr offset c(%c0_i32_mig11) : ins(!amdgcn.vgpr<?>, !amdgcn.vgpr<[? : ? + 2]>) mods(i32) -> !amdgcn.write_token<flat>
  return
}

// CHECK-LABEL:   func.func @load_before_branch_consumed_in_single_clobbered(
// CHECK-SAME:      %[[ARG0:.*]]: i1) {
// CHECK:           %[[ALLOCA_0:.*]] = memref.alloca() : memref<!amdgcn.read_token<flat>>
// CHECK:           %[[ALLOCA_1:.*]] = memref.alloca() : memref<!amdgcn.read_token<flat>>
// CHECK:           %[[ALLOCA_2:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:           %[[ALLOCA_3:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:           %[[ALLOCA_4:.*]] = amdgcn.alloca : !amdgcn.vgpr<?>
// CHECK:           %[[MAKE_REGISTER_RANGE_0:.*]] = amdgcn.make_register_range %[[ALLOCA_3]], %[[ALLOCA_4]] : !amdgcn.vgpr<?>, !amdgcn.vgpr<?>
// CHECK:           %[[LOAD_0:.*]] = amdgcn.global_load_dword dest %[[ALLOCA_2]] addr %[[MAKE_REGISTER_RANGE_0]] offset c(%{{.*}}) : outs(!amdgcn.vgpr<?>) ins(!amdgcn.vgpr<[? : ? + 2]>) mods(i32) -> !amdgcn.read_token<flat>
// CHECK:           memref.store %[[LOAD_0]], %[[ALLOCA_1]][] : memref<!amdgcn.read_token<flat>>
// CHECK:           cf.cond_br %[[ARG0]], ^bb1, ^bb2
// CHECK:         ^bb1:
// CHECK:           %[[LOAD_1:.*]] = memref.load %[[ALLOCA_1]][] : memref<!amdgcn.read_token<flat>>
// CHECK:           amdgcn.wait deps %[[LOAD_1]] : !amdgcn.read_token<flat> -> !amdgcn.fence_token
// CHECK:           %[[STORE_0:.*]] = amdgcn.global_store_dword data %[[ALLOCA_2]] addr %[[MAKE_REGISTER_RANGE_0]] offset c(%{{.*}}) : ins(!amdgcn.vgpr<?>, !amdgcn.vgpr<[? : ? + 2]>) mods(i32) -> !amdgcn.write_token<flat>
// CHECK:           cf.br ^bb3
// CHECK:         ^bb2:
// CHECK:           %[[LOAD_2:.*]] = memref.load %[[ALLOCA_1]][] : memref<!amdgcn.read_token<flat>>
// CHECK:           amdgcn.wait deps %[[LOAD_2]] : !amdgcn.read_token<flat> -> !amdgcn.fence_token
// CHECK:           %[[LOAD_3:.*]] = amdgcn.global_load_dword dest %[[ALLOCA_2]] addr %[[MAKE_REGISTER_RANGE_0]] offset c(%{{.*}}) : outs(!amdgcn.vgpr<?>) ins(!amdgcn.vgpr<[? : ? + 2]>) mods(i32) -> !amdgcn.read_token<flat>
// CHECK:           memref.store %[[LOAD_3]], %[[ALLOCA_0]][] : memref<!amdgcn.read_token<flat>>
// CHECK:           cf.br ^bb3
// CHECK:         ^bb3:
// CHECK:           %[[LOAD_4:.*]] = memref.load %[[ALLOCA_0]][] : memref<!amdgcn.read_token<flat>>
// CHECK:           amdgcn.wait deps %[[LOAD_4]] : !amdgcn.read_token<flat> -> !amdgcn.fence_token
// CHECK:           %[[STORE_1:.*]] = amdgcn.global_store_dword data %[[ALLOCA_2]] addr %[[MAKE_REGISTER_RANGE_0]] offset c(%{{.*}}) : ins(!amdgcn.vgpr<?>, !amdgcn.vgpr<[? : ? + 2]>) mods(i32) -> !amdgcn.write_token<flat>
// CHECK:           return
// CHECK:         }
func.func @load_before_branch_consumed_in_single_clobbered(%cond: i1) {
  %0 = amdgcn.alloca : !amdgcn.vgpr<?>
  %1 = amdgcn.alloca : !amdgcn.vgpr<?>
  %2 = amdgcn.alloca : !amdgcn.vgpr<?>
  %addr = amdgcn.make_register_range %1, %2 : !amdgcn.vgpr<?>, !amdgcn.vgpr<?>
  %c0_i32_mig11 = arith.constant 0 : i32
  %token = amdgcn.global_load_dword dest %0 addr %addr offset c(%c0_i32_mig11) : outs(!amdgcn.vgpr<?>) ins(!amdgcn.vgpr<[? : ? + 2]>) mods(i32) -> !amdgcn.read_token<flat>
  cf.cond_br %cond, ^bb1, ^bb2
^bb1:
  %c0_i32_mig12 = arith.constant 0 : i32
  %w0 = amdgcn.global_store_dword data %0 addr %addr offset c(%c0_i32_mig12) : ins(!amdgcn.vgpr<?>, !amdgcn.vgpr<[? : ? + 2]>) mods(i32) -> !amdgcn.write_token<flat>
  cf.br ^bb3
^bb2:
  %c0_i32_mig14 = arith.constant 0 : i32
  %token_2 = amdgcn.global_load_dword dest %0 addr %addr offset c(%c0_i32_mig14) : outs(!amdgcn.vgpr<?>) ins(!amdgcn.vgpr<[? : ? + 2]>) mods(i32) -> !amdgcn.read_token<flat>
  cf.br ^bb3
^bb3:
  %c0_i32_mig15 = arith.constant 0 : i32
  %w1 = amdgcn.global_store_dword data %0 addr %addr offset c(%c0_i32_mig15) : ins(!amdgcn.vgpr<?>, !amdgcn.vgpr<[? : ? + 2]>) mods(i32) -> !amdgcn.write_token<flat>
  return
}

// CHECK-LABEL:   func.func @remove_waits() {
// CHECK:           amdgcn.s_waitcnt vmcnt = 2 expcnt = 2 lgkmcnt = 2 immutable
// CHECK:           return
// CHECK:         }
func.func @remove_waits() {
  amdgcn.s_waitcnt vmcnt = 0 expcnt = 0 lgkmcnt = 0
  amdgcn.s_waitcnt vmcnt = 2 expcnt = 2 lgkmcnt = 2 immutable
  return
}

}
