// RUN: aster-opt --aster-scf-pipeline %s | FileCheck %s

// ============================================================================
// Three-stage pipeline: load / wait+compute / store
// Stage 0: async load (data + read_token)
// Stage 1: wait on token, compute on data
// Stage 2: make_register_range + store (write_token)
//
// Cross-stage values: token (0->1), data (0->1), computed (1->2)
// 3 iter_args in kernel.
//
// Prologue (2 sections):
//   Section 0: load(iter 0)
//   Section 1: load(iter 1), wait+compute(iter 0)
// Kernel: for i in [2, 6): all 3 stages active
// Epilogue (2 sections):
//   Section 1: wait+compute(iter 5), make_range+store(iter 4)
//   Section 2: make_range+store(iter 5)
// ============================================================================

// CHECK-LABEL: func.func @three_stage_load_compute_store

// Prologue section 0: load(iter 0)
// CHECK:       %[[P0_D:.*]], %[[P0_T:.*]] = amdgcn.global_load_dword

// Prologue section 1: load(iter 1) + wait+compute(iter 0)
// Per-iteration mappings: iter 1's load results are separate from iter 0's.
// wait+compute uses iter 0's token/data (P0_T, P0_D), not iter 1's.
// CHECK:       %[[P1_D:.*]], %[[P1_T:.*]] = amdgcn.global_load_dword
// CHECK:       amdgcn.wait deps %[[P0_T]] : !amdgcn.read_token<flat> -> !amdgcn.fence_token
// CHECK:       %[[P1_C:.*]] = amdgcn.test_inst outs %{{.*}} ins %[[P0_D]]

// Kernel: 5 iter_args (3 cross-stage + 2 i32 offsets)
// Token and data come from iter 1's load (P1_T, P1_D).
// Computed comes from iter 0's compute (P1_C).
// CHECK:       %[[KER:.*]]:5 = scf.for %{{.*}} = %{{.*}} to %{{.*}} step %{{.*}} iter_args(%[[A_T:.*]] = %[[P1_T]], %[[A_D:.*]] = %[[P1_D]], %[[A_C:.*]] = %[[P1_C]], {{.*}}) -> (!amdgcn.read_token<flat>, !amdgcn.vgpr, !amdgcn.vgpr, i32, i32)
// CHECK:         %[[K_D:.*]], %[[K_T:.*]] = amdgcn.global_load_dword
// CHECK:         amdgcn.wait deps %[[A_T]] : !amdgcn.read_token<flat> -> !amdgcn.fence_token
// CHECK:         %[[K_C:.*]] = amdgcn.test_inst outs %{{.*}} ins %[[A_D]]
// CHECK:         amdgcn.global_store_dword data %[[A_C]]
// CHECK:         scf.yield %[[K_T]], %[[K_D]], %[[K_C]]

// Epilogue section 1: wait+compute(iter 5) + store(iter 4)
// wait+compute uses kernel results #0, #1 (iter 5's stage 0 values).
// store uses kernel result #2 (iter 4's stage 1 value).
// CHECK:       amdgcn.wait deps %[[KER]]#0 : !amdgcn.read_token<flat> -> !amdgcn.fence_token
// CHECK:       %[[E1_C:.*]] = amdgcn.test_inst outs %{{.*}} ins %[[KER]]#1
// CHECK:       amdgcn.global_store_dword data %[[KER]]#2

// Epilogue section 2: store(iter 5)
// Uses the value computed in section 1 for iter 5.
// CHECK:       amdgcn.global_store_dword data %[[E1_C]]
// CHECK:       return

func.func @three_stage_load_compute_store(%addr: !amdgcn.vgpr<[? + 2]>) {
  %dest = amdgcn.alloca : !amdgcn.vgpr
  %s_compute = amdgcn.alloca : !amdgcn.vgpr
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c6 = arith.constant 6 : index
  scf.for %i = %c0 to %c6 step %c1 {
    %c0_i32_mig1 = arith.constant 0 : i32
    %data, %rtok = amdgcn.global_load_dword dest %dest addr %addr offset c(%c0_i32_mig1) {sched.stage = 0 : i32} : outs(!amdgcn.vgpr) ins(!amdgcn.vgpr<[? + 2]>) mods(i32) -> !amdgcn.read_token<flat>
    %wf0 = amdgcn.wait deps %rtok {sched.stage = 1 : i32} : !amdgcn.read_token<flat> -> !amdgcn.fence_token
    %computed = amdgcn.test_inst outs %s_compute ins %data {sched.stage = 1 : i32} : (!amdgcn.vgpr, !amdgcn.vgpr) -> !amdgcn.vgpr
    %wtok = amdgcn.global_store_dword data %computed addr %addr offset c(%c0_i32_mig1) {sched.stage = 2 : i32} : ins(!amdgcn.vgpr, !amdgcn.vgpr<[? + 2]>) mods(i32) -> !amdgcn.write_token<flat>
  }
  return
}
